### ISSUE TITLE
Cannot get a reading on the app

### ISSUE THREAD

**Issue by mjphillips20** [nightscout/nightguard#1]
Nightscout app is working, but I cannot get a reading to show on the nightguard app or the watch app.

**Comment by dhermanns** [comment]
Did you enter the protocol in your uri to your nightscout backend? Typically https://?

What version is your nightscout backend?
If nothing helps, you can send me a personal
message with your uri and I will check what could be the problem...

**Comment by dhermanns** [comment]
Hopefuly V1.2.0 in the App Store should improve this now. Https will be prefixed automatically and sync to watch is improved.

**Comment by mjphillips20** [comment]
Love this app so much. It's working great! Only request I would have is to add arrows next to the number if there are any. Any chance we will see this in the future?

**Comment by dhermanns** [comment]
Hi!

Yes - I always wanted to add that, too. But now I think the number is much
more precise than the arrows are.

But I keep this in mind. Maybe someone else can provide a pull request for
it...
mjphillips20 <notifications@github.com> schrieb am Do. 28. Juli 2016 um
16:38:

> Love this app so much. It's working great! Only request I would have is to
> add arrows next to the number if there are any. Any chance we will see this
> in the future?
>
> Sent from my iPhone
>

**Comment by rodericj** [comment]
I'd like to take a stab at a PR for this, but I may not have bandwidth for a few days.
