### ISSUE TITLE
App badge displays the wrong units

### ISSUE THREAD

**Issue by derivadow** [nightscout/nightguard#100]
The app badge always displays BG in my/dL even when app set to use mmol/L which results in the wrong info being displayed (on the badge)

**Comment by dhermanns** [comment]
Hi Tom!

Thanks for this feedback. I can reproduce this. I will have a look how this
can be fixed.

Tom Scott <notifications@github.com> schrieb am Mi. 29. Juli 2020 um 23:37:

**Comment by dhermanns** [comment]
I've made a fix for it. A new Testflight build should be available soon here:
https://testflight.apple.com/join/Ub8WcpcE

**Comment by dhermanns** [comment]
V2.9.0.257 is available now for a testflight. Click the link above.

**Comment by derivadow** [comment]
Thanks, looks like it's fixed for me too :)
