### ISSUE TITLE
Testflight version with additional watch info (COB,IOB etc) -display of BG "time ago" unreadable on Watch series 3

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/nightguard#103]
Hi,

The Testflight version 2.9.0 with additional watch info (COB,IOB etc):

The display of BG "time ago" is unreadable on Watch series 3, see photo.

https://www.dropbox.com/s/izlp06pig1vbe74/2020-08-12%2020.49.14.jpg?dl=0

**Comment by dhermanns** [comment]
Thanks for your feedback! What size is your watch?

**Comment by bjornoleh** [comment]
Hi,

This is the 38 mm Series 3.

tor. 13. aug. 2020 kl. 06:12 skrev dhermanns <notifications@github.com>:

**Comment by dhermanns** [comment]
This should be fixed now with the upcoming testflight release.

**Comment by bjornoleh** [comment]
Confirmed!

Thanks!

tor. 13. aug. 2020, 21:31 skrev dhermanns <notifications@github.com>:

**Comment by dhermanns** [comment]
Great - thanks for your help!
