### ISSUE TITLE
More Finnish translations

### ISSUE THREAD

**Issue by dhermanns** [nightscout/nightguard#104]
Hi @makotila!

Could you have a look at the new labels?
I changed a label on the preferences screen and there is a new "Care" tab.
I already added the entries to the Finnish resource files.

cu,
Dirk

**Comment by makotila** [comment]
Yes, sorry delay, I'll check asap, a little busy time atm

**Comment by dhermanns** [comment]
No problem - thx for your work!

**Comment by dhermanns** [comment]
Hi Markus - I got two more labels. If you could have a look ;-)
