### ISSUE TITLE
Allow users to pick displayed units locally

### ISSUE THREAD

**Issue by sulkaharo** [nightscout/nightguard#106]
Hi! Looks like Nightguard's detection of units to be displayed to the user is based on units loaded from Nightscout and this is failing at least when used against DEV. I'd recommend you allow the units to be selected locally in the app settings and just defaulting to the units from Nightscout, as many users don't have the setting set correctly in NS. Additionally, when reading the setting from NS, I'd recommend simply doing a case insensitive comparison to the units string to see if it contains "mmol" to determine what the units are.

**Comment by dhermanns** [comment]
Hi Sulka Haro!

Did you try that with the latest testflight version of nightguard? I already made a fix there.

**Comment by dhermanns** [comment]
Nevertheless - it's always good to have an option ;-) . The upcoming release will introduce a switch for that.
