### ISSUE TITLE
Inclusive graph design (stats screen)

### ISSUE THREAD

**Issue by derivadow** [nightscout/nightguard#108]
The choice of colours on the stats screen isn't accessible to colour blind users. Specifically the red, green and yellow are indistinguishable to people with different colour blindnesses.

**Comment by dhermanns** [comment]
Hi Tom!

Thanks for your Feedback. Did you try the TestFlight V3.0.0? I did change
the colors there.

**Comment by derivadow** [comment]
Yes, I'm testing with 3.0.0.579. Do you want screen grabs of the simulations for different forms of colour blindness?

**Comment by dhermanns** [comment]
Did you had less problems with the old color scheme?

If you could propose different colors I could introduce a color scheme
selector to change to your preferred colors.

**Comment by derivadow** [comment]
Hi, I don't know about the previous colour scheme. I'm not colour blind but I spotted the update and thought I would help out with a spot of testing.

In terms of what to pick (and looking at the design of the rest of the app) something like: 
#F5793A
#A95AA1
#85C0F9
#C6D4E1
#0F2080

FYI red/green colour blindness is the most common but people can also be blue/yellow or completely colour blind. Combinations to avoid include:

Red & green
Green & brown
Green & blue
Blue & gray
Blue & purple
Green & gray
Green & black

If that's not possible then then adjusting the shade (one very dark the other very light can work (most colour blind people can detect contrast).

**Comment by dhermanns** [comment]
I loved your suggested colors and used it as a default for the statistics view now. Thx ;-)

**Comment by derivadow** [comment]
Really glad to have been able to help. I've simulated for protanope, deuteranope, tritanope and I think you can differentiate all the lines in all cases.

**Comment by dhermanns** [comment]
Thanks Tom for your help. That's what makes nightscout so powerful!
