### ISSUE TITLE
Displays BG in mg/dl erronously

### ISSUE THREAD

**Issue by oddst** [nightscout/nightguard#109]
All other Nightscout clients show BG AS mmol/L, but not Nightguard. But NightGuard believes 128 is a mmol/L value and triggere high alarms Even though high alarm is set to 180 mg/dl (or rather 10.0 mmol/L).

Other NS clients are:
Nightscout in Chrome/Firefox/Edge
Nightscout X on iOS
Loop Follow app om iOS
Xdrip4iOS

**Comment by dhermanns** [comment]
Hi!

Sorry that I can‘t meet your expectations.
I‘m using mgdl myself and therefore testing mmol is much harder for me.

But I know that we have multiple beta testers using mmol. But actually no
one else reported this.

Can you tell us what version of nightguard you are using?

The latest TestFlight could already have a fix for this. Further more you
could manually force mmol whatever you have configured on your backend in
V3.0.0.

**Comment by oddst** [comment]
Hi, started writing earlier, but then 3.0.0.591 became available through Apple App STore.

That solves the problem, even the automatic selection choice works.

So, problem solved... :) 

BR Odd

**Comment by dhermanns** [comment]
Sounds great.
