### ISSUE TITLE
OpenAPS functionality plans?

### ISSUE THREAD

**Issue by JELCRAWFORD** [nightscout/nightguard#11]
App currently does not support OpenAPS functions. What are plans in this regard?

**Comment by dhermanns** [comment]
Hi!

Nothing planned so far, since I don't have a pump that can be used with
openaps.

But nightguard is an open source project so maybe someone else can
contribute...
JELCRAWFORD <notifications@github.com> schrieb am Fr. 14. Apr. 2017 um
08:03:

**Comment by dhermanns** [comment]
I've successfuly installed openaps now, but still have no pump and therefore no usecase to put the additional openaps features to work. If someone else sees this ticket and is able to help. Please reopen...

**Comment by aliswalker** [comment]
Reopening to see if there's more interest in this? I wouldn't know where to start myself but hopefully someone is keen

The ability to write to NS e.g. for Carbs, from Watch, should be a good foundation. Then other features like bolus and/or calculator

**Comment by dhermanns** [comment]
Did you see the new V3.0.0 Feature to set temporary targets?

That will be next to come to the watch, too.

**Comment by aliswalker** [comment]
Thanks, I hadn't. App Store is 2.8.0 and latest release showing here is 2.7.5.542 - is there somewhere more up to date I should be looking? Or can help with?

**Comment by dhermanns** [comment]
You can try the TestFlight Version if you like:

https://testflight.apple.com/join/Ub8WcpcE
