### ISSUE TITLE
Temporary target displayed as mg/dL with mmol units

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/nightguard#111]
Hi, just a little observation, please see the screenshot.

The temporary target (TT) is displayed as mg/dL, with mmol units used otherwise.

Its the latest version, installed today. 

![Skjermbil](https://user-images.githubusercontent.com/63544115/92758061-a35e6700-f38e-11ea-9a84-5475e65e7f70.jpg)

The temp target is displayed correctly in Nightscout, but not enacted in Loop. But I supppse temp targets are not used at all in Loop, just in AAPS or OpenAPS? 

(Loop use temporary overrides for both targets and "% insulin need" overrides.)

**Comment by dhermanns** [comment]
Hi!

Thanks for your Feedback. I will have a look. Temparary Targets are the
same as if set by the nightscout site. So could be that it has no effect
with loop, if they use a different format.

OpenAps and Aaps should work.

**Comment by bjornoleh** [comment]
Thanks.

Regarding Loop, yes, Temporary override and Temporary override cancel is used from NS Careportal. Perhaps that can be added as well? No big deal to activate it from NS, but perhaps the effort of adding it to Nightguard is limited.

![20200910_181538](https://user-images.githubusercontent.com/63544115/92761254-c9d1d180-f391-11ea-9a47-daf4de7b614a.jpg)

**Comment by bjornoleh** [comment]
Thinking about it again, perhaps adding override functionality to work with loop is not quite as easy after all. As far as I know, it requires reading and actibating the preset overrides which are stored in the "profile" collection. So it is a little different from how the temporary targets seem to work.

But that was an aside from the actual issue anyways.

**Comment by dhermanns** [comment]
Upcoming V3.0.2 will convert the internally used mg/dl to mmol if that's the desired display unit.
