### ISSUE TITLE
Cage and Sage not displayed properly

### ISSUE THREAD

**Issue by OpossumGit** [nightscout/nightguard#113]
Cage and sage values are visible on my Nightscout site
![image](https://user-images.githubusercontent.com/9529545/92995231-f573c980-f501-11ea-9f74-35093671a553.png)

Nightguard shows zeroes
![image](https://user-images.githubusercontent.com/9529545/92995237-045a7c00-f502-11ea-8e93-d3357d8f3dec.png)
For some time cage was working, while sage was displaying one day off until it reverted to zero

**Comment by dhermanns** [comment]
Hi!

Sage should be fixed with 3.0.2. You can verify this on Testflight:

https://testflight.apple.com/join/Ub8WcpcE

You can leave me your Url if cage is still a problem.

**Comment by OpossumGit** [comment]
It's dorans.herokuapp.com Please acknowledge you got it as I'd like to edit this comment later as I do not want to leave the link public

**Comment by dhermanns** [comment]
Deleted it for you ;-)

**Comment by dhermanns** [comment]
Site Change Events will now be queried for the last 5 days. So in your case we should find them in V3.0.2 now, too.
