### ISSUE TITLE
Question mark instead of glucose delta

### ISSUE THREAD

**Issue by andruhamessi** [nightscout/nightguard#114]
Glucose delta disappeared on the last update. 
![F2491662-3865-4486-B436-4D1D9984F111](https://user-images.githubusercontent.com/34947737/93008159-42938200-f57a-11ea-93ae-a4eefe845c06.jpeg)
 

Also would be nice to have option to hide careportal data.

**Comment by dhermanns** [comment]
Hi!

V3.0.2 is available in App Store now. It should be fixed with this version.

Cu,
Dirk
