### ISSUE TITLE
Delta 

### ISSUE THREAD

**Issue by craigpress** [nightscout/nightguard#115]
I don’t see the change in BG anymore. It just shows a question mark. 

Also if you select info, I have to scroll all the way to the bottom to tap on close.

**Comment by dhermanns** [comment]
Hi! Please load V3.0.2 from the Appstore.
Should be the same as #114.

Do you mean the Info on the watch?

**Comment by craigpress** [comment]
Yup fixed!

________________________________

**Comment by dhermanns** [comment]
Ah ok - now I understand your cancel issue on the watch: This happens on WatchOS7 only. Seems to be a change introduced by the update. I will see what I can do...

**Comment by craigpress** [comment]
It all seems fixed now for me. Just FYI

________________________________
