### ISSUE TITLE
Missing watch complication

### ISSUE THREAD

**Issue by derivadow** [nightscout/nightguard#119]
In the latest build (3.1.0.602) the watch complication is missing

**Comment by dhermanns** [comment]
Hi Tom! What complication is missing? I just had a look and Infograph
Complication together with others is fine on my watch.

Tom Scott <notifications@github.com> schrieb am Mo. 28. Sept. 2020 um 07:31:

**Comment by derivadow** [comment]
On my watch there are no complications, nothing is installed on the watch at all (app nor complications) and no option to do so.

**Comment by dhermanns** [comment]
Did you try to reinstall the ios Part? Maybe something has gone wrong
during update.

Tom Scott <notifications@github.com> schrieb am Mo. 28. Sept. 2020 um 10:27:

**Comment by dhermanns** [comment]
Ah ok - had another user with problems. I'm right now rewriting the watch to support the new swift-ui display technology. And this some features I need are supported by watchos 7 only. Therefore the first and second Apple Watch can't be supported anymore.

If you still would like to use this watch, you will need to stay with the latest App-Store Version V3.0.x.
Sorry
