### ISSUE TITLE
Readings switch between mmol to mg/dl

### ISSUE THREAD

**Issue by Sushalucy** [nightscout/nightguard#122]
My readings always show as mmol on my iPhone, however, they switch between mmol and mg/dl on the apple watch.

**Comment by dhermanns** [comment]
Hi Sishalucy!

Are you on the latest Nightscout Version 14.0.6?
They did a bugfix lately.

I‘m currently working around it. So you could alternatively use the latest
TestFlight Version.

Cu,
Dirk

Sushalucy <notifications@github.com> schrieb am Sa. 3. Okt. 2020 um 14:48:

**Comment by Sushalucy** [comment]
Thank you so much. I tried to update just now but couldn’t find the video.  I will try the test flight version now. 

Thanks again 

Siân Walker
