### ISSUE TITLE
Wrong alert units

### ISSUE THREAD

**Issue by derivadow** [nightscout/nightguard#123]
Using mmol/L but the data on the app badge & iOS alerts is displaying the data as mg/dL 

Version: 3.1.0.606

**Comment by dhermanns** [comment]
Thx Tom! Did you get these values when your App is in background? I tested
the app badge with mmol and it looks ok. At least when the app is in
foreground.

Tom Scott <notifications@github.com> schrieb am Sa. 3. Okt. 2020 um 22:44:

**Comment by dhermanns** [comment]
Yes - looks like this could be mainly the same cause as #77 . I tried to fix this with the upcoming Testflight build.

**Comment by dhermanns** [comment]
This should bei fixed now with V3.1.0. Its available in the App Store now! Have fun...
