### ISSUE TITLE
Nightguard on Apple Watch 2015

### ISSUE THREAD

**Issue by francy08** [nightscout/nightguard#124]
Nightguard 3.1.0 app disappears on my Apple Watch series 0 (2015), why? This would be the last version that support it!

**Comment by dhermanns** [comment]
Hi!

What is your Version of WatchOS installed?

**Comment by dhermanns** [comment]
Ah ok - I missed that. The series 1 and 2 got watchos 6. Series 0 hasn't been updated since Watchos4. So right now, Series 0 can't be supported by Version V3.1.0. I will see how much is missing from WatchOS4 to 6.

If it's possible, I will try to build a last Version V3.1.1 for the Series 0.

**Comment by francy08** [comment]
How can I do this downgrade?

**Comment by dhermanns** [comment]
You won‘t have to do anything. I will see what I can do...

>

**Comment by dhermanns** [comment]
I stripped V3.1.1 down to just WatchOS4. So you should try the upcoming TestFlight version:
https://testflight.apple.com/join/Ub8WcpcE

Let me know if that works for your watch.

**Comment by dhermanns** [comment]
Apple was fast - V3.1.1 is released. Hope that helped...

**Comment by francy08** [comment]
Thank you for very fast answer! Nightguard is back on my watch, but crashes after few seconds.

**Comment by dhermanns** [comment]
Sorry - that is much harder then. Because I don’t have Series 0 anymore.
You could send me your Uri to see if its a general problem with your
backend.

Or you could try to reenter your Uri. Or try to reinstall the app.

**Comment by francy08** [comment]
thank you very much for your efforts in solving this problem, I will try to reinstall the app, I hope to solve.  anyway thanks again for taking the time to deal with my problem.
