### ISSUE TITLE
Blood sugar level is only in mol and not in mg/dl

### ISSUE THREAD

**Issue by Bengah** [nightscout/nightguard#126]
There is no option to change the type of value for the blood sugar level anymore. So please integrate the mg/dl option again. Thank you

**Comment by dhermanns** [comment]
Hi!

Are you using an old version?
This is the option: Should be still included:

**Comment by Bengah** [comment]
No. iOS Update from last night. Where is the option? In nightspot the level is displayed in mg

**Comment by dhermanns** [comment]
Yes - this option is in that version still under the preferences tab.

**Comment by Bengah** [comment]
Oh ... sorry i was blind...thank you, it works. Thanks for your Support and for managing this app!!!

**Comment by dhermanns** [comment]
Welcome 😉 But normally you should keep these settings to „automatically detection“. If you have to overwrite your backend settings, you have the probably wrong on your Nightscout Backend.
