### ISSUE TITLE
Dexcom Raw Data still relevant?

### ISSUE THREAD

**Issue by dhermanns** [nightscout/nightguard#127]
@florianpreknya: We are using the G6 now. But we are not using the raw data feature.
Is this still working/relevant for you?

Right now I'm rewriting the watch part in swiftui. And I'm wondering whether I still have to port this visualization.
Furthermore it's hard for me to test since I don't get these values in my setup.

**Comment by florianpreknya** [comment]
Yes, I think we should remove the raw data, G4/G5 are not very common these days anymore.
I'm really happy that the project is so active. Yes, SwiftUI is the way to go! 👍

**Comment by dhermanns** [comment]
Ok - I will kick this out then ;-) .
