### ISSUE TITLE
Bg change

### ISSUE THREAD

**Issue by Samhagberth** [nightscout/nightguard#128]
Nightguard shows 0,1 mmol change when the actual change is 1 mmol. both up and down. Other values seems  to be shown correctly.

**Comment by dhermanns** [comment]
Hi!

What is your version?

Samhagberth <notifications@github.com> schrieb am So. 1. Nov. 2020 um 21:22:

**Comment by Samhagberth** [comment]
313620


/Sam

**Comment by dhermanns** [comment]
There has been a lot of work done till the last version. Did you try the
last TestFlight?

https://testflight.apple.com/join/Ub8WcpcE

Samhagberth <notifications@github.com> schrieb am So. 1. Nov. 2020 um 21:30:

**Comment by Samhagberth** [comment]
I will try it now :)


/ Sam
Skickat från min iPhone
