### ISSUE TITLE
Feature request - more battery percentages

### ISSUE THREAD

**Issue by nickarmstrong84** [nightscout/nightguard#13]
Hi again,

Feature request this time. I like that I can see what looks like my Minimed Bluetooth upload device battery percentage, but I have 4 devices that I'm tracking batteries for at all times. Phone, watch, pump and minimed connect uploader. If nothing else, because the full view app on the watch does not show the watch battery, adding that maybe on the top left would be very helpful. If you had room for other battery reading, that could be useful too. Watch is likely the most useful for me if you had room to add one. Thanks for taking the time to read these. Keep up the great work.

**Comment by dhermanns** [comment]
Thanks for your feedback. But I don't see enough space to meaningfully
display so many batterie values. So I decided to display the in my eyes
most important one.

But maybe someone can provide a pull request for this and prove me wrong ;-)

cu,
Dirk
nickarmstrong84 <notifications@github.com> schrieb am So. 21. Mai 2017 um
06:40:

**Comment by nickarmstrong84** [comment]
Hi Dirk,
If I had experience with writing apps I'd take a look at your code and see what I can come up with, but I don't. I'll leave this open for a while and see if anyone with the right knowledge comes by. If nothing else, having the watch battery level in the upper left hand corner on the same line as the current time would be great. Thanks.

**Comment by dhermanns** [comment]
Technically - this should be easy to do. My problem is, that there will not be enough space on the watch to display both battery values.

I would have to display something like:
"100/100%"

The first will be the battery level of the watch, the second the level of the uploader.
I think that even that would fit. And if that would fit, the users would have no idea what value is for which battery. So for good usability you would need something like:
"W100/U100%"
U would be the Uploader. W would be the Watch.

**Comment by nickarmstrong84** [comment]
I think that would be great. You're the design guy, so I'll leave it up to you. Thanks for the quick replies to these threads :-)

**Comment by dhermanns** [comment]
Sorry - but I don't think we have space on the watch right now. The new IOB feature made it even worse. So I will have to close this for now.
