### ISSUE TITLE
Apple Watch 5 not Displaying

### ISSUE THREAD

**Issue by pemby143** [nightscout/nightguard#131]
I have an Apple Watch Series 5 and it does not display the graph in complications it only say s Nightguard or the logo until I go into the complication

**Comment by dhermanns** [comment]
Hi! What is your version?

**Comment by pemby143** [comment]
Off Nightscout or app

**Comment by dhermanns** [comment]
I think nightguard version should be interesting.

**Comment by pemby143** [comment]
3.1.3

**Comment by dhermanns** [comment]
Then you should try the TestFlight first:

https://testflight.apple.com/join/Ub8WcpcE

**Comment by pemby143** [comment]
Thanks for the update but still no display on complications

**Comment by pemby143** [comment]
![F1841519-DC84-430B-ADA9-3A3ABBE69522](https://user-images.githubusercontent.com/46693878/99984255-bb962d80-2da4-11eb-8a91-7cfab2b39519.jpeg)

**Comment by dhermanns** [comment]
Looks like the corner complication is working and just the big complication
has this issue?

pemby143 <notifications@github.com> schrieb am Mo. 23. Nov. 2020 um 16:58:

**Comment by pemby143** [comment]
The one in the corner is Tomato

**Comment by dhermanns** [comment]
Did you try other nightguard complications?

pemby143 <notifications@github.com> schrieb am Di. 24. Nov. 2020 um 08:13:

**Comment by pemby143** [comment]
I didn’t know there were others

**Comment by dhermanns** [comment]
Depending where you place them, they will be displayed with more or less
information. So you should be able to place nightguard where Tomato is now.
May it‘s s problem just for the big nightguard complication...

pemby143 <notifications@github.com> schrieb am Di. 24. Nov. 2020 um 09:19:

**Comment by pemby143** [comment]
![59D01BCD-6E60-435D-B948-0FF9E28A0BE8](https://user-images.githubusercontent.com/46693878/100068069-ee850380-2e2e-11eb-9a9c-961a8fecbea6.jpeg)
Still not working

**Comment by dhermanns** [comment]
Sorry can‘t reproduce this here:

What is your watch version? What nightguard version is displayed on your
watch?

pemby143 <notifications@github.com> schrieb am Di. 24. Nov. 2020 um 09:28:

**Comment by pemby143** [comment]
3.2.0.653

**Comment by dhermanns** [comment]
Do you have a screenshot from nightguard on your watch? Does it open when you click on your complication?

**Comment by pemby143** [comment]
Yes it does. But does it not show a open app so I can see it at a glance rather than opening it up

**Comment by dhermanns** [comment]
Sorry - then I don‘t have any more Ideas. Not reproducible here.
