### ISSUE TITLE
Ios 14.2 no graphe on iphone

### ISSUE THREAD

**Issue by Cheun1** [nightscout/nightguard#132]
Ios 14.2 no graphe on iphone.
![image](https://user-images.githubusercontent.com/41595891/100795876-099fd680-3420-11eb-92e4-8116b4a79834.png)

**Comment by dhermanns** [comment]
Hi! Tell me something more about your nightscout and nightguard version.

**Comment by Cheun1** [comment]
nightguard 3.2.0.655
nightscout 14.0.6

**Comment by Cheun1** [comment]
nightscout 14.0.6 sorry

**Comment by dhermanns** [comment]
That looks fine. Let me guess: you are using mmol? You could leave me your
URI here:

issue132.hermanns@spamgourmet.com

and I will try to reproduce this...

**Comment by Cheun1** [comment]
Is not for me , i help a people , this will happen after the update of nightguard today.If i can have his url i will send it to you maybe tomorrow. (if she want )

**Comment by dhermanns** [comment]
Otherwise you could try to reinstall and/or reenter your URI.

**Comment by Cheun1** [comment]
she have do that and restart iphone but no issue , wait and see tomorrow

**Comment by Cheun1** [comment]
i try testflight with her tomorrow , and i keep you informed thank you very much

**Comment by dhermanns** [comment]
You are on the latest version - so that won‘t help.

Cheun1 <notifications@github.com> schrieb am Di. 1. Dez. 2020 um 23:04:

**Comment by Cheun1** [comment]
I have found the problem ***lol**
![image](https://user-images.githubusercontent.com/41595891/100879977-72cd2b80-34ac-11eb-8ed5-06c863772aa4.png)

**Comment by dhermanns** [comment]
Ah - ok. That sounds like you need an update for your backend ;-)

Cheun1 <notifications@github.com> schrieb am Mi. 2. Dez. 2020 um 14:42:

**Comment by Cheun1** [comment]
thank you for all , you can close this.
