### ISSUE TITLE
Nightguard doesn't show the graph

### ISSUE THREAD

**Issue by aleksdia** [nightscout/nightguard#133]
After upgrading to version 3.2.0. my Nightguard doesn't show the graph. 

![IMG_4F79AAFE4F5C-1](https://user-images.githubusercontent.com/74585086/100891647-74badd00-34f4-11eb-978f-02893b93960a.jpeg)
![IMG_2331](https://user-images.githubusercontent.com/74585086/100892387-3eca2880-34f5-11eb-93c7-c6a832aab29d.jpg)

**Comment by dhermanns** [comment]
Hi!

Have a look at #132. Looks like you have a pretty old nightscout version
running.

So you should update to a recent Nightscout  version. This is highly
recommended- not at least for security reasons.

aleksdia <notifications@github.com> schrieb am Mi. 2. Dez. 2020 um 16:22:

**Comment by laurapmlima** [comment]
Guys, I donwloaded latest version too and i'm having the same trouble. I have an Iphone 11 and an Apple watch series 5

**Comment by dhermanns** [comment]
Check your Nightscout Version.

laurapmlima <notifications@github.com> schrieb am Mi. 2. Dez. 2020 um 18:30:

**Comment by laurapmlima** [comment]
V 3.2.0.655
![Nightguard](https://user-images.githubusercontent.com/47230733/100912853-c4c38080-34af-11eb-8eb0-54d726061a15.jpg)

**Comment by dhermanns** [comment]
Nightscout not Nightguard Version seems to cause this. Have a look at #132

laurapmlima <notifications@github.com> schrieb am Mi. 2. Dez. 2020 um 19:05:

**Comment by laurapmlima** [comment]
I did the update, my Nightscout informes "repo is up to date", however the version remains the same: 0.10.3. I'm trying to get help wtih them, but do you know how I can fix this?

**Comment by aleksdia** [comment]
I've updated my Nightscout to version 14.0.7. The problem with the graph has gone. Thank you.

**Comment by dhermanns** [comment]
Great, thanks for letting me know.

aleksdia <notifications@github.com> schrieb am Do. 3. Dez. 2020 um 01:53:

**Comment by laurapmlima** [comment]
A fixed the problem with Nightscout uptade and now everything is normal. I believe you can close this issue. Thaks for the support!

**Comment by dhermanns** [comment]
Great to hear that. Welcome!

**Comment by Krasnoglazaya** [comment]
Hello!  where should i update the Nightscout program?  I updated Nightguard and the graph disappeared, there are no other programs on my Iphone.  what should I do?

**Comment by dhermanns** [comment]
Nightscout is your software the you installed typically on azure or heroku.
You are referencing it with the URL you are entering in Nightguard.

The “new” Api I’m using is V2 which is actually pretty old. I’m wondering
why quite many people experiencing this error.

So someone who has this can leave me the URI here:
issue133.hermanns@spamgourmet.com

I will check whats going on with these old versions. Maybe there is another
workaround than updating...

**Comment by Krasnoglazaya** [comment]
Maybe I should do that? 
![CC2EBBCF-254F-4605-80C6-EF7F0A8DAAFC](https://user-images.githubusercontent.com/56973388/101235877-549a4200-36dd-11eb-966d-06c11ef3fd25.jpeg)

**Comment by dhermanns** [comment]
No - do that:
http://nightscout.github.io/update/update/

But others no that one better. I’m not using
Nightscout in the cloud myself.

Krasnoglazaya <notifications@github.com> schrieb am Sa. 5. Dez. 2020 um
07:36:

**Comment by dhermanns** [comment]
If someone still have this - leave me your URI here:
issue133.hermanns@spamgourmet.com

Maybe I can improve this. The V2 API is existing for many nightscout versions. So I think that alone can't be the reason.

**Comment by SzilagyiAron** [comment]
Thanks dhermanns for this update description. Problem solved, graph is again on watch!

**Comment by dhermanns** [comment]
Thanks for your feedback!

**Comment by cchance14181** [comment]
Hi,
I would also very much appreciate some help. 
I’m also having these issues On the watch app since the update of nightguard (no graph, crown scroll & refresh Boxes, 2 blank screens, url & updates info)
 
Using series 3 watch - 6.2.8
XR - 13.6.1
Nightscout - 14.0.7
Nightguard - V3.2.0.655

I’ve uninstalled and reinstalled nightguard on phone and watch and re-entered api into the app ... still no graph ... what am I missing? 
also the bg keeps showing 0.5, 0.3 etc on the complication on watchface... after I’ve had a split second of panic, when I open the watch app it shows actual bg. 
TIA

**Comment by dhermanns** [comment]
You can send me your URi and I will have a look:

graph.hermanns@spamgourmet.com

**Comment by dhermanns** [comment]
For those with old Nightscout backends <= 0.11. 

I switched back to the old v1 API and with a bit of luck your graphs should be once more fine now:

https://testflight.apple.com/join/Ub8WcpcE

But remember to update your backends soon. It could be dangerous to stay on old versions.

**Comment by cchance14181** [comment]
Thanks again for all your help.
I will try and figure this out tomorrow. I’m not the most tech minded person. 🙈
Kind Regards
Carrie

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dhermanns** [comment]
The version is in the app store now. Let me know if there are still problems...

**Comment by cchance14181** [comment]
Hi, I couldn’t get it to work at all with any version, it was still the same. No graph and the changing of bgs was worse... it kept showing my son as being 0.2, 0.3, 0.5 etc until I refreshed the data... for now I have removed the app and have reinstalled Sugarmate... it’s not as amazing as nightguard but will have to do!
I actually have an Apple Watch series 6 for my 40th birthday in a couple of weeks. But I need to update Xcode and loop iOS etc first so will try again once have this all sorted. Need to find some extra space on my Mac first to be able to do Xcode! Nothings ever simple! Lol!
Thank you again for all your help,
Happy New Year 🥳
Carrie

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
