### ISSUE TITLE
Missing graph on Series 3 watch (38 mm)?

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/nightguard#134]
Hi, I see there are some bigger changes going on with Nightguard. I am not sure what it is supposed to look like on the watch at the moment, but it seems it doesn't display correctly on my Series 3 38 mm. There is no graph on the first screen, and then there are some things I can't quite understand, including two black screens.

It looks the same with the current Testflight and Appstore versions, as of today. 

Perhaps these screenshots can be useful? 

![-5122201120777505707](https://user-images.githubusercontent.com/63544115/100924092-72e71e80-34e0-11eb-809d-37087242d978.jpg)

![-6273886267355182594](https://user-images.githubusercontent.com/63544115/100924095-737fb500-34e0-11eb-8505-6969ff5e7992.jpg)

![-5082204957275219097](https://user-images.githubusercontent.com/63544115/100924085-724e8800-34e0-11eb-8369-0faf3fa79631.jpg)

![-4535508252361213556](https://user-images.githubusercontent.com/63544115/100924089-72e71e80-34e0-11eb-97ac-7f94819bf7b4.jpg)

![-8226561107810756666](https://user-images.githubusercontent.com/63544115/100924097-737fb500-34e0-11eb-95d7-ec0d045d42e9.jpg)

**Comment by dhermanns** [comment]
I dont have a 38mm watch anymore.
I checked it in the simulator.

Will double check this...

bjornoleh <notifications@github.com> schrieb am Mi. 2. Dez. 2020 um 20:58:

**Comment by dhermanns** [comment]
That's how it should look like in my simulator:

![Simulator Screen Shot - 38mm - 2020-12-02 at 22 02 07](https://user-images.githubusercontent.com/3207317/100931099-58b23e00-34ea-11eb-8fd2-b9aefea84cab.png)
![Simulator Screen Shot - 38mm - 2020-12-02 at 22 02 17](https://user-images.githubusercontent.com/3207317/100931105-5bad2e80-34ea-11eb-880a-594246635def.png)
![Simulator Screen Shot - 38mm - 2020-12-02 at 22 02 21](https://user-images.githubusercontent.com/3207317/100931108-5cde5b80-34ea-11eb-9e2e-ce173577a41f.png)
![Simulator Screen Shot - 38mm - 2020-12-02 at 22 02 26](https://user-images.githubusercontent.com/3207317/100931113-5ea81f00-34ea-11eb-9c4b-6f96d4a6e0fd.png)

You can leave me your URI:
issue134.hermanns@spamgourmet.com

Maybe it's related to your backend like the other issues we have right now.

**Comment by bjornoleh** [comment]
Ok, you have mail. The site is at nearly current Dev  14.0.8 (actually the crowdin_incoming branch from a few days ago).

**Comment by dhermanns** [comment]
Tried with your backend and a 38mm simulator. Looks fine too.
Did you increase the visualization of fonts or ui elements on your phone?
Don't know if that has an impact on the watch...

**Comment by bjornoleh** [comment]
Ok, I am checking the versions now. Not latest versions, but probably should not matter?

iOS 13.7
WatchOS 6.2.8

No changers to the screen and text size settings.

Anything else I could check?

**Comment by dhermanns** [comment]
Oh - you are a major version behind.
So you should definitely update.

>

**Comment by bjornoleh** [comment]
Yes I know, but Loop and other stuff is working fine, so I didn't quite expect it to make too much of a difference. And there were some issues initially with iOS 14 and Xcode, so I have been putting it off for some time now. I will report back when we have updated, I guess it is about time.

**Comment by dhermanns** [comment]
Yes - maybe you are right.
But chances are 50:50 and I have absolutely
no idea how to tackle this down if the
simulator can‘t reproduce your error :-/

**Comment by bjornoleh** [comment]
I will probably do the updating soon, but it should also be possible to install Xcode simulators for older versions of iOS and probably watchOS too. I haven't really looked into this though.

https://developer.apple.com/forums/thread/110911

**Comment by dhermanns** [comment]
Let me know if this is still a problem after updating.

**Comment by bjornoleh** [comment]
@dhermanns Hi, Nightguard is displayed correctly  on the watch after updating to latest iOS and watchOS.

The IOB value is displayed a little varying, see screenshots, perhaps for this size only? 

![IMG_02671](https://user-images.githubusercontent.com/63544115/103560840-ccb07f00-4eb8-11eb-89d1-c0904463555f.jpg)
![IMG_02661](https://user-images.githubusercontent.com/63544115/103560843-cd491580-4eb8-11eb-9a21-381ce43c201f.jpg)

**Comment by dhermanns** [comment]
Yes - looks like. On the 38mm watch there is no more gap between last readings and the COB. So it shrinks the label size.
