### ISSUE TITLE
Reservoir level immer 0

### ISSUE THREAD

**Issue by stephanpaulsgit** [nightscout/nightguard#135]
Hallo,

das verbleibende Insulin im Reservoir wird bei mir immer mit 0 U angezeigt, obwohl in Nightscout das korrekte Level zu sehen ist. Habe die neueste App-Version 3.2.0.655 installiert, Nightscout ist auf Version 14.0.7.

Benutze den 600 Series Uploader mit der Medtronic 640G, falls das noch wichtig ist.

Habe wie im App Store von Ihnen vorgeschlagen meine URI des Nightscout backends per Mail geschickt.

Vielen Dank und Grüße

**Comment by dhermanns** [comment]
Hi Stephan,

we should switch to english here if possible. Thanks for your URI. 
Your Reservoir Units have decimal values. This caused some trouble in nightguard.

I fixed this. You can check a beta version in a few hours here:
https://testflight.apple.com/join/Ub8WcpcE

**Comment by stephanpaulsgit** [comment]
Hi, thank you! After installing the beta version it works fine now.

**Comment by dhermanns** [comment]
Great to hear that!
