### ISSUE TITLE
Units only dispaying in mmol on Apple watch series 4

### ISSUE THREAD

**Issue by melanieklee** [nightscout/nightguard#137]
Hi,

I am running the Nightguard app in newest version on my iPhone. I am using the settings from my backend app (mg/dl) to display the units on screen.
This works fine on the iPhone itself but when installing the app to my watch (Model A1978, version 7.1) the values are shown in mmol.

I tried uninstalling, setting the units manually in the app and reinstalling to the watch but without effect.

Kind regards,
Clemens

**Comment by dhermanns** [comment]
Hi Melanie!

Hm - hard to say. Maybe the synchronization to your watch is broken. You could leave me your Uri and I can see if its an backend related problem:

137.hermanns@spamgourmet.com

Or you could try to reenter your URI on the app and look whether it's synced correctly to your watch.

**Comment by melanieklee** [comment]
Hi,

I reentered the URI - https://watchmelanie.herokuapp.com - again. It resynched fine. The values are correct per se - the mmol value on the watch is equivalent to the mg/dl value on the phone. 

I have also deleted and reinstalled the app on the phone. But sadly that also did not help.

If you have any idea?

Thanks!

**Comment by dhermanns** [comment]
Interesting: It synced fine for me:

![image](https://user-images.githubusercontent.com/3207317/102548567-25130e80-40bb-11eb-954f-35070cd6c019.png)

**Comment by melanieklee** [comment]
Yes...I removed and readded the watch part several times. I downloaded the English and not the German Version. Would that make any difference? Maybe some hidden region setting?

**Comment by dhermanns** [comment]
You should have Version 3.2.0

melanieklee <notifications@github.com> schrieb am Do. 17. Dez. 2020 um
23:01:

**Comment by melanieklee** [comment]
I am using Nightguard 3.2.0.655

**Comment by dhermanns** [comment]
Since it's the same code on the watch and the app, I would guess that your configured units are not synced to the watch.

So I'm preparing a version with this new feature on the watch: If you enter the nightscout URI directly on your watch, it now determines the configured units directly from your nightscout backend.

So this should work even if your synchronization has a problem.
Please try the upcoming TestFlight version.

1) Make sure that units are *not* manually set on your nightguard app.
2) Reenter your nightscout URI directly on your watch.
3) Cross fingers ;-)

**Comment by melanieklee** [comment]
Hey, not sure if you got the comments in the thread…but it works since a few days (not sure why though).  From: dhermannsSent: Wednesday, 23 December 2020 21:48To: nightscout/nightguardCc: melanieklee; AuthorSubject: Re: [nightscout/nightguard] Units only dispaying in mmol on Apple watch series 4 (#137) Since it's the same code on the watch and the app, I would guess that your configured units are not synced to the watch.So I'm preparing a version with this new feature on the watch: If you enter the nightscout URI directly on your watch, it now determines the configured units directly from your nightscout backend.So this should work even if your synchronization has a problem.Please try the upcoming TestFlight version.Make sure that units are not manually set on your nightguard app.Reenter your nightscout URI directly on your watch.Cross fingers ;-)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dhermanns** [comment]
Ah - great to hear that. Fine!
