### ISSUE TITLE
Wider range for temp targets

### ISSUE THREAD

**Issue by JohnKitching** [nightscout/nightguard#138]
Hi,
Would it be possible to have a wider range for temp targets?
For activity I like to set mine higher than the 6.7mmol max. 
Apologies if I've missed a setting somewhere.

**Comment by dhermanns** [comment]
Hi John!

Sure - what ranges do you like to have?

**Comment by JohnKitching** [comment]
You're a star!
I go for 8.0 but I'd guess others go a bit higher (I'm not particularly energetic!)

**Comment by dhermanns** [comment]
Than I will go for 8.0 and 8.9.

**Comment by JohnKitching** [comment]
That's brilliant. Thank you. 
While I have your attention ... any chance of finer resolution on carbs? 20 or 30 is quite a bit step. 
Personally, I'd go 1g steps 1g to 100g as it's easy to scroll but maybe some people wouldn't like that?

**Comment by dhermanns** [comment]
Personally I'm not very good in estimating the carbs so exactly. But estimation to maybe 5g is possible. 
I will add 5g steps.

**Comment by JohnKitching** [comment]
Thanks very much. 
Very impressed with the recently added functionality by the way. 
Great work!

**Comment by dhermanns** [comment]
Happy to be helpful :) . Here you go:
https://testflight.apple.com/join/Ub8WcpcE

It will be normally available for testflight in a couple of hours...

**Comment by JohnKitching** [comment]
I can't seem to select 8 as a target on my watch. I can do it on my phone but on my watch it always shows 7.215 as the target.

**Comment by dhermanns** [comment]
Yes - you can set different targets only on the app now. Not on the watch since there is not much UI space available.

**Comment by JohnKitching** [comment]
Ah ok. Thanks.

**Comment by JohnKitching** [comment]
Would it be possible to have the watch use the value last entered on the phone?
That way you could enter the temp target you want on the phone but then have it available to set on the watch after the first time?
Could that be done without creating a problem with the UI space?

**Comment by dhermanns** [comment]
Yes - I'm implementing a default temp target right now. That will be the last value selected on the iPhone. It will be synched to the watch. Hava a look at #140.

**Comment by JohnKitching** [comment]
That looks ideal thank you. 
Sorry I missed it. 
Great work!

**Comment by dhermanns** [comment]
No problem- welcome!

**Comment by dhermanns** [comment]
It will be available with Build 664:

https://testflight.apple.com/join/Ub8WcpcE
