### ISSUE TITLE
Complication randomly vibrates the watch

### ISSUE THREAD

**Issue by miguelpruivo** [nightscout/nightguard#139]
For some reason when I have the complication on my series 6, it randomly vibrates the watch silently (even with DND on while sleeping) and there is no notification at all. It seems somehow that it vibrates every time a new event comes in (by looking at the time in the logs) but I’m not sure. This is very inconvenient because I think there’s a notification when there’s not.

**Comment by dhermanns** [comment]
Hi Miguel!

Did you try to snooze the alarms on the watch? Did that pause the vibrations?

**Comment by miguelpruivo** [comment]
@dhermanns the thing is, why is it vibrating without any notification? I mean, it’s just vibrating occasionally I don’t even know what is trying to “notificate”. The thing that I know for sure, is that if I remove the complication, it stops. Is this an expected behavior?

**Comment by dhermanns** [comment]
The vibration is what is done if I notice an alarm situation. And that is done during a background update. The possibility that an app is allowed to do background updates is increased by apple, if a complication of that app is active.

The notifications are pushed by the ios app. So it can happen what you described: the watch app noticed an alarm situation and vibrates. And that can be without a notification from the iOS part.

So right now you would have to snooze the alarms if you don't want to get any vibrations. You can even completely disable alarms.

**Comment by miguelpruivo** [comment]
@dhermanns so that means that if it’s vibrating it’s because I’ve either high/low or some other alarm? 

Also, complication updates are very slow unless I tap on it and manually refresh it. What is the average time of each refresh?

**Comment by dhermanns** [comment]
Yes. That should be the case. Otherwise we have another problem here ;-) .

Apple doesn't assure any number of background updates. It will increase the more often you use the app.
And things like adding the complication increases it, too. 

What I experienced is about up to 4 updates an hour. But in times you won't use the app, it will be maybe no update at all.

**Comment by JohnKitching** [comment]
I noticed the same thing. For me I think it was missed readings. I turned it off on the phone and it went away.

**Comment by dhermanns** [comment]
Good point.

**Comment by miguelpruivo** [comment]
> I noticed the same thing. For me I think it was missed readings. I turned it off on the phone and it went away.

ok, this may be the case since I remember opening it and having the message about missing readings.

Thank you for the input.

Closing.
