### ISSUE TITLE
Invalid JSON

### ISSUE THREAD

**Issue by glucosadri** [nightscout/nightguard#141]
Hello, I´ve migrated fron azure to heroku and now when I try to run nightguard with the new URL appears:
"Invalid JSON received from Pebble Watch API, missing bgs array. Check Nightscout configuration.
What can I do?

Thanks

**Comment by dhermanns** [comment]
Hi! You can send me your URI to:

issue141.hermanns@spamgourmet.com

And I will have a look what's going on...

**Comment by glucosadri** [comment]
just sent,
Thanks

**Comment by dhermanns** [comment]
Ah ok - the error message was bad. I improved it in upcoming Version 3.2.2.
You secured your new installation completely and disallowed even read access to your system.

So I would guess that you didn't entered a security token in your nightscout URL.
Without it, nightguard can't read any data from your nightscout backend.

**Comment by glucosadri** [comment]
How can I input my security token in nightguard??

**Comment by dhermanns** [comment]
Have a look at the description underneath the URI in nightguard:

"E.g. 'https://nightscout?token=mytoken'."

Where mytoken is your certain security token.

**Comment by glucosadri** [comment]
Sorry,
You mean:
https://myurl?token=mytoken
I have to type "?"

**Comment by glucosadri** [comment]
Thanks now It's working.

**Comment by dhermanns** [comment]
Great!

**Comment by liongame43** [comment]
Hi, I type my url with token on Nightguard but I cant see my SAGE and care informations. Can you help me?

**Comment by dhermanns** [comment]
You should be able to set them using nightguard. If that doesn't work, you need to check the access rights of your token used in nightguard. Have a look at the Nightscout documentation how to create a token with careportal access.
