### ISSUE TITLE
Update Nightscout

### ISSUE THREAD

**Issue by erickdasilvamedeiros** [nightscout/nightguard#143]
When performing: Time to update Nightscout, it displays the error below:
There was an error
Make sure you username is typed correctly, you're logged into your github account (in these browsers)

Error: {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#compare-two-commits"}

I am logged into https://github.com/ in the same browser.

can you help me?

![image](https://user-images.githubusercontent.com/76886694/103468725-052a4e80-4d3b-11eb-8478-3450bb8361ea.png)

**Comment by dhermanns** [comment]
Hi Erik! You probably wanted to open this issue for another Nightscout component. Here is the Nightguard iOS Client. So I can't help you with the Nightscout Updater issue.
