### ISSUE TITLE
Nightguard complication not working on Apple Watch v3

### ISSUE THREAD

**Issue by ETT2010** [nightscout/nightguard#145]
Hi, I updated my iPhone 6 a month or so ago to v12.4.9 and since then my Apple Watch v3 won’t display Nightguard.  I’ve tried everything uninstalling and loading back up but it won’t open.  My Apple Watch then needed updating (v5.3.9) so I did that (hoping that was the problem) but still nothing.  It still shows as a complication on the watch and still works on my actual iPhone but when I press the app on my watch it just clicks out and doesn’t open it.  I read that 0, 1 and 2 watches no longer work but thought I’d message in case this is a simple fix I haven’t thought of yet.  Thanks

**Comment by dhermanns** [comment]
Hi! So your watch is still on WatchOS5? You will have to go to Watch OS 7 so that your Watch is able to support the latest APIs. Looks like your iPhone 6 has to be on iOS 14 for that. Not sure if this is possible. Sorry.
