### ISSUE TITLE
Temp target reading mmol

### ISSUE THREAD

**Issue by dexterbooty** [nightscout/nightguard#147]
When nightscout is set to mmol the temp target is divided by 18 e.g 5mmol target is shown as 0.3

**Comment by dhermanns** [comment]
Hi! I would think that you didn't set the Temp-Target with Nightguard, but via nightscout directly?

**Comment by dexterbooty** [comment]
Correct temp target was set in nightscout and works fine. Issue is Nightguard displays the value divided by 18 when using mmol. See attached example of a temp target = 5 
![2127D8B9-FAE9-4B9E-81F4-6D5DB6A9EBB8](https://user-images.githubusercontent.com/10778986/111122161-8a18bc00-8565-11eb-9531-c6b107f6ebf0.jpeg)
![FE4FAAA0-04D7-4258-9CDB-6B0660F70063](https://user-images.githubusercontent.com/10778986/111122166-8b49e900-8565-11eb-8cf2-4904a6a5c94a.jpeg)

**Comment by dhermanns** [comment]
Looks like androidaps stores the Temp-Targets in mmol if your backend is configured for it. I can't really test this here, since my backend is in mgdl. So I would need your feedback whether my above change helps.

**Comment by dexterbooty** [comment]
Happy to test but not actually registered as a beta tester at the moment. Or if easier happier to provide link for nightscout site I use.

**Comment by dhermanns** [comment]
This is the TestFlight:
https://testflight.apple.com/join/Ub8WcpcE

But you can send me your uri, too if you prefer:
no147.hermanns@spamgourmet.com

**Comment by dexterbooty** [comment]
Thanks still seems to be dividing by 18. Just sent you my link.

**Comment by dhermanns** [comment]
Ah - ok. I see. Thanks. Aaps stores the units in your case (not in mgdl case so I didn‘t expected that). So I can use that to do the conversion.

**Comment by dhermanns** [comment]
I have a new Testflight version. Can you have a look?
Everytime I checked your child was fine - so no Temporary Target in place ;-) .

**Comment by dexterbooty** [comment]
Works great thanks.

**Comment by dhermanns** [comment]
Excellent
