### ISSUE TITLE
MMOL vs MG

### ISSUE THREAD

**Issue by Lilac13** [nightscout/nightguard#148]
My watch is displaying mmol, I use mg.  Is there a way to change this setting?  The Nightguard app shows correct with mg.
thank you!

**Comment by dhermanns** [comment]
Hi! What watch do you use?

**Comment by Lilac13** [comment]
Hello! Apple Watch series 4

**Comment by dhermanns** [comment]
Ok - that should work. Did you already tried the latest TestFlight?

https://testflight.apple.com/join/Ub8WcpcE

**Comment by Lilac13** [comment]
I have the test flight app on my phone, yes.

**Comment by Lilac13** [comment]
Do I need to add an updated version or enter a Redeem code?

**Comment by dhermanns** [comment]
No - that version should do fine. We already had another such case but I have no idea how that could be reproduced. You can leave me your nightscout URI here issue148.hermanns@spamgourmet.com.

But last time I was not able to reproduce this. The watch gets this information from the app. So maybe your link between the app/watch is somewhat broken.

Did you already try to deinstall/reinstall the watch part only? What version do you see in the watch app?

**Comment by Lilac13** [comment]
I just uninstalled then reinstalled it.  Still showing mmol value.

**Comment by dhermanns** [comment]
Then I just can try to reproduce it with your backend...

**Comment by Lilac13** [comment]
Do you need my URL?

**Comment by dhermanns** [comment]
Yes - you can send it to me using the email above.

**Comment by dhermanns** [comment]
As expected - runs fine in mgdl for me on the watch. Did you try to manually override the unit setting on the app?
