### ISSUE TITLE
Zoom does not work on apple watch series 1

### ISSUE THREAD

**Issue by fcofernandez** [nightscout/nightguard#15]
Hi
I noticed that I can scroll back and forth in time, but the zoom does not work, is that normal?

**Comment by dhermanns** [comment]
No - after selecting Zoom from the popup you should be able to zoom.

What is your setup? What watch are you using?

**Comment by fcofernandez** [comment]
I´m running night guard 1.4.1.105 on an apple watch series 1 with OS 3.2.3

**Comment by dhermanns** [comment]
Ah ok - anyone else here with a series 1 watch? I'm running it with a series 2 and the zooming takes a lot of cpu. The first watch has a much weaker cpu. I think the series 1 has still the cpu of the first watch, has it?

Maybe its a cpu issue and someone else can with a series 1 can confirm my thoughts...

**Comment by fcofernandez** [comment]
Hi
You are right, it has to be a CPU thing. If I try to zoom in in does´t do anything and it crashes, but since you said it might be a CPU issue I tried repeatedly till i got it to move a bit and the zoom worked eventually, it might crashes 1 out of 4 attempts though but then stays in the position i wanted so in a way, its fixed and from the developer side there is nothing else you could do since its a hardware issue. 

Again, thanks for the app, it really changed my life. Since I started medtronic guardian connect CGM together with your app on the apple watch 3 months ago my A1C has gone down from 8,6 to 6,6! Its so much easier to manage

**Comment by dhermanns** [comment]
Nice to hear this great feedback - thanks!

Since the series 3 Watch seems to be ready for launch, more and more people will switch to a newer model. So this shouldn't hopefully be a big issue soon.
