### ISSUE TITLE
Allow configuring different soundURL for alarms

### ISSUE THREAD

**Issue by devonestes** [nightscout/nightguard#151]
Howdy - thanks a ton for NightGuard!

I was looking for a way to set a different audio file to play for alarms. I'm not an iOS dev,
so I may be wrong here, but it looks like this is hardcoded at compile-time [here](https://github.com/nightscout/nightguard/blob/f9d00d54a4838cdedb4903380180e2627e08b926/nightguard/AlarmSound.swift#L42).

Would it be possible to allow users to select different sounds for their alarms instead
of this default one? A nice first step would be allowing users to set a new URL to some
file that can be downloaded when set. Of course using the same UI that's provided for
selecting sounds for alarms in Clock.app or something like that would be great eventually,
but there's no need to jump right to that if that's more complicated than just users inputting
a URL.

Thanks again for the great work on this!

**Comment by dhermanns** [comment]
Looks like using the clock alarm tones isn't possible since there is no API to use them right now:

https://stackoverflow.com/questions/35863251/how-to-get-alarm-sound-list

So falling back to enter an URI could be an option.

**Comment by dhermanns** [comment]
I had some time and added the possibility to add mp3 or wav files from your iCloud account.
Please have a look at the current Testfllight:
https://testflight.apple.com/join/Ub8WcpcE

**Comment by devonestes** [comment]
Just tried it out, and it works a treat! Thanks so much!

**Comment by dhermanns** [comment]
Welcome ;-)

Devon Estes ***@***.***> schrieb am So. 6. Juni 2021 um 19:53:

**Comment by dhermanns** [comment]
@makotila : If you have some time - we have some new labels here for the Finnish translation ;-) .

**Comment by makotila** [comment]
@dhermanns Sorry for the delay, pr for translation is now opened

**Comment by dhermanns** [comment]
No problem - thx for your translation!
