### ISSUE TITLE
Carbs added via Apple Watch not working

### ISSUE THREAD

**Issue by ggirling** [nightscout/nightguard#155]
When using the dedicated AW screen to add carbs, (swipe to 4th screen, scroll to appropriate # carbs, click "Add Carbs" button, click "Accept" on screen "Do you want to add Xg of carbs") the entered amount fails to update on Nightscout and Nightguard screens.

**Comment by dhermanns** [comment]
Hi! Thanks for your feedback. Did you enter a correct security token to your Nightscout URL?

Do you get an error message when trying that on the phone?

**Comment by ggirling** [comment]
Thanks!  I’ve got a URL with the token included. I get no error message when I enter it though and the carb doesn’t appear on NS.

**Comment by dhermanns** [comment]
Did you try to enter it using the iPhone App?

**Comment by ggirling** [comment]
I just did and it’s weird: I’ve got the URL with the token entered, but I’m getting the message “You don’t have write access to nightscout.Did you enter a security token in your URL?”  I’ve tried reentering it to be sure, but I continue to get that message. 

—————
Typos happen.

**Comment by dhermanns** [comment]
Maybe your generated token has no write access to your backend?

**Comment by dhermanns** [comment]
Your token should have the careportal role:

http://www.nightscout.info/wiki/welcome/website-features/0-9-features/authentication-roles

**Comment by ggirling** [comment]
Thanks so much - that worked!

**Comment by dhermanns** [comment]
Great 👍! But you showed me that the error message on the watch is still missing. I will add that in the upcoming release.

**Comment by ggirling** [comment]
Thanks to you! Your work is very much appreciated!

—————
Typos happen.
