### ISSUE TITLE
mg/dl not shown on Apple Watch (only mol)

### ISSUE THREAD

**Issue by lijobe** [nightscout/nightguard#156]
Hi
I can only see mmol on my watch (Apple Watch 3) 
I already installed via TestFlight 
I changed from mg/dl to mmol and back in my heroku settings (no whitespaces) 
I uninstalled the app on the watch and reinstalled 
Refreshed 
No change 
What can I do?

**Comment by dhermanns** [comment]
Hi! What is your installed watchos version?

**Comment by lijobe** [comment]
Version 
7.6.1 (18u70)
Model
A1891

**Comment by dhermanns** [comment]
Ok - that's fine. Can you try to enter your Nightscout URL directly on the Apple Watch?

**Comment by lijobe** [comment]
Absolutelely GREAT 👍 
Yes 
Entered url On my watch  
https://xxx.herokuapp.com (no token) 
Works  now 
Thank you ! 

Is there also a way to edit what is shown in the complication? 
Now : time value delta 
I would not need time

**Comment by dhermanns** [comment]
No - thats not possible to be configured. Great to hear that helped. The communication to the phone seems to be sometimes a problem. Had another user who had the same effect.

**Comment by lijobe** [comment]
Thank you so much ! 
I consider this as resolved successfull

**Comment by sofonisba** [comment]
hi, i am having the same problem. All my readings (phone-xdrip, site-herokuapp, etc) are on mg but my apple watch is displaying on mmol.  How can I enter your Nightscout URL directly on the Apple Watch? (series 3)

**Comment by sofonisba** [comment]
thank you, it worked! many thanks
