### ISSUE TITLE
Watch complication

### ISSUE THREAD

**Issue by lulukuhl** [nightscout/nightguard#157]
Hi, I have been researching but I can't find anything. 
the Nightguard app is running smoothly on my new Watch SE. But I can't make it a complication. Is this possible with night guard at all? 
I can open the app and have the data, but I would love to see the data only by looking at the watch, not opening any app. 
Is there any way of doing it with nightguard or any other app?

**Comment by dhermanns** [comment]
Yes - for sure this is possible:
![](https://github.com/nightscout/nightguard/raw/master/images/watch-complication.jpg)

Did you try to select the Nightguard complication on the watch? I had a case for some time where the complications 
were not selectable in the watch app on the phone. It helped to build the watch-face directly on the watch.

We support a lot of complications. But not all. Maybe you should start with the infograph watch-face and select the Nightguard corner complication.

**Comment by lulukuhl** [comment]
Thank you! The Nightguard Icon is nowhere to be seen nor can I choose it anywhere. In the app it is not possible and also not on the watch directly. 
where do I get the infograph watch face?

**Comment by dhermanns** [comment]
This is the Watchface you see on my screenshot. Ah - that isn't on the series 3. You are right. But others should work, too. But I can't test this because I don't own a series 3. But I will try this later in emulator...

**Comment by lulukuhl** [comment]
Thank you. I have an apple watch SE. Maybe that is the issue?

**Comment by dhermanns** [comment]
I think the SE has the same limitations as the series 3. So no infograph, too.

**Comment by lulukuhl** [comment]
Ok, if you find out on which watch face it works on the SE let me know.

**Comment by dhermanns** [comment]
Just tried the meridian watch face on the se-watch in emulator. I added the complication to the middle of the face:

![Simulator Screen Shot - Apple Watch SE - 40mm - 2021-08-29 at 20 45 57](https://user-images.githubusercontent.com/3207317/131261952-0ef2731e-f0c0-44a6-acd2-86b7ddc66927.png)

**Comment by lulukuhl** [comment]
This is weird and a bit frustrating, but it does not work for me. 
Am I doing it wrong?
It should appear in this list, correct?

![IMG_2C99EFBE2356-1](https://user-images.githubusercontent.com/45488316/131262216-2fecba7c-24ce-4bd6-920c-29160cc344a1.jpeg)
![IMG_3BF1C4DD927E-1](https://user-images.githubusercontent.com/45488316/131262221-3b16b2fa-d04f-4536-adbe-907bcfcded38.jpeg)
![IMG_D44455AA47D6-1](https://user-images.githubusercontent.com/45488316/131262222-e22af054-5f0e-4283-8ef4-e23e3786b731.jpeg)

**Comment by lulukuhl** [comment]
Youtube music is the only other app I installed on the Apple Watch and this does appear in the list.

**Comment by dhermanns** [comment]
I guess this is the same on the watch for this face? Then you could only check to have your iOS and watchOS on the latest version. Are you on iOS 14, watchOS 7?

If that's the case you could try to just deinstall/reinstall the watch part of Nightguard.

**Comment by lulukuhl** [comment]
I have no idea what happened over night, either there was an update or night guard just settled in... but now suddenly it appears. Although I don't understand it, I am happy that it works. Thank you very much for the support!

**Comment by dhermanns** [comment]
Very strange - thx for your feedback. Happy that its up and running now ;-)
