### ISSUE TITLE
Finnish Translation for the new Duration-Tab

### ISSUE THREAD

**Issue by dhermanns** [nightscout/nightguard#158]
Hi @makotila!

Could you have a look at the new labels?
I added a new Duration Tab to set the Change Dates directly from nightguard. 
You could have a look at the snapshot folder. The Screenshots can be localized, too.

cu,
Dirk

**Comment by dhermanns** [comment]
Have a look at keyword and title files here:
https://github.com/nightscout/nightguard/tree/master/fastlane/screenshots/fi

**Comment by makotila** [comment]
There is now open PR for Finnish translation

**Comment by dhermanns** [comment]
Thanks - merged that
