### ISSUE TITLE
No watch app

### ISSUE THREAD

**Issue by JohnKitching** [nightscout/nightguard#159]
Since the last update on TestFlight (3.6.0) NightGuard isn’t appearing on my watch or showing as an available watch app.

**Comment by dhermanns** [comment]
Hi John!

Are you on watchos 8?

This is actually needed for the new features.

John Kitching ***@***.***> schrieb am Do. 23. Sept. 2021 um
21:35:

**Comment by JohnKitching** [comment]
Ah ok, sorry, didn't know that. 
I'll do it and let you know.

**Comment by dhermanns** [comment]
Great

John Kitching ***@***.***> schrieb am Do. 23. Sept. 2021 um
21:41:

**Comment by JohnKitching** [comment]
watchOS 8 installed, 3.6.0 installed again, all working fine thank you.

**Comment by dhermanns** [comment]
Good to hear - thanks for your feedback!

John Kitching ***@***.***> schrieb am Fr. 24. Sept. 2021 um
00:21:
