### ISSUE TITLE
Has anyone been able to set up Pushover to send notifications?

### ISSUE THREAD

**Issue by fcofernandez** [nightscout/nightguard#16]
I have been trying to set it up but it´s not as straighforward as I hoped. 
If so, would you please share a quick tutorial on how to make it work with night guard/ night scout ?

**Comment by dhermanns** [comment]
You can't. Nightguard does not support pushover. But I think you would like to configure Pushover for your nightscout Backend. I already had that up and running.

Maybe this is helpful:
http://www.nightscout.info/wiki/labs/pushover

**Comment by fcofernandez** [comment]
Hi
Thanks for the tutorial link, that worked well and now I receive the notifications. 
Thanks a lot!

**Comment by dhermanns** [comment]
Great - the nightscout configuration is not my main part, but nice that I could help ;-)
