### ISSUE TITLE
BGs over 9.9 mmol not shown in complication

### ISSUE THREAD

**Issue by JohnKitching** [nightscout/nightguard#160]
3.6.0
watchOS 8
![image](https://user-images.githubusercontent.com/48366213/134673631-24638106-466c-4dbf-bda9-b05dd5df7666.png)

**Comment by dhermanns** [comment]
Yes - thanks for your feedback. Missed that one.

**Comment by dhermanns** [comment]
Look like a bug in watchOS 8. Before it was displaying fine and I have no way to shrink the visualization. As a workaround I try to round the mmol value and remove the decimals. Better than nothing ;-). Will be available as a TestFlight soon...

**Comment by JohnKitching** [comment]
Sounds like a plan thank you.

**Comment by JohnKitching** [comment]
Looks good thank you. ![image](https://user-images.githubusercontent.com/48366213/134983400-58a639a3-5fe6-4932-8013-90239d8435ed.png)

**Comment by dhermanns** [comment]
Good to hear - thanks for testing!

**Comment by JohnKitching** [comment]
But not always (10.3)
![image](https://user-images.githubusercontent.com/48366213/135132459-eeb93a37-bba0-40ec-a11b-7b9f670f2901.png)

**Comment by dhermanns** [comment]
Latest Testflight should (hopefully) now really display a rounded "10" in that case.
