### ISSUE TITLE
Update 3.6.1

### ISSUE THREAD

**Issue by wathman105** [nightscout/nightguard#166]
Hi. 

Since updating to 3.6.1 nights out has stopped working. 

Error attached. 

Is this a fault or do I need to change settings. Checked everything and it seems ok. 
![1A35EFCF-C005-4FFF-BE99-69A15389CAC4](https://user-images.githubusercontent.com/53540906/138056181-47fcb0dc-8fb3-402f-915d-9abc368b8137.png)

**Comment by dhermanns** [comment]
What NS Version are you using?

You could leave me your URL here:

***@***.***



wathman105 ***@***.***> schrieb am Mi. 20. Okt. 2021 um 10:24:
