### ISSUE TITLE
Invalid JSON received from API V2 Properties, missing bgs array

### ISSUE THREAD

**Issue by AlexanderShumskiy** [nightscout/nightguard#169]
Nightguard ver. 3.6.2.752 (iOS)
Nightscout backend ver. 14.2.2

1. After updating the application to version 3.6.2, I had everything ok for a while. But after the readings from the sensor were transmitted to the Nightscout website - the error "Invalid JSON..." appeared again in the application - see the screenshot.

2. After updating the application to version 3.6.2, changes (delta) are no longer displayed - with any change in the application, "+-0" or "+0" is displayed.

![IMAGE 2021-10-21 16:54:54](https://user-images.githubusercontent.com/59305516/138292332-2f75c095-1d5b-47fa-a86d-717cfcaab958.jpg)

**Comment by jfigueroa69** [comment]
Hi I am having problems getting Gluroo to work with nights out. Getting error 
Invalid JSON received from API V2 Properties, missing bgs array. 
used the following: https://14cf.ns.gluroo.com/","apiSecret":"14cfec46-82a9-4f09-91f0-19f1982761c9
![IMG_8660](https://github.com/nightscout/nightguard/assets/161789889/6ea0f81a-5049-46dc-9d80-8b7f881be0e5)
Please assist me so I can get this to work on my Apple Watch as well

**Comment by dhermanns** [comment]
Hi! What URI did you enter in Nightguard? It should look like:

https://xxxx.ns.gluroo.com:39893/api/v1/entries?token=14cfec46-xxxx-xxxxx-xxxxx

And the Port 39893 would be typically individual to your generated site too.

**Comment by jfigueroa69** [comment]
I have the following: https://14cf.ns.gluroo.com/14cfec46-82a9-4f09-91f0-19f1982761c9Not sure where to find the Port info on the App as I am very new to this.Thank youJuan Figueroa On Mar 1, 2024, at 8:49 AM, dhermanns ***@***.***> wrote:﻿
Hi! What URI did you enter in Nightguard? It should look like:
https://xxxx.ns.gluroo.com:39893/api/v1/entries?token=14cfec46-xxxx-xxxxx-xxxxx
And the Port 39893 would be typically individual to your generated site too.

**Comment by dhermanns** [comment]
Then you should use

https://14cf.ns.gluroo.com?token=14cfec46-82a9-4f09-91f0-19f1982761c9

as your nightguard URL. Let me know if it works. I will delete all references here.

As soon as you use it, you shouldn't share it publicly ;)

**Comment by dhermanns** [comment]
And the error message you will see just means there are currently no values existing. Which seems to be the case right now.

**Comment by jfigueroa69** [comment]
Not sure what I am doing wrong but the message comes up after I used the link you sent me. Thank you for the support JuanSent from my iPhoneOn Mar 1, 2024, at 10:07 AM, dhermanns ***@***.***> wrote:﻿
And the error message you will see just means there are currently no values existing. Which seems to be the case right now.

**Comment by dhermanns** [comment]
As pointed out: Did you have bgvalues uploaded already? Seems not.

**Comment by jfigueroa69** [comment]
Ok that is where I am confused at so where do I this at? In the Gluroo App or the Nightscout or neither? ThanksOn Mar 1, 2024, at 3:09 PM, dhermanns ***@***.***> wrote:﻿
As pointed out: Did you have bgvalues uploaded already? Seems not.

**Comment by dhermanns** [comment]
Maybe you should read the nightscout documentation or gluroo, if you have no idea how to upload your glucose values. That depends on many factors and is out of scope of nightguard. Visit the nightscout facebook groups e.g.
