### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by razielsparda** [nightscout/nightguard#17]
How I'm supposed to set the app to use mmol/l

**Comment by dhermanns** [comment]
Hi! The app uses your settings on the nightscout backend. So you have to change it there.

I think you can change it by setting an environment variable.

**Comment by dhermanns** [comment]
Have a look at the documentation:
https://github.com/nightscout/cgm-remote-monitor#environment

It should be the environment entry DISPLAY_UNITS.
Hope this helps!
