### ISSUE TITLE
Missing Update Timer when CGM is initializing or no CGM Data available

### ISSUE THREAD

**Issue by MateoB01** [nightscout/nightguard#173]
Hello.
The app (especially on the Apple Watch) is an integral and essential part of my son's daily diabetes management.
Thank you for the great job!

Since the last update I miss the update timer:

![grafik](https://user-images.githubusercontent.com/58656562/139121803-7ca28423-0dfd-4a79-8d0b-10de72c1e823.png)

In the picture, a new sensor has been started that is just initializing.
The timer was very helpful to see that the upload device is connected to the pump.
Currently, I can no longer see on the Apple Watch whether the connection is stable and regular, but have to use the Nightscout app on the mobile phone.

The "problem" is when no current CGM data is available (sensor change, sensor defect, lost sensor, no sensor signal)

Would it be possible to make this timer visible again?

Nice to have: Visible ISIG values ​​during initialization or missing calibration.

**Comment by dhermanns** [comment]
Did you try the latest TestFlight? I'm not sure if that helps. I wasn't able to reproduce this either. On my site I can see the last cgm value even after a sensor change. For more than one hour.

**Comment by dhermanns** [comment]
Closed due to inactivity
