### ISSUE TITLE
Trend value missing in full screen monitor

### ISSUE THREAD

**Issue by Magmaticchimp8** [nightscout/nightguard#174]
Hi, 

seems that the +/- value since the last reading isn’t appearing in the full screen monitor view.

two screenshots here, one showing the delta value in the main screen, then showing 0 on full screen 

![6020C3B9-8DC8-4D2A-88EC-67C0700E3CE2](https://user-images.githubusercontent.com/51284430/139754652-18624338-fe06-4ad9-b7cf-c1404b958d61.jpeg)
![46BDC379-C465-4FEF-A069-B2C333C87C23](https://user-images.githubusercontent.com/51284430/139754653-c63f75bf-a882-497c-a0a8-0fad55d527c8.jpeg)

**Comment by dhermanns** [comment]
Hi! Thanks for your feedback. This is fixed now in the latest TestFlight 3.6.4.759. Apple should approve it for the TestFlight soon. Let me know if that helps...

https://testflight.apple.com/join/Ub8WcpcE

**Comment by dhermanns** [comment]
Its in the app store now.
