### ISSUE TITLE
BG value not updated when BG<=2.2

### ISSUE THREAD

**Issue by annaneubauerova** [nightscout/nightguard#175]
On the screenshot you can see that the numerical BG value has not been updated for more than an hour. However the graph shows that there were other values (2.2) which were downloaded, but did not change the numerical value. Similarly the snooze pressed at BG value 2.3 is not counting down (as can be seen on another screenshot), therefore no alarm will be triggered as long as the actual BG value is 2.2. I’m running iOS 15.1.1
![DAEF75E0-72F0-446F-BD73-B0955A041EFD](https://user-images.githubusercontent.com/42444971/144096041-af9b1b12-332b-49a5-b6e3-98c142f61e61.png)
![599B1F83-400F-42AC-86CE-9B18DE7B3535](https://user-images.githubusercontent.com/42444971/144096055-d1ca0696-f59b-4cf5-8272-f8e96476f157.png)

**Comment by dhermanns** [comment]
Hi! What is your nightguard version?

**Comment by dhermanns** [comment]
It doesn't seems to be just the low value:

![image](https://user-images.githubusercontent.com/3207317/144313640-996c7e96-d45e-49e2-b003-7db540aeebe6.png)

It snoozes and updates for me fine. I would guess that nightscout sends something unexpected which makes the parsing unpossible. If this happens the next time, please tell me what you get when entering

`https://......./api/v2/properties`

in your browser. I think that should clarify it..

**Comment by annaneubauerova** [comment]
Hi, I’m using V.3.6.4.759. 
It works well for anything other than the LOW value. Fortunately I don’t get that too often but will try to send the properties when that happens. 
Thanks!

**Comment by dhermanns** [comment]
Great 👍

**Comment by dhermanns** [comment]
Normally, your properties should contain the latest bg value. Something like:
```
"bgnow": {
"mean": 114,
"last": 114,
"mills": 1642344436410,
"sgvs": [
{
"_id": "61e42ff9eaf84c313e24f739",
"mgdl": 114,
"mills": 1642344436410,
"device": "xDrip-DexcomG5",
"direction": "Flat",
"filtered": 0,
"unfiltered": 0,
"noise": 1,
"rssi": 100,
"type": "sgv",
"scaled": 114
}
]
},
```

But looks like your uploader just sends errors:
<img width="1208" alt="Bildschirmfoto 2022-01-16 um 16 11 00" src="https://user-images.githubusercontent.com/3207317/149665834-f9e2f922-0606-4e6e-9c7e-0dc188f898f9.png">

You could see your probably expected values under the "errors" section. But I would think that it's not a good idea to display them as "normal" values, since nightscout marked them as erroneous. 

Did you enable the "missing values" alert? This alarm should be played because there has been no valid value for a longer time. If that doesn't work, may that should be fixed?

**Comment by annaneubauerova** [comment]
You mean “missed readings” in Nightguard? Yes, I have that on to alert when no data are received for more than 15 mins. But that only triggers when no data are received. In this case it seems data are received, though erroneous.

**Comment by dhermanns** [comment]
That makes sense. Then I will fix that. You should get a „no data“ Alarm
after 15 Minutes.

**Comment by annaneubauerova** [comment]
Thank you very much, I’ll let you know if it works when we experience the low value again

**Comment by dhermanns** [comment]
The new behavior is now:
- if no more bg values are retrieved from the properties endpoint, the last retrieved value displayed in nightguard is exchanged by an empty "---" string. 
- alarms will still work on the erroneous values, because these are still delivered from nightscout by a different endpoint

In your case, you will now get normal low value alarms. The latest TestFlight will have these fixes soon. Let me know if that helps...

**Comment by dhermanns** [comment]
You can test this now:

https://testflight.apple.com/join/Ub8WcpcE

**Comment by dhermanns** [comment]
Let me know if this is still a problem...

**Comment by annaneubauerova** [comment]
Thank you, we had low yesterday but didn’t last long enough. But the snooze timer seemed counting down so it seems it helped. I will reopen if I find a problem. Thanks again

**Comment by dhermanns** [comment]
Great to hear that!

annaneubauerova ***@***.***> schrieb am So. 23. Jan. 2022 um
18:10:

**Comment by annaneubauerova** [comment]
Hi, so unfortunately it seems it didn't help - I'm wondering whether the issue could be due to the snooze button?
On the attached screenshots you can see the following:
- time 0:04 and 0:07: time since last reading moving but snooze time not moving (both pictures show "snoozed for 6 min" but 3 minutes have elapsed)
- time 0:09 and 0:11 and 0:19: I was waiting for 15 minutes since last reading (as I understood that's the setting you changed) and after refresh of the app, the "snoozed for" time has reduced to 1 min (so definitely the behaviour has changed). However, as you can see on the pictures, it is not moving again, ie. the snooze will never get turned off as long as the BG value is LOW
- time 0:21: trying to play with the snooze button shows there is no option to "stop snoozing", which is normally there
I also attach the properties.
Hope this helps to clarify.
Thank you very much for your help

![IMG_5438](https://user-images.githubusercontent.com/42444971/151041542-1cc7e3e5-4b4d-44a0-9dd1-1f5051827809.png)
![IMG_5437](https://user-images.githubusercontent.com/42444971/151041554-93827742-fc39-4b59-a84f-4dfdad448125.png)
![IMG_5436](https://user-images.githubusercontent.com/42444971/151041558-304ac328-8030-41f8-a360-033f7a7dc68e.png)
![IMG_5434](https://user-images.githubusercontent.com/42444971/151041562-f1f22689-b18b-499b-9e71-4040e7216bb3.png)
![IMG_5433](https://user-images.githubusercontent.com/42444971/151041564-3b37be99-3541-436c-a57f-7fb1678f0f5a.png)
![IMG_5439](https://user-images.githubusercontent.com/42444971/151041570-a839b1cc-4065-4fc1-9198-0eca1ef4a800.png)
[properties2.pdf](https://github.com/nightscout/nightguard/files/7936441/properties2.pdf)

**Comment by dhermanns** [comment]
Your latest propertes2.pdf suggest that we have a slighty different situation we had before:
- In your second case, the "latest" value is missing, too
- but you there are no values marked as erroneous

Maybe that explained why my fix didn't helped here. What is your current Nightguard Version in your App?

**Comment by annaneubauerova** [comment]
It’s v3.6.4.759
Regarding the values - strange, the value on xdrip is same in both cases, ie LOW.

**Comment by dhermanns** [comment]
That explains why I can't understand this behavior: you are not using the current TestFlight. It should be 3.6.5.x 😉

**Comment by annaneubauerova** [comment]
This is the latest version available in AppStore. Are we talking about the same app? :(
 
![2C086F1F-D678-4CCD-8271-6A6FFC8654F0](https://user-images.githubusercontent.com/42444971/151442897-0c1df224-52ce-448f-ac2b-fe4c46104726.jpeg)
