### ISSUE TITLE
Xcode Build issues

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/nightguard#178]
I was thinking about modifying the main view or adding a simple view visible at a distance on a small screen. But I am having issues building current master with Xcode, so would have to get past that hurdle first. 

Versions:
macOS 12.0.1
Xcode 13.2
iOS 15.2

(I was thinking about nightstand mode with BG, delta, COB and IOB, and a small BG chart of the last hour or two, perhaps someone already did that? Something similar to https://github.com/mlukasek/M5_NightscoutMon, but on an iPhone). 

I have installed pods, and get build succeeded. But I fail in installing the app to a phone. 

Here is the error message:

<img width="290" alt="Screenshot 2022-01-05 at 10 00 56" src="https://user-images.githubusercontent.com/63544115/148221365-a318573d-302c-437f-bd02-6fbdb04fe7f7.png">

I can't seem to find anything missing in Info.plist, and CFBundleExecutable seems ok:

	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>

Any pointers for how to proceed?

<img width="1408" alt="Screenshot 2022-01-05 at 14 18 24" src="https://user-images.githubusercontent.com/63544115/148224114-77a1b4df-11df-4f0f-8028-e9e6dcead770.png">

**Comment by bjornoleh** [comment]
Turns out there are referenses to xcuserdata for the Duration scene:

Build input files cannot be found: '/Users/dirk/workspace/nightguard/nightguard/fi-FI.lproj/Duration.strings', '/Users/dirk/workspace/nightguard/nightguard/de.lproj/Duration.strings', '/Users/dirk/workspace/nightguard/nightguard/Base.lproj/Duration.storyboard'

I managed to delete those, and switch to relativ path for Duration.storyboard (Duration.storyboard; sourceTree = "<group>";).

After that I cant build the watch app for some reason, I may have messed up the bundle identifiers. I added "2" to the default obne. But only got this error after I deleted the xcuserdata:

error: WatchKit App doesn't contain any WatchKit Extensions whose WKAppBundleIdentifier matches "de.my-wan.dhe.nightguard2.watchkitapp". Verify that the value of WKAppBundleIdentifier in your WatchKit Extension's Info.plist matches the value of CFBundleIdentifier in your WatchKit App's Info.plist.

I deletedDelete Watchapp and Watchapp extension targets just to get past this, and then I could successfully build to the phone.

**Comment by bjornoleh** [comment]
With the initial hurdles behind me, could someone please give me a hint about how to enable the Bedside view? It seems to be disabled in the current master? It might make a good starting point for my project.

**Comment by dhermanns** [comment]
Hi! Bedside view works fine for me on the latest Testflight. So maybe something on sour side? I needed to make some mods to the Eureka Framework. I would have to document this.

This is the reason why you had to comment out some code.
But shouldn't be the reason for the bedside view not to come up.

**Comment by bjornoleh** [comment]
Thanks for your reply! How is the Bedside view activated on the phone, is there a hidden button to push? I think I have seen it before, but not now on both 13 mini and an old SE (2026), both running iOS 15.2 and Nightguard 3.6.4.

**Comment by dhermanns** [comment]
Its the target sign on the snooze button. A short press opens a menu. From
there you can open the bedside view.

bjornoleh ***@***.***> schrieb am Mi. 5. Jan. 2022 um 19:19:

**Comment by bjornoleh** [comment]
Ah, thanks! I had no intention of using the alarms at this point, so had disabled them. Then the Snooze slider and target button was hidden.

**Comment by dhermanns** [comment]
Ah ok - that is a known glitch that should be changed, too :-/

bjornoleh ***@***.***> schrieb am Mi. 5. Jan. 2022 um 21:14:

**Comment by bjornoleh** [comment]
Ok :-)

I noticed there is also no way to snooze an alarm from the Bedside / Full screen view. Not sure if that is intentional either?

**Comment by dhermanns** [comment]
Yes - there is currently a ticket open with such a request . Would be nice
to have it there, too. But not implemented yet.

bjornoleh ***@***.***> schrieb am Mi. 5. Jan. 2022 um 23:07:
