### ISSUE TITLE
Unable to modify target range

### ISSUE THREAD

**Issue by varunmashru** [nightscout/nightguard#185]
I'm unable to find any option to change the target range. It's not even using the range set on my nightscout set up

**Comment by tast3rmonial** [comment]
Dear ,

We are excited to give you an update on Tastermonial.

Today we have initiated a way to evaluate food claims and for customers to get a prescription for continuous glucose monitor (CGM) sensors and experiment with different foods using our app. 

We are actively working to improve your user experiences in:

👉 Ordering a CGM

We realized the uncertainty of CGM prices in major pharmacies around the US. Therefore, our team is now working on a solution to order CGM online and ship directly to you at a competitive price.

👉 Learning from your CGM food experiment data

[See video of current app's abiity](https://youtu.be/xtaoSxdqq6U)

Here's a peek into upcoming Tastermonial app's upgrade in the next few weeks:

- the ability to run food pairing experiments wtih CGM
- automatic syncing of CGM data to view and share the blood sugar experiments
- You'll be able to use our app to scan and evaluate more foods in your pantry (we're expanding our food database)
 We'd be happy to gather your feedback that could help us in prioritizing the next launches. Click the button below to let us know your needs.

[Customer ***@***.***&firstname=&lastname=)

 

Thanks for reading!

Bude & Tastermonial Team

[Facebook](https://www.facebook.com/tastermonial)
[Instagram](https://www.instagram.com/tastermonial)

No longer want to receive these emails? [Unsubscribe](https://manage.kmail-lists.com/subscriptions/unsubscribe?a=TvyBXH&c=01FXX9GKFJ7N78D2MSRYTZAT07&k=e574ec6a7a119f5b1cdfb5f838f13d66&m=WUxwcT&r=RaxVLjU).
TASTERMONIAL

**Comment by dhermanns** [comment]
Could you elaborate a bit more what you like to achieve? Did you mean the glucose ranges? Did you get an error message?

**Comment by varunmashru** [comment]
Yes. I'm talking about the Target Glucose Ranges that show up on the graphs. I think the current default range is 90-170mg/dL. I want to change it to 90-140mg/dL. 
I couldn't find any way to configure that in the current version of the app.

**Comment by dhermanns** [comment]
![image](https://user-images.githubusercontent.com/3207317/160931200-210ce9fa-9879-43a6-a550-5d8e55756796.png)

You can set that on the alarm tab.

**Comment by dhermanns** [comment]
Closed due to inactivity
