### ISSUE TITLE
watchOS MAY be sending wrong carbs

### ISSUE THREAD

**Issue by JohnKitching** [nightscout/nightguard#188]
This is a vague one (sorry) but thought I'd best post in case other people are seeing it. 
I'm fairly sure (but not certain) that sometimes carbs entered on my watch aren't what's getting to NightScout. 
I can't recreate it but I think it's possible I'm dialling up carbs but the confirmation is for a value other than the one I've selected. It's very intermittent. 
I'll slow down my use and pay more attention!

**Comment by dhermanns** [comment]
Ok - awaiting the details.
