### ISSUE TITLE
Graph not updating on Series 2 with WatchOS 4.0

### ISSUE THREAD

**Issue by cjbeck** [nightscout/nightguard#19]
My graph only works after the initial sync of the application on the watch. After that I get the values as text updated, but the graph doesn't update anymore. The app on the phone updates the graph as expected, but not on the watch.

What other information can I provide to assist?

**Comment by fcofernandez** [comment]
Hi
Thanks for your work. Also have the same issue, since I updated to OS 11 and Watch OS 4 , I'm having issue where the graph does not update. The glucose numbers update correctly but perhaps they take longer than before, I think before it took about 3 seconds and now like 10 seconds or have to try a couple of times turning the wrist to turn on the watch for the readings to update. The graph does not update after using it for a while, though if I force quit the app and restart and works again. This happens quite often. 

I also updated the app to the last version released a week ago but still same issues. 

Hope this helps and thanks for your app!

**Comment by dhermanns** [comment]
Hi! I had the same problems with my Series 2 after updating to  iOS 11. Now I have a Series 3 and did some updates to the app. Now - it seems to work much better for me. But sometimes I still have to force a restart of the app. It seems that the running timer which updates the data gets stopped from time to time.

What watches do you have?

**Comment by cjbeck** [comment]
I have a Series 2. I'm wondering if I should try to factory reset the watch?

**Comment by dhermanns** [comment]
I see this problems now more often at my series 3. So don‘t reset yours.

As soon as I find some time I will completely remove the Timer and go to background updates. But this will be a bigger refactoring, so I think it will take a bit more effort.

**Comment by efidoman** [comment]
Thanks - I appreciate your work on this one. I had this issue since upgrading IOS on watch/phone. However, today, it got worse and I can't get the watch complication to update. I can reset watch/phone, delete app and redownload app and it updates just once and then not again.

**Comment by dhermanns** [comment]
No - it shouldn’t be. I get the feeling that Apple has changed something regarding the time budget to do URLSession.

I’m experimenting with this. Looks like Apple stops allowing updates from the web. But normally that should only be the case if running in Background.

**Comment by efidoman** [comment]
The total frozen state of the apple watch updates resolved itself today. It seems to have been a single day problem. If it wasn't related to daylight savings time, then it is quite a coincidence.

**Comment by fcofernandez2** [comment]
I thought it fixed itself but after more testing the problem still there about the graph data freezing or disappearing altogether every few hours. Updates definitely take longer than the previous version. 

Its a shame, I really hope it can be fixed as it really helped us keeping an eye on the glucose, I understand that you are doing this probono but if there is anything we can do to help let us know. Some crowdfunding or sell the app perhaps. It is time that you have to allocate for this so is only fair that we contribute in the project the ones like me who cannot program.

**Comment by dhermanns** [comment]
Maybe I will add a paypal button to the app sometime ;-).

But I‘m still on this issue. I already have reimplemented the whole update mechanism, but still have problems with it :(.

It works fine for hours but than still freezes...

**Comment by fcofernandez2** [comment]
Yes you definitely should add an option for donations in the final version, i would be happy to contribute :)

I´m guessing Apple are not reachable for these kind of issues, I wonder if anyone in the developer´s forum had a similar issue with other apps. 

I was looking to downgrade to OS3 but apparently is not possible after 15 days of use so I´m stuck with OS 4. Tip: Do not upgrade!

**Comment by dhermanns** [comment]
I finally found the solution to this problem: To me it looks like a bug in WatchOS4.

I'm using internally a SKScene. With WatchOS4 Apple stops this scene by setting isPaused = true on it. 
Till now, I was not able to reproduce it. After installing the app, this seems to happen very rarely, but gets more and more a problem after some hours.

The workaround is to set isPaused = false whenever the app comes up.

This is available in the app store now as V1.5.0.

**Comment by cjbeck** [comment]
Awesome! I'll try it now! Thanks so much!
