### ISSUE TITLE
When BG is coming in every minute previous 24 hours not all shown.

### ISSUE THREAD

**Issue by JohnKitching** [nightscout/nightguard#192]
My setup is Libre 2 - Glucose Direct - Loop-dev - Nightscout- NightGuard. 
This gives me 1 minute BG readings. 
Because of the number of data points (I assume) not all of the previous 24 hour grey line is shown. 
![image](https://user-images.githubusercontent.com/48366213/171346478-fd7d6e37-3bad-4bc4-bff1-8c8c887a169a.png)

**Comment by dhermanns** [comment]
Yes already talked to him ;-) . I will create a new TestFlight and you can have a look...

**Comment by dhermanns** [comment]
Testflight is ready:

https://testflight.apple.com/join/Ub8WcpcE

Let me know if that helps...

**Comment by JohnKitching** [comment]
Will do thank you. Might be 48 hours though, I ran out of NS database space so have an eight hour gap!

**Comment by JohnKitching** [comment]
All good now thank you. 

![image](https://user-images.githubusercontent.com/48366213/172921478-e4bd0ecc-90fe-4abc-91e5-0be595351e16.png)

**Comment by JohnKitching** [comment]
Although I should say I'm back to five min updates. It was too much data for Loop too. 
NightGuard was working with one min before I changed it.

**Comment by dhermanns** [comment]
Great - thx for your feedback. I think I will keep the change.
Doesnˋt seem to cause too much overhead and hopefully sensor data updates will increase in the future for other users, too.

**Comment by JohnKitching** [comment]
Thanks for your support as always!
Yeah, it seems to work well apart from the receiving systems not dealing with the data volume too well. 
I saw xDrip can show minute values too but I don't think it passes them on (Android version of xDrip)
