### ISSUE TITLE
Request: run NightGuard on Linux aarch64

### ISSUE THREAD

**Issue by robster7674** [nightscout/nightguard#193]
It would be great if I could create the NightGuard app for my Linux phone (PinePhone) running Manjaro, aarch64.

**Comment by dhermanns** [comment]
The question you should follow is: How can I execute an iOS App on a
PinePhone.
But this is definitely nothing where I could help ;-)

robster7674 ***@***.***> schrieb am Do. 2. Juni 2022 um 10:45:

**Comment by robster7674** [comment]
LOL, I doubt running iOS apps on Linux is feasible, unless of course I can resort to running iOS in a vm (or container). I think it is less effort to port the code, but I am not a developer myself, so I might be wrong here.

**Comment by dhermanns** [comment]
As far as I know Swift isn’t available for Linux at all. Nor are all the
frameworks like Swift UI we are using. So “porting” means writing new from
ground up.

robster7674 ***@***.***> schrieb am Do. 2. Juni 2022 um 10:55:

**Comment by robster7674** [comment]
You got me thinking, and searching. I came across https://github.com/apple/swift/blob/main/docs/Android.md. From there, I also came across efforts to compile Swift stdlib for Linux. So there is activity in that space, I'll dig further into it.

**Comment by dhermanns** [comment]
Feel free to come back if you have a progress here...
