### ISSUE TITLE
Feature request: ability to toggle / turn off the "yesterday" background BG view

### ISSUE THREAD

**Issue by scottleibrand** [nightscout/nightguard#195]
It would be useful to have a preferences option to turn off the grey "yesterday" BG overlay, for both the iOS Main screen and in the Apple Watch app. Some users find it distracts from easily seeing and quickly internalizing their current and recent BG trends.

**Comment by dhermanns** [comment]
Hi Scott,

thanks for your feedback. I will see what I can do. 

Cu,
Dirk

**Comment by dhermanns** [comment]
Its available with build 792 in TestFlight now:
https://testflight.apple.com/join/Ub8WcpcE

**Comment by dhermanns** [comment]
@makotila : There are some new texts that need to be translated to Finnish. Could you have a look ;-)?

**Comment by makotila** [comment]
Ok, I'll check translation
