### ISSUE TITLE
Nightguard Not updating values

### ISSUE THREAD

**Issue by eggy13** [nightscout/nightguard#20]
Hi my nightguard iOS App (iPhone cuttend iOS) Doesnt Update my values anymore. Closikg the App and Restarting Shows the current value After That No more updating. Deleting the App did  Not resoleve. Nightscout App Works Fine. Any ideas? Ty for your help

**Comment by dhermanns** [comment]
Hi eggy - yes that was a bad bug happening during daylight saving switch. Sorry for that :-/. I had the same problems last night. 

I provided a fix with my last commit here. The new version 1.4.3 is in review at Apple now.

**Comment by dhermanns** [comment]
V1.4.3 is now in the App-Store and fixes the problems hopefully next year...
