### ISSUE TITLE
Graphs are not displayed after changing domain name of nightscout website.

### ISSUE THREAD

**Issue by AgushkaNightscout** [nightscout/nightguard#205]
Hello,
Thank you for your great app!

I moved my nightscout website from heroku.com to another hosting, changed the domain name and put the new URL in the app settings. After that bg values, level change, time values, iob, cob, basal and battery are displayed (and changed), but graphs are not displayed, cage, sage, pump battery, tb, tt are not displayed or changed. Iphone 13 pro max, iOS 15.5, Nightguard 3.7.2. Correspondingly, same on the watch. Can you please tell me what the problem could be?

![75bb8a64-6f2b-4d2e-8840-2f104a9dc9b7](https://user-images.githubusercontent.com/90107639/195907762-064046d0-5564-46e7-83bd-fd40a5b2a8d4.jpeg)

![64d808e4-d92d-4f95-a089-6307468e2fbe](https://user-images.githubusercontent.com/90107639/195907768-ffd52a01-1c7f-4daa-951e-49feb18fa70e.jpeg)

Thank you!

**Comment by dhermanns** [comment]
Hi! Looks like your new backend is not working as expected. Nightguard uses some v1 and some newer v2 nightscout apis and some of them seem to return something unexpected.

You could send me your nightscout URI with read permissions and I will have a look.

**Comment by dhermanns** [comment]
What is your new nightscout backend version you probably switched to?

**Comment by AgushkaNightscout** [comment]
@dhermanns Please look [link](https://agushka.site)

NS version is 14.2.6, dev branch. Direct link to current [commit #7043](https://github.com/nightscout/cgm-remote-monitor/pull/7043). On heroku.com was the same version, I didn't change it.

**Comment by dhermanns** [comment]
Seems I need a read token to access your side.
You could send me one to ***@***.***

AgushkaNightscout ***@***.***> schrieb am Sa. 15. Okt. 2022
um 12:09:

**Comment by dhermanns** [comment]
I just tried your URI containing the read token. Works fine and that should have been your problem:

If you secure your web-page even for reading, you will have to provide the token with read permissions in your nightscout-URI. Otherwise nightguard won't be able to read all the nightscout endpoints.

**Comment by AgushkaNightscout** [comment]
You are absolutely right, now all works fine! Thank you very much!

**Comment by dhermanns** [comment]
Great 👍
