### ISSUE TITLE
No graph display anymore, on Apple watch

### ISSUE THREAD

**Issue by plamondon-ln** [nightscout/nightguard#206]
Apple watch series 7, watchos 9.0.2, modular face
Iphone is ok, good graph, iPhone Xs, iOS 16.0.3
Values and stats are displayed, but no graph anymore on the watch.
No problems on iPhone, using security token.
Thanks for a great app.

**Comment by dhermanns** [comment]
Hi! You can leave me your URI and I will have a look:
issue205.hermanns@spamgourmet.com

**Comment by dhermanns** [comment]
What is your nightguard version? Does your watch uses the right URI including a valid token?

**Comment by plamondon-ln** [comment]
Sorry for the missed info:
nightguard v3.7.2.786
My phone uses the right URI, obviously, since the graphs are OK.
But the watch URI? Is'nt it supposed to use the same as the phone? How can I check it on the watch?

**Comment by plamondon-ln** [comment]
Hello, 
I wanted to let you know that after reinstalling Nightguard on my phone and using the internal URL (http://192.xxx.xxx.xxx), it now works. I have a local installation behind a proxy and a firewall. That seems to be the problem. I will now investigate my security settings. Thanks again for your efforts.

**Comment by dhermanns** [comment]
Interesting. Thx for your feedback!
