### ISSUE TITLE
Feature request Home Screen widget

### ISSUE THREAD

**Issue by simensen** [nightscout/nightguard#208]
I'm not sure if this is the appropriate place to make a feature request. I chimed in on #198 since that issue was only regarding Lock Screen widget I thought it best to make a separate feature request dedicated to requesting a Home Screen widget.

I've been using the Home Screen widgets from LinkBluCon and like them a lot.

![CE4A99A7-89CC-4210-A1B1-4322C04B10AB](https://user-images.githubusercontent.com/191200/202921051-b5c19cc1-dea3-47de-8ba5-375695457b57.png)
![EF068107-7E67-4C30-AD58-1A98D707C6F3](https://user-images.githubusercontent.com/191200/202921060-f444d163-b598-431b-97d8-a461378e2833.png)
![202EBCF9-80A4-4389-BDC2-B4472895BAE5](https://user-images.githubusercontent.com/191200/202921071-54db10be-e4e0-4fad-b749-3f61e173475b.png)

Is there a more appropriate place for me to discuss feature requests?

**Comment by dhermanns** [comment]
Would be definitely useful. Maybe someone could help here?

**Comment by bramirez37** [comment]
I would love that too

**Comment by poml88** [comment]
Ok, I added a simple one, we can fine tune it from here. Right now it is similar to the rectangular lockscreen one.

**Comment by poml88** [comment]
Maybe close this as well. Home Screen widet added. Ok, can always be improved...
