### ISSUE TITLE
Feature Request - Display IOB

### ISSUE THREAD

**Issue by miguelkennedy** [nightscout/nightguard#21]
Hi, thanks for the app. It's great.

Can you add IOB to both the iPhone and Apple Watch app/complication? For those that are on MDI it would be great if we could have an option to switch the pump battery field to the IOB displayed in nightscout.

Thanks in advanced!

![nightguard](https://user-images.githubusercontent.com/17232641/32208425-5ee47cee-bdfa-11e7-9104-98decd5b6030.jpg)

**Comment by dhermanns** [comment]
I'm not using the IOB Feature of nightscout. My uploader/pump doesn't support it. So it would be hard for me to test it and always keep it working. But this is an open source project. Maybe someone can help implement this...

**Comment by miguelkennedy** [comment]
Unfortunately I don't know how to code in Swift but it's quite easy to get the iob from nightscout api https://nightscout.address/api/v2/properties/iob

**Comment by miguelkennedy** [comment]
Hi was able to add this feature to both the app and the watch... If pulled the modified files so you can merge them to the project...
