### ISSUE TITLE
Feature request: Badge number x 10 for mmol/l

### ISSUE THREAD

**Issue by segersvard** [nightscout/nightguard#210]
I would like there to be an option to multiply the blood glucose value by 10 for the app notification badge, right now a blood glucose value of 5.6 mmol/l just shows as 6, but I would really like it to be able to show 56 instead :) really like the app!

**Comment by dhermanns** [comment]
Would be too much misleading in my mind. You should go with the lock-screen feature or the widget feature (which is not implemented yet).

**Comment by segersvard** [comment]
Too bad, I’m not convinced it would be misleading at all but you might have a point. I wouldn’t like someone with 3.1 mmol confuse it with 31 mmol, even though I’d like to know wether I have 4,6 or 5,4 at a glance. At least xDrip4iOS has this feature.

Looking forward to the widget 👍

**Comment by dhermanns** [comment]
My time is very limited, but maybe someone from the community can help.
