### ISSUE TITLE
Adding Access Token to enable graph on apple watch

### ISSUE THREAD

**Issue by Kloy40** [nightscout/nightguard#213]
Graph hasn’t been working for a few weeks now and looks to be related to updates and the need to add an access token. Can someone please specify the format for adding the token please? The example on NightGuard app - http://Nightscout?token=mytoken doesn’t make any sense to me!

**Comment by Kloy40** [comment]
Thanks - got the token working but still have no working graph on the watch! Is there a workaround that I haven’t seen yet?

**Comment by Kloy40** [comment]
If fact - there is no graph on NightGuard at all!

**Comment by dhermanns** [comment]
We have had other issues like

https://github.com/nightscout/nightguard/issues/205

which turned out to have misconfigured security tokens, TLS or firewall issues.

**Comment by Kloy40** [comment]
Have tried all those things but no joy. Thanks for trying

**Comment by dhermanns** [comment]
Did you check your TLS Certificate? What is your Rating?

Kloy40 ***@***.***> schrieb am Di. 6. Dez. 2022 um 19:51:

**Comment by Kloy40** [comment]
Sorry - I don’t know what the TLS certificate is! How would I check that?

**Comment by dhermanns** [comment]
Your can check your URI e.g. here:

https://www.ssllabs.com/ssltest/

**Comment by Kloy40** [comment]
Thanks again - just checked that and rating came back as A. Nothing obviously wrong that i could see!

**Comment by dhermanns** [comment]
You can send me your URI:

issue213.hermanns@spamgourmet.com

I will have a look.

**Comment by dhermanns** [comment]
Looks like you have configured your nightscout backend to be accessed by Api Secret. Just by entering your Api Token doesn't work for me. And that is what nightguard uses, too.

**Comment by Kloy40** [comment]
Thanks Dirk,Apologies but I am not a techie, so not sure quite what you are saying. My API secret is what I sent earlier - NorthBerwick. Is that what I need to add to Nightguard to get it to access?I get readings etc on Nightguard, just not the graph. RegardsKenSent from my iPhoneOn 6 Dec 2022, at 20:38, dhermanns ***@***.***> wrote:﻿
Looks like you have configured your nightscout backend to be accessed by Api Secret. Just by entering your Api Token doesn't work for me. And that is what nightguard uses, too.

**Comment by dhermanns** [comment]
You need to generate a token that can be used to access your site. Your Api
Secret shouldn’t be used for that.

Kloy40 ***@***.***> schrieb am Di. 6. Dez. 2022 um 21:46:

**Comment by Kloy40** [comment]
I generated an access token for Nightguard and sent that to you earlier, as well as my API secret. Not sure what to do now! Should I generate another token and scrap the existing one that starts 9130?Sorry for being so stupid. RegardsKenSent from my iPhoneOn 6 Dec 2022, at 20:56, dhermanns ***@***.***> wrote:﻿
You need to generate a token that can be used to access your site. Your Api
Secret shouldn’t be used for that.

Kloy40 ***@***.***> schrieb am Di. 6. Dez. 2022 um 21:46:

**Comment by Kloy40** [comment]
Ok - I will see what I can find out. It does seem strange as everything was working fine until recently. Not sure whether it was upgrading Phone, watch or whatever. Or if it was moving from Heroku to google cloud. Somewhere along the line it has gone wrong. Thank for tryingKind regardsKenSent from my iPhoneOn 6 Dec 2022, at 21:12, dhermanns ***@***.***> wrote:﻿
Not sure whats wrong with your nightscout setup. Maybe you should ask there. Normally your logon screen should work with your token, too.
But thats not the case. Only logon with Api-Secret is working. If you find out the reason for this, nightguard will work, too.

**Comment by dhermanns** [comment]
My guess is it was the resetup of your nightscout backend in google cloud.

**Comment by Kloy40** [comment]
Thanks Dirk,Wasn’t aware that I had changed the setup when I migrated but will have a look and maybe ask Navid if this is common.Sent from my iPhoneOn 7 Dec 2022, at 07:17, dhermanns ***@***.***> wrote:﻿
My guess is it was the resetup of your nightscout backend in google cloud.

**Comment by Kloy40** [comment]
Hi Dirk - fixed it!!!

In NightGuard i needed to enter my URL as https://klnightscout.hopto.org?token=nightguard-90…. - ie, the format for entering it was wrong previously. Now has graph etc all showing. It seems to need the site reconfigured but i can sort that quickly i hope.

Thanks again for all your assistance and i hope that the above may be useful if anyone else has a similar issue.

Kind regards

Ken

**Comment by dhermanns** [comment]
But you can’t still logon to your site with this token?

Kloy40 ***@***.***> schrieb am Mi. 7. Dez. 2022 um 11:35:

> Hi Dirk - fixed it!!!
>
> In NightGuard i needed to enter my URL as
> https://klnightscout.hopto.org?token=nightguard-90…. - ie, the format for
> entering it was wrong previously. Now has graph etc all showing. It seems
> to need the site reconfigured but i can sort that quickly i hope.
>
> Thanks again for all your assistance and i hope that the above may be
> useful if anyone else has a similar issue.
>
> Kind regards
>
> Ken
>
> Sent from my iPad
>

**Comment by dhermanns** [comment]
I thought that that was the reason. But didn’t seem so. So you just entered
the token in a wrong format? How did you enter it before?

Kloy40 ***@***.***> schrieb am Mi. 7. Dez. 2022 um 11:39:

> Do i need to have that? I have always accessed my site with API secret!
> Happy to try to change it if you think there is merit in it, but everything
> seems to be working now.
>
>
> Sent from my iPad
>

**Comment by Kloy40** [comment]
I also had an issue with Sugarmate a few weeks ago and it turned out to be that i needed to add a token on there to get it to work so i just added 9130cb5b41edb3de as the token and it worked fine. When i added the token to NightGuard i just entered the same ie https://klnightscout.hopto.org? 9130cb5b41edb3de

The correct format appears to be https://klnightscout.hopto.org?token=nightguard-9130cb5b41edb3de

All working fine now.

**Comment by dhermanns** [comment]
Great - and thanks for the feedback
