### ISSUE TITLE
Feature Request: Widget/Complication Styles

### ISSUE THREAD

**Issue by mendelini** [nightscout/nightguard#215]
I love Nightguard! I was wondering if there could be different widget styles for the Lock Screen and Watch Complication - for example, one that had only the bg number and a small arrow for the trend with a gauge 
![weather-widget-lock-screen_2x](https://user-images.githubusercontent.com/121192710/209876244-a3bc8597-4785-45b4-9502-6a62646890e7.jpg)

**Comment by dhermanns** [comment]
The upcoming TestFlight implements this:

![image](https://user-images.githubusercontent.com/3207317/232159078-1143bb1d-21c3-4e4a-ad25-2676f3b6959f.png)

**Comment by dhermanns** [comment]
The TestFlight is available now:
https://testflight.apple.com/join/Ub8WcpcE

Let me know if it works for you.

**Comment by mendelini** [comment]
It looks fantastic!

**Comment by dhermanns** [comment]
Thanks. The latest TestFlight improves stability. Let me know if there are any more issues with the new widgets.
