### ISSUE TITLE
No Graphs, No Landscape Mode, No Night Mode

### ISSUE THREAD

**Issue by Wallanaise** [nightscout/nightguard#216]
Hi, just downloaded this app and have set it up (i was unfortunately kicked off during the Heroku changes and have recently signed up to Nightscout Pro for ease). However, on the nightguard app i am seeing no graph data, nothing happens when i turn the phone (for landscape viewing of graph data) and although night mode is listed as a feature i cant find this anywhere within the app. Am i missing something? Thanks

**Comment by dhermanns** [comment]
Hi! Nightguard is always in dark mode. What listing do you refer? Nightguard is an iOS App you can use as a Client to your Nightscout backend. If you have any issues setting up your Nightscout backend, you should talk to your hoster of your "Nightscout Pro" instance.

This is just to report Nightguard bugs. You could get help with your setup e.g. using the nightscout facebook groups.

**Comment by Wallanaise** [comment]
On the app store where i downloaded nightguard theres reference to a night mode where you only see your current BG. That doesnt appear to be a feature anywhere in the app despite the imagery. I have fixed all other issues with a token. On 24 Jan 2023, at 19:37, dhermanns ***@***.***> wrote:﻿
Hi! Nightguard is always in dark mode. What listing do you refer? Nightguard is an iOS App you can use as a Client to your Nightscout backend. If you have any issues setting up your Nightscout backend, you should talk to your hoster of your "Nightscout Pro" instance.
This is just to report Nightguard bugs. You could get help with your setup e.g. using the nightscout facebook groups.

**Comment by dhermanns** [comment]
Ah ok - press the round button right to the snooze button.

Wallanaise ***@***.***> schrieb am Di. 24. Jan. 2023 um 23:23:

**Comment by Wallanaise** [comment]
Ah ok. I had disabled all alerts which removes that button  from the screen altogether! Thanks!

**Comment by dhermanns** [comment]
Yes - that is a known issue which has to be fixed ;-).

Wallanaise ***@***.***> schrieb am Mi. 25. Jan. 2023 um 09:44:
