### ISSUE TITLE
Feature Request: Customize Y-axis Min/Max values

### ISSUE THREAD

**Issue by threegirldad** [nightscout/nightguard#218]
I deal far more with hypoglycemia than hyperglycemia, so it would be very helpful to be able to change the Y-axis values accordingly (e.g., Min=60, Max=160).

***EDIT*** Someone in a Facebook group pointed out that these values match the alarm targets.  I wasn't aware of that.  Perfect!

**Comment by threegirldad** [comment]
Yes, thank you.  I tried to edit the post to explain that someone pointed that out to me.  Changing the alarm targets also changes the graph targets, which is exactly what I was looking for.

**Comment by dhermanns** [comment]
Yes. And beyond this, the y-Axis adjusts automatically depending on the bgvalues of the last two days.
