### ISSUE TITLE
Nightguard from source 

### ISSUE THREAD

**Issue by j-kaltes** [nightscout/nightguard#220]
![nightguard](https://user-images.githubusercontent.com/72013079/227585837-8fff06b3-b596-4e4e-aa73-8d010a558eb0.png)
I tried to run Nightguard in xCode, but it failed (see picture). The README.md says that "_you will have to modify the SliderRow in the following way:_"

```
public final class SliderRow: Row<SliderCell>, RowType {
    public var steps: UInt = 20
    public var shouldHideValue = false
    public var lastSelectedValue : Float?

    required public init(tag: String?) {
        super.init(tag: tag)
    }
}
```
But the only SliderRow I can find is "extension SliderRow" in CustomFormViewController.swift which seems to be something totally different.

**Comment by dhermanns** [comment]
Hi!

did you do a

pod install

before? It should pull the pod dependencies. And this is where you have to
update the mentioned code.

Jaap Korthals Altes ***@***.***> schrieb am Fr. 24. März 2023
um 17:33:

**Comment by dhermanns** [comment]
Now you would have to adjust the SliderRow the way described on the github
page.

Jaap Korthals Altes ***@***.***> schrieb am Fr. 24. März 2023
um 18:01:

**Comment by j-kaltes** [comment]
Yes, when I just add the code before the extension, it does work. Why isn't it uploaded to the github?

**Comment by dhermanns** [comment]
Its code modifying the pod dependency. So you could try to provide a pull request for the eureka framework.
