### ISSUE TITLE
Modular face on Apple Watch 

### ISSUE THREAD

**Issue by KeiraAlexandra** [nightscout/nightguard#223]
My Apple Watch made an update tonight and it doesn't allow me to choose Nightguard BG values for the middle section on Modular face anymore. It was so fantastic - I could see last 3 readings and +/- change of BG values at a glance. How do I make my Apple watch understand that I want Nightscout in the middle section (I can choose it in top, bottom left and right but then I get only current BG reading)? I have tried basically every available face and Nightscout doesn’t appear as option in any complication with graphics opportunity. Is there a way to fix that?

**Comment by dhermanns** [comment]
Have a look at #222 . Seems to be a duplicate. Closing this one.
