### ISSUE TITLE
Development setup guide

### ISSUE THREAD

**Issue by grahamjenson** [nightscout/nightguard#225]
I was looking at customising some views and I am new to iOS development. I was wondering if you could write a quick setup guide to get a development environment working?

At the moment, when I checkout the master branch and run `pod install` I get the error:

```
[!] Unable to find a target named `nightguard WatchKit Extension` in project `nightguard.xcodeproj`, did find `nightguard`, `nightguardTests`, `nightguardUITests`, `nightguard Widget Extension`, `nightguard WatchKit App`, and `nightguard ComplicationExtension`.
```

I wonder if I am missing some previous step?

**Comment by dhermanns** [comment]
Hi Graham,

did you do pod install before opening the project for the first time?

And have a look afterwards at the readme.md. There is an issue with eureka. Everything else should work immediately.

**Comment by grahamjenson** [comment]
Hey,

Cheers, I made a very basic mistake of opening the project file and not the workspace file. Took me three days to figure that out 🤦 

Now to actually learn some coding :)

**Comment by dhermanns** [comment]
Great - awaiting your Pull Request ;-)

**Comment by poml88** [comment]
Hm, I can't get it to run. I get exactly the same error message from the first post. 
So I do the git clone, then enter the directory and do a pod install.
And then I am stuck. Any advice?

**Comment by poml88** [comment]
thanks for helping!
Hm... I deleted the target nightguard WatchKit Extension from the Podfile, that also works, but it this the way to go?
I can try to open the project file. I opened the workspace file for now.
