### ISSUE TITLE
Using https://bernardoramirez.up.railway.app/?token= and nightguard still tells me I have no token access

### ISSUE THREAD

**Issue by bramirez37** [nightscout/nightguard#227]
Installed Nightgard today on my Iphone, add the URL https://bernardoramirez.up.railway.app/?token=thisismytoken format to the url. 
And now want to tell the system that I changed cannula and error.

Is token different from apisecret? if yes where can I create a token?

Thanks

**Comment by dhermanns** [comment]
Yes - Api-Secret ist different to the Token.

Have a look at the nightscout documentation "Create Token":

https://nightscout.github.io/nightscout/security/
