### ISSUE TITLE
No graph.

### ISSUE THREAD

**Issue by jetcrabs** [nightscout/nightguard#228]
I did NS on Google Cloud yesterday , pure base without any parameters , data from xdrip. Ubuntu 20.04.6 LTS. NS 2023.05.09. Nightguard shows the BG but does not generate a graph. Does it need any specific parameters?

**Comment by dhermanns** [comment]
Did you secured your backend and provided a security token in your nightscout URL? What Device are you using? What is your nightguard version?

You can send me your Uri if nothings helped: ngissue.hermanns@spamgourmet.com.

**Comment by jetcrabs** [comment]
Thank you very much, my mistake, I did not generate the token. Best app , thanks again and sorry for bothering you.

**Comment by dhermanns** [comment]
No problem. Welcome ;-)
