### ISSUE TITLE
Can’t get Nightguard to sync to Apple Health

### ISSUE THREAD

**Issue by fonewiz** [nightscout/nightguard#229]
At some point in the past I installed Nightguard and had my readings from my Libre 3 syncing to HealthKit. I saw the past readings from Nightguard which I recently deleted. I uninstalled Nightguard at some point and recently reinstalled it once I got my new Nightscout site setup. Now I can’t get Nightguard to sync to HealthKit no matter what I do. It’s turned on in Health, it’s turned on in Nightguard, permissions all look good etc. Killed both the Nightguard app, killed Health app, complete power cycle of phone. I have removed other blood sugar apps that might interfere and so on. Just can’t get it to add any of my readings to Apple Health. I see the current number in Nightscout but I never see any of the averages or anything else, maybe I don’t understand how to use this app yet. Just thought I would post this and see if anyone had an idea of something I might be missing to get this working again. Thanks in advance.

**Comment by fonewiz** [comment]
So you're saying I need to leave the app open and on the foreground on my phone in order for it to update Apple Health? That seems odd but I set it to stay active just now and I'll leave it that way for 20 or 30 minutes to see if I get anything synced to Apple Health. This would seem kind of, well, mostly useless though if this is the way it works. I mean, for me anyhow. I don't leave it open all the time but I guess some people do, especially overnight thus the name Night Guard?? The only real reason I personally installed it was to get my numbers into Apple Health.

**Comment by fonewiz** [comment]
Not to take anything away from the hard work of the devs, didn't mean it that way. Just mentioning what my use case is.

**Comment by fonewiz** [comment]
Maybe I just don't have NightGuard setup right. When I open it, I do see my current blood glucose number as of the last update which seems to be every 5 minutes. BUT.. In the little circles below it show 0/288 Readings and the other 3 circles seem to be full of nothing really, just has averages and 0% in range which I know is wrong. Gonna check my NIghtScout site too, maybe that's the issue. Any help is appreciated, thanks.

**Comment by dhermanns** [comment]
Did you have generated a security token and provided that in the nightguard Uri?

And nightguard syncs older values to apple health, but you will have to have it in foreground at least once, since background updates are very restricted in the apple eco system.

**Comment by fonewiz** [comment]
I don't have it set that way right now but I did try this a few days ago. I'll setup a new token and add it to the URI and see if that helps. Thanks.

**Comment by fonewiz** [comment]
I just setup a token again and now the app looks WAY different, has WAY more info. The little blue circles have data now etc. I set the role to admin for now. What is the minimum role required? I don't see anything syncing to Healthkit yet but I'm hoping it will just be a few minutes before data starts showing up. Thanks for your help so far @dhermanns !

**Comment by fonewiz** [comment]
@dhermanns Awesome! I now have 19 days of data in Healthkit! Woop! Not sure what happened when I setup the token last time but it definitely works now! Thanks so much. I just need to figure out what role level I should have for Nightguard, I'm guessing admin is not needed lol
