### ISSUE TITLE
Apple Watch Complication - Number only

### ISSUE THREAD

**Issue by tedtucker** [nightscout/nightguard#230]
On my Apple Watch Ultra my Nightguard Complication currently shows read time and value. This takes up a lot of space and makes the number harder to read at a glance. I feel it would be much more valuable to have only blood sugar value and perhaps an indicator (* even) if the value is older than 5 minutes.

**Comment by dhermanns** [comment]
Hi Ted - did you try the latest Testflight Version?
Or what nightguard Version are you using?


Ted Tucker ***@***.***> schrieb am Do. 8. Juni 2023 um 20:04:

**Comment by tedtucker** [comment]
Version 3.7.3

**Comment by dhermanns** [comment]
You should try the latest Testflight Version.
Complications are completely rewritten there:

https://testflight.apple.com/join/Ub8WcpcE

**Comment by tedtucker** [comment]
hahahaha.... yeah... that is perfect. what does the gauge represent?

**Comment by dhermanns** [comment]
The Age of the retrieved value

**Comment by tedtucker** [comment]
Wow this works well. Than you so very much. Testflight says the app will expire in 30 days?

**Comment by dhermanns** [comment]
Yes - the release will be done till that time ;-)
