### ISSUE TITLE
Issue with middle position on modular watch face

### ISSUE THREAD

**Issue by andypituch** [nightscout/nightguard#232]
Hi!

I can no longer add the nightguard to the middle position of the module watch face, but I have no issues adding it to any other "position" on this watch face or any of the other watch faces. I've seen where this might be an issue because of a watch or phone update but I wanted to confirm that and see if there is a workaround.

**Comment by dhermanns** [comment]
Hi Andy!Did you try the latest Testflight Version?

https://testflight.apple.com/join/Ub8WcpcE

**Comment by andypituch** [comment]
Nope, didn't even know it was a thing/option. I will try this later today and report status... Where can I find info about the beta version and the issues that it addresses?

Also, to circle back on the root cause... is this an expected experience due to a recent iOS or WatchOS update?

**Comment by dhermanns** [comment]
Do a search on issues here. There have been other requests with issues regarding complications. Seems to be introduced by some watchos updates.

**Comment by andypituch** [comment]
Thank you! joining the TestFlight/Beta has made the new complication available in the middle position of the modular watch face. Thank you!

I'm not sure what the correct method to provide feedback on the "new way" is, but I would like to see the trend arrow direction on each reading since we no longer have the graph (if that's possible). It looks like it's available in the other positions so hopefully it can be integrated into the middle slot as well.

**Comment by dhermanns** [comment]
You ment the multiple value complication? I could do a simple delta value calculation there, but sure that is not exactly the same. I think I will provide a full graph there.
