### ISSUE TITLE
BG delta not showing

### ISSUE THREAD

**Issue by dexterbooty** [nightscout/nightguard#233]
BG change shows as +- followed by single digit.  E.g +0.5 shows as “+-0.” On the screen.  Value will show correctly on full screen monitor. 
![95179d27-08e9-4d7d-92ad-ef75c44c3989](https://github.com/nightscout/nightguard/assets/10778986/6005331f-3eee-4f4c-b8dd-0184b971a7a2)

**Comment by ricardoadan2** [comment]
Having the same issue.

**Comment by dhermanns** [comment]
Works on my machine ;) . But I don't have a mmol backend system that is usable right now. So you can send me your URI and a Read-Token to nightissue233.hermanns@spamgourmet.com and I will have a look.

**Comment by maskac** [comment]
I have same issue , open nightscout you can try it https://dite14.nightscout.cz/

**Comment by robnightscout** [comment]
Same here, delta broken on iPhone app and Apple Watch. May be an incorrect divisor as it's usually +0 but I have seen +0.1 on a large jump (actual delta +1.0). On mmol/L as per others above

**Comment by dhermanns** [comment]
This should be fixed now in the latest TestFlight V3.8.1:
https://testflight.apple.com/join/Ub8WcpcE

Apple should approve this in the next hours for beta testing...

**Comment by dhermanns** [comment]
Ready for testing now. Let me know if this helps...

**Comment by ricardoadan2** [comment]
Thanks for the fix. We did a bit of testing. Phone was working perfectly. Watch showed a delta of 0.1 when in reality it was 1.1.  I sent you the screenshots.
Thanks again.

**Comment by dhermanns** [comment]
Thanks for your Feedback. A new TestFlight version is coming to address this ;) .

**Comment by dhermanns** [comment]
And once more ready for testing ;)

**Comment by dexterbooty** [comment]
Looks good can see a 1.1 rise coming through. ThanksOn 8 Jul 2023, at 15:19, dhermanns ***@***.***> wrote:﻿
And once more ready for testing ;)

**Comment by ricardoadan2** [comment]
Working perfect now. Thank you so much for providing a fix!! This app is a life saver for us!!

**Comment by dhermanns** [comment]
Great 😍👍
