### ISSUE TITLE
Nueva actualización ya no funciona para Apple Watch antiguo serie 3

### ISSUE THREAD

**Issue by estefaniadalbosco** [nightscout/nightguard#234]
Hola, usaba la app para seguir a mi hijo que tiene DM tipo 1 y ahora con la nueva actualización, ya no puedo tener la app en el reloj, ya que es para sistema operativo sobre 9, los Watch serie 3 solo se pueden actualizar hasta la 8.8.1, alguna posibilidad de que se pueda volver a habilitar? Era la app más útil para poder ver a mi hijo mientras va al colegio. Gracias

**Comment by dhermanns** [comment]
Sorry, I don't speak spanish. I needed to raise the minimum WatchOS requirements to support the new complications. The old way was broken.

So you have to use the phone to follow. Sorry!
