### ISSUE TITLE
Apple WatchOS complication Not available anymore

### ISSUE THREAD

**Issue by funkstille** [nightscout/nightguard#235]
Since last apple updates the nightguard Apple Watch complication is gone. Is there a way to fix this?

Apple Watch 8
WatchOS 9.5.2
iPhoneOS 16.5.1
Nightguard 3.8.0.828

**Comment by dhermanns** [comment]
They are reimplemented. So you have to reselect them. If they are not installed correctly, try to deinstall/reinstall the watch part.

**Comment by funkstille** [comment]
Uninstall und install in the Watch app did. the trick. Working again. Thanks for the quick support!

**Comment by funkstille** [comment]
Done

**Comment by dhermanns** [comment]
Happy to help 😉
