### ISSUE TITLE
Apple Watch 3 doesn’t work with V3.8

### ISSUE THREAD

**Issue by PapaundMama** [nightscout/nightguard#237]
I updated the nightguard app to V3.8 and the app disappeared from my Apple Watch 3 (watchOS 8.8).
Which version of nightguard works with that Apple Watch 3?

**Comment by ewingate** [comment]
Also facing this issue. Is this something that will be looked at, or do we need to upgrade the hardware?

**Comment by dhermanns** [comment]
Sorry - you have to upgrade or use the older v3.7 if you know how to sideload.
