### ISSUE TITLE
unknown error while extracting data from pebble watch api   

### ISSUE THREAD

**Issue by MarTD1** [nightscout/nightguard#238]
My daughter's nightguard app has this display "unknown error while extracting data from pebble watch API  " and is not providing any readings. I have uninstalled and re-installed the app, and nothing has changed—the same error code on the phone.
It no longer works on my Apple watch as well. 

I do not have a pebble watch connected to anthing if that helps. 

Any help would be much appreciated as we utilized this app much more than Dexcom for blood sugar readings. 

Thanks

**Comment by dhermanns** [comment]
Hi! Sorry - missed that one. You can provide your URL if you are still struggling with it.

**Comment by SaulAdelman** [comment]
I am getting unknown error while extracting data from prebble watch API
