### ISSUE TITLE
Finer grained increments at lower levels

### ISSUE THREAD

**Issue by motinis** [nightscout/nightguard#240]
Could we please have the increments < 100 be 5, rather than 10? E.g., 60, 65, 70, 75, ... , 95, 100?

Currently we change our settings from day to night - during day we use low prediction (e.g. 20 minutes to 70 or 25 minutes to 60) and fast drop; at night - assuming we're not coming down from a severe high we will generally turn these off (otherwise a compression can cause a drop that will set off the alarm even if it doesn't get to a low) and use a little bit higher low values. It would be useful to be able to use 75 and not need to choose between 70 and 80.

Thank you - we super appreciate Nightguard! It has saved us during the day more than once, and really helped us get our sleep back in the nights.

**Comment by dhermanns** [comment]
Never expected that someone can that exactly define the threshold ;) . But that's of course an easy one.
Here you got:
https://testflight.apple.com/join/Ub8WcpcE

#wearenotwaiting ;) 

Know exactly where you talking about with your sleepless nights.

**Comment by motinis** [comment]
Thank you so much. This helped us out.

We’ve recently changed how we’re using Loop so I think the old way of
increments of 10 is fine now. So you don’t need to keep maintaining this
version.

Super appreciate the help!!

**Comment by dhermanns** [comment]
Great to hear that.

**Comment by motinis** [comment]
We’re back to using this now most nights.  So appreciate it being available. Thanks!!

**Comment by dhermanns** [comment]
Great to hear - welcome 😉
