### ISSUE TITLE
Apple Watch Series 3 (watchOS < 9) compatibility 

### ISSUE THREAD

**Issue by auburnham** [nightscout/nightguard#241]
Apple Watch Series 3 does not get the watchOS 9 update. Could you make a version available for the Series 3 watch?

**Comment by dhermanns** [comment]
You can checkout every old version of nightguard and deploy it to your
watch. But through app store apple allows only one version to be available.
Sorry.

auburnham ***@***.***> schrieb am Fr. 1. Sept. 2023 um 04:24:

**Comment by auburnham** [comment]
Thank you, I appreciate

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by auburnham** [comment]
Thank you. I appreciate the reply & understand the store limitation. Is there a guide for deploying old versions to the watch?

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by dhermanns** [comment]
You will have to install Xcode and compile a version yourself. You can follow any watchos beginner guides.
