### ISSUE TITLE
Apple Watch update - Modular face, no BG values

### ISSUE THREAD

**Issue by KeiraAlexandra** [nightscout/nightguard#242]
With the latest Apple Watch update the BG values doesn’t show up in Modular face anymore.
Is there a way to get the 3 readings back in the middle part of the Modular face?

**Comment by dhermanns** [comment]
Do you really ment the modular face complication? Or is this a duplicate to #241.

**Comment by KeiraAlexandra** [comment]
Hello!It was a duplicate to 241, sorry for the confusion :(After yesterday’s fixes it all works just fine again, thank you so much!!!!Best regardsKristina On 13. Sep 2023, at 08:23, dhermanns ***@***.***> wrote:﻿
Do you really ment the modular face complication? Or is this a duplicate to #241.

**Comment by dhermanns** [comment]
What fixed it?

**Comment by KeiraAlexandra** [comment]
Hello!I thought you did something to fix the issue :)But if it wasn’t you then it was probably an update of software I did on iPhone yesterday morning.Best regardsKristinaOn 14. Sep 2023, at 09:11, dhermanns ***@***.***> wrote:﻿
What fixed it?

**Comment by dhermanns** [comment]
Ok ;) .
