### ISSUE TITLE
No option on iwatch for Nightguard

### ISSUE THREAD

**Issue by KlausTheDog** [nightscout/nightguard#243]
Hi I am late to the table on this one but I have a libre 2 going from gluroo to Nightguard (this part is working).
I don’t seem to have the option to add Nightguard onto my iwatch though using the complications. It isn’t listed anywhere on the iwatch apps either!?? Tried everything I can think of but not getting anywhere.
Please help if you can 🙏🏻
I have an iPhone XS iOS 16.6
Iwatch 3 OS 8.8.1
Nightguard version 3.8.1

**Comment by dhermanns** [comment]
Hi! Have a look at #241. Series 3 is not capable of running nightguard anymore.
