### ISSUE TITLE
Widget/Complications Disappear

### ISSUE THREAD

**Issue by CaldenHartz** [nightscout/nightguard#246]
New user and admittedly not the savviest.  Followed Diabetech's video and got up and running.

Problems arose shortly after.  Widget on lock screen of iPhone iOS 17.0.2 works at first but after a couple short hours, becomes invisible.  This is to say that the widget is still there, as the interface tells me but is invisible.  Tapping on the "blank" space where the widget once showed up takes me to the app as per usual.

The same exact thing happened to me on my Apple Watch 9 running 10.0.2.  The smaller format is supported fully and has never disappeared but the longer format (showing 3 time stamps and readings) has also disappeared or as the first case, turned invisible.  Tapping the "blank" space does still bring me to the app as per normal, just as on iPhone.

Thank you for your excellent app, before I forget and I hope this is not just egregious user error!

**Comment by dhermanns** [comment]
Hard to say whats going on. Looks like an iOS Glitch for me.
What phone are you using?

You can leave me your url here: issue246.hermanns@spamgourmet.com
But I would be surprised if I could reproduce it on my hardware.

**Comment by CaldenHartz** [comment]
Thank you very much for the reply.  I appreciate your attention on this!  I will provide said URL via the channel provided but would like to mention that another user via Diabetech's guide/video has also reported the same "issue" which I thought was interesting and made me feel less alone and incompetent! Haha.

Please expect URL soon!

![libre](https://github.com/nightscout/nightguard/assets/78230670/d490a9d7-14ee-409f-be85-3ae5720ba5df)

**Comment by dhermanns** [comment]
Tried your URL and it works fine on my Ultra 1 Watch with WatchOS10.0.1.

Tried different complications which all displayed correctly.

So you could try to uninstall/reinstall just the watch part of the app and reselect the complications. At least that helped in the past sometime.

**Comment by CaldenHartz** [comment]
Thank you for going out of your way to test on your end.

To update you, today, for a brief couple hours the longer format widget reappeared visually on my iPhone lock screen.  As of writing this however, it has once again become invisible. 

The widget (long form) is still invisible on my watch.

Will do as you suggest and report back!

**Comment by CaldenHartz** [comment]
Update: Proceeded as instructed and had no such luck.  Attached is a photo of me trying to assign app to aforementioned space.  Even without being on watch face, it appears blank.

It seems it is some Apple voodoo!  I am sorry this is ridiculous.
![incoming-F9B6565B-4041-418A-BEAD-3767AFF9D09A](https://github.com/nightscout/nightguard/assets/78230670/39f3c2c0-e32d-4a93-9308-5929985898f9)

**Comment by dhermanns** [comment]
Apple takes a snapshot of the App. If I did a fresh install, it is missing and therefore is blank. But this is just the complication selection. The complication itself should work on the screen.

**Comment by CaldenHartz** [comment]
Hello!  Deep apologies for the delay in my response.  The widget on the lock screen continues to come in and out of visible sight though the watch version has never reappeared.

I will just leave this as is.  It works beautifully as the mini complication and I am extremely happy with the hard work that is put into this.  Thank you so much for being patient with me!

**Comment by dhermanns** [comment]
After updating to ios 17.0.2 / watchos 10.0.1 I noticed this once. But
continued to work soon afterwards. So looks like Apple introduced an issue.

You could even try the latest Testflight:
https://testflight.apple.com/join/Ub8WcpcE

I will soon deploy a fresh compiled version with the latest Xcode there.
This sometimes help too with such glitches.

Regards,
Dirk

Calden ***@***.***> schrieb am Di. 3. Okt. 2023 um 06:57:

**Comment by CaldenHartz** [comment]
Hello again!

I have done as instructed and downloaded the Testflight version.  I am having no change in the magical behaviour of the lock screen widget and the Watch version from henceforth has never reappeared ha!

I will keep an eye on things as you suggest and hope for the best.  In the meantime, truly, the app is a marvel and I am so deeply grateful as a new diabetic (2).

**Comment by dhermanns** [comment]
TestFlight build 3.8.2.836 is now available. It's the first version compile for WatchOS10. Maybe that helps...

**Comment by CaldenHartz** [comment]
Good evening! I have downloaded the latest version via TestFlight. After having to turn phone on and off for another reason, the lick screen widget did reappear for a large chunk of the day but has gone into hiding again as of writing this. I am in no way harping for a fix, I am hoping this feedback helps you or another user if they stumble upon my hapless misadventures. 

That being said, Watch widget still pretending to be Houdini but that’s ok! The mini one is perfect in itself for my uses. 

For my own clarification: is the Watch widget and even the iPhone Lock Screen widget supposed to self update or does it only do so when going physically into the app?

Thanks again!

**Comment by dhermanns** [comment]
It should self update once an hour if you have background updates activated:

https://medium.com/@h3rmanns/enabling-background-updates-for-you-iphone-and-watch-4b8167a70b24

**Comment by CaldenHartz** [comment]
Thank you for being so kind, helpful and thorough.  I have double checked that I have all these settings already and thankfully, I do!  I asked because I am noticing VERY large time spans with no update- even when I manually open the app.

![IMG_9721](https://github.com/nightscout/nightguard/assets/78230670/0858e9af-4dd3-42b1-aaf3-b1615652c88e)

Apologies for the colourful background.

I do not mind as I, for now, obsessively check the app(s) as I am very new to this diagnosis but was merely wondering!

Thanks again for continuing to offer me support!

**Comment by dhermanns** [comment]
But does it update without using the App? If yes, then its ok. Apple learns at what times you use the App and, e.g. at night completely stops updates.

**Comment by CaldenHartz** [comment]
Alas, no. I have to check my up to date numbers manually and it seems (I will have to find you evidence) that even when opening the app, the Lock Screen widget doesn’t update, regardless. 

As noted, will come back with more info. 

Thank you!

**Comment by CaldenHartz** [comment]
Update:

As suspected, app does not update seemingly at any reasonable interval for lock screen widget.  It is the afternoon.

Moreover, opening the app itself does not force a refresh.

Just thought you'd like the feedback!

Thanks again, a million times over.

![IMG_9730](https://github.com/nightscout/nightguard/assets/78230670/2ea08dd0-4c19-4a06-b490-2f7b9e521e69)

**Comment by dhermanns** [comment]
Seems to be that the widget didnˋt get any updates. Normally Nightguard immediately asks for a refresh if new values are available. So I would assume something Device specific.

**Comment by CaldenHartz** [comment]
Oh no.  I will take your word on it.  I will be upgrading in the winter to the new iPhone so I hope this resolves it!

Thank you for your wisdom and guidance.

**Comment by dhermanns** [comment]
I would expect a software setting not a hardware thing. But Apple introduced a new background API I will have to switch to. Maybe that removes some of the glitches (and adds more regular updates, too).

**Comment by CaldenHartz** [comment]
You would know better than I.

All things in good time I am sure.  I am certain all users are just grateful in general!

Thanks!
