### ISSUE TITLE
Complication not automatically updating on Apple Watch Ultra 2

### ISSUE THREAD

**Issue by SmiteDiabeetus** [nightscout/nightguard#247]
Hi there! I am really struggling with this new watch (Ultra 2). I am trying to figure out why Nightguard simply refuses to update on the complication. All the backend data is being updated properly and displaying on my Nightscout site, and the complication will pull from the site when I tap on the complication and open the nightguard watch app, I have rerolled the watch, re-paired watching and phone, set to cellular only, reinstalled the app several times, verified that Nightscout is the latest version.

I have also verified that background data syncs are enabled, and that the nightguard watch app log shows the appropriate 'tasks' and 'schedules';  "WKWatchConnectivityRefreshBackgroudTask recieved" followed by "URL session started", then "Scheduled next" accompanied by the next refresh time, however the complication fails to update at the time of the refresh with updated data!

Have I missed something? Anyone else seeing this at all?
![watch1](https://github.com/nightscout/nightguard/assets/57505669/e3d719af-bc85-4519-acb6-7ca4d2d5bc03)
![watch2](https://github.com/nightscout/nightguard/assets/57505669/9cacecf0-e8e0-4b44-8e49-9cc8a0db52b8)

**Comment by dhermanns** [comment]
If you have even different nightguard complications on the same watchface, they even sometimes update different.

So I would expect that even if the Background update works fine, Apple schedules updates for the complications, too.

And these should improve the more you use the complications. So maybe this improves the longer you use your new watch with the nightguard complications.

Quite boring, I know...

**Comment by SmiteDiabeetus** [comment]
Thats a bummer, apart from being able to bolus from my loopkit app, its pretty useless if it never updates! looks like this $1000 watch is going back, and ill just go back to using my fitbit. Amazing that a nearly trillion dollar company can’t seem to figure something a simple as user defined app update/refresh preferences. Boo apple!

**Comment by dhermanns** [comment]
They are protecting battery life. But maybe we implemented background updates not the way apple wants us to.

But since even apples own background update example doesn't work for me, seems not easy to implement ;-)

**Comment by SmiteDiabeetus** [comment]
True. I contacted Apple, apparently they are seeing a number of issues with complication updates after the last few watchos updates. So could be that you guys haven't done anything wrong! Thanks for your help!

**Comment by dhermanns** [comment]
But don't expect too much. Complications are more for something like weather updates that don't need updates every 5 minutes.

My experience is that you should see updates every hour. If you want more, keep nightguard in foreground.

**Comment by SmiteDiabeetus** [comment]
"Servers can send up to fifty complication pushes per day to each individual watch (no limitations on how frequent they are, aka they can be 50 pushes in one hour)"  [wwdcnotes](https://www.wwdcnotes.com/notes/wwdc20/10049/)

when you say " keep nightguard in foreground." what do you mean by that (apologies this is my first apple watch!)

**Comment by dhermanns** [comment]
You can do server pushes. But therefore you would have to have a server
that does the pushes. With nightscout you host your own backend and
therefore you are not easily able to do server pushes at all.

Therefore nightguard canˋt use them at all.

With foreground I mean you would have to let the nightguard app running on
your watch. Not just a complication on the watchface. If its active, it can
do updates as frequently we like.

SmiteDiabeetus ***@***.***> schrieb am So. 1. Okt. 2023 um
20:43:

**Comment by SmiteDiabeetus** [comment]
I think I was spoiled by my fitbit w/ the sentinel watchface. It would update within 30 seconds of the CGM/Nightscout. Add on 3 days of battery life...and I am asking myself why did I buy this thing again? 

Anyway, not a fit for me on this platform i guess. Appreciate your time and help @dhermanns !
