### ISSUE TITLE
No sugar schedule

### ISSUE THREAD

**Issue by Alfidus** [nightscout/nightguard#248]
Hello, please tell me, is there any solution for the missing schedule?
Latest application version (3.8.1.831), Nightscout version 14.2.6, iPhone SE 2, iOS 17.0.2
The sugar itself is shown, but it does not load from the server and does not build a new graph
Tell me, are there any options?
In the line with the server, the token also indicated - nothing has changed

I attach a screenshot - https://imgur.com/a/t10zz58

**Comment by Alfidus** [comment]
Also this evening I noticed that the application does not send notifications

**Comment by dhermanns** [comment]
Did you change something on your Backend side? Looks like the api v2 can't be accessed.

You can try the latest Testflight but I would think this has to do with your Token or Settings on your nightscout backend.

**Comment by dhermanns** [comment]
You should check your generated token. Should be a security issue.

**Comment by dhermanns** [comment]
Let me know if this is still an issue, but closing so far.
