### ISSUE TITLE
Watch complication issue

### ISSUE THREAD

**Issue by Michaelmkh** [nightscout/nightguard#249]
I have an Apple Watch complication named de-my.wan.dhe.nightguard.watchkitapp. How do I get rid of it?  I tried deleting the nightguard app from my iPhone iOS 17 and that didn’t help. I want to install the nightguard complication on my watch and the widget on my phone.

**Comment by dhermanns** [comment]
I noticed that too. Looked like an Apple Watch Bug to me. You can try to deinstall the Watch part and restart the watch. After that it should be disappeared.

**Comment by dhermanns** [comment]
And take care, that you don't have an old version of the app installed. Maybe as TestFlight?

**Comment by Michaelmkh** [comment]
Here is the weird thing. I deleted Nightguard from my iPhone (iOS 17) and restarted both Apple Watch (watch OS 10) and iPhone. Still same issue. But after about an hour the problem went away. Not sure why or what I did. Passing this along in case someone else has this issue. In the future if this happens again I will try deleting the watch part also.

**Comment by Michaelmkh** [comment]
I don’t have TestFlight on my iPhone, so hopefully don’t have an old version somehow.

**Comment by dhermanns** [comment]
I had to rename the complications. Looks like apple hasn't testet this very well and still keeps the old ones.

Seems to recycle them after a reboot (after some time ;-).

**Comment by Michaelmkh** [comment]
Thanks for the information. Appreciated.
