### ISSUE TITLE
Feature Idea: Trending trend arrows

### ISSUE THREAD

**Issue by hummelstrand** [nightscout/nightguard#25]
Can you read the last three values and display a more detailed trend arrow? Here's a quick sketch of what some of them might look like: 
![image](https://user-images.githubusercontent.com/2979793/34984640-e9059fa4-fab1-11e7-8aa1-2a2caa8ac8af.png)

The idea would be to show if this trend is quickly changing or if it is stable. I'm imagining that the existing logic could be applied with only minor modifications.

Let me know if I can be of any assistance, I could tweak and finish the arrows if you're interested.

**Comment by dhermanns** [comment]
For this the chart visualization was meant. For me you could get a fast impression of what’s going on by looking on the chart data.

**Comment by hummelstrand** [comment]
I'm often just glancing at the delta value and the trend arrow. However, since both are based on the last two values I can't see if the trend is a new one or if the change has been going on for a while. The graph just isn't detailed enough. When the sensor is a bit noisy and the values are fluctuating up and down between each 5-minute reading, I've missed that a stable trend has suddenly gone up or down. 
Just an idea that would suite my habits, I hope I've explained it well enough for you to consider.

**Comment by hummelstrand** [comment]
I just came up with another argument: Today the arrow and the delta value are  displaying the same data. If the arrow could be modified to show the last two deltas it would actually provide more information.

**Comment by dhermanns** [comment]
I think there doesn't seem to be enough interest regarding that feature. I will close it - sorry.
