### ISSUE TITLE
Badge icon shows the wrong number

### ISSUE THREAD

**Issue by Michaelmkh** [nightscout/nightguard#252]
This is probably a settings issue or a user issue, but the badge icon on my iPhone shows "7" while my actual blood sugar number is completely different (130, 150, etc.).  This started happening a couple of days ago.  I have wandered through the app trying to figure out what the "7" was or how to change it to what it used to be (my blood sugar number).  Any help would be appreciated.

**Comment by dhermanns** [comment]
Looks like it renders your values as mmol. You can force it to mgdl in your nightguard settings.

**Comment by Michaelmkh** [comment]
I think I found the problem.  The the slider for "Show BG on App Badge" (farther down the preference screen) was not turned on.  Not sure how it got turned off.  I turned it on and the correct number is displaying.  Sorry to bother you.

**Comment by dhermanns** [comment]
no Problem

**Comment by Michaelmkh** [comment]
Closing issue
