### ISSUE TITLE
Watch: Configure gauge color ranges

### ISSUE THREAD

**Issue by eichmat** [nightscout/nightguard#254]
Would be nice to be able to adjust the color ranges for green, yellow, and red text.... it always shows me red when I'm within my normal range.  The iPhone app shows green when I'm in range.

**Comment by dhermanns** [comment]
This seems to be a bug. Should be green on the complication as well. Already noticed that, too.

**Comment by eichmat** [comment]
Thanks!   Look forward to the fix.  So far, other than the crashing on WatchOS 10 that running the TestFlight copy fixed, I like what I see from Nightguard.  

I just switched over to Apple from Samsung (I know, a rare thing), and was glad I could find something similar to what I had on that other platform (though that didn't need the extra jump of Gluroo... that app pulled directly from LibreLinkUp).  But hey, it works.. thanks again!

**Comment by dhermanns** [comment]
Great to here - welcome

**Comment by dhermanns** [comment]
Latest Testflight fixed the color calculations.

**Comment by tsimmons** [comment]
TestFlight version 3.8.2 (843) seems to have reverted back to red on in-range readings.
