### ISSUE TITLE
Nightguard iPhone, iPad 

### ISSUE THREAD

**Issue by Cash59710** [nightscout/nightguard#258]
Hello, I wanted to let you know about some options that are missing after a week of use. For information, I use the Nightguard application (V3.8.1.831) with Gluroo (latest version), in an Apple environment.

What I notice on the application description and what I don't find in use :

- trend arrow (up, down, stable)
- active carbohydrates
- active insulin units
- superimposed graphs

Thank you in advance for your investment, which is invaluable.
![IMG_1132](https://github.com/nightscout/nightguard/assets/149300740/0e0f1a2b-70d0-4c70-88f1-248c49ebf22b)
![IMG_1135](https://github.com/nightscout/nightguard/assets/149300740/c28b5777-14af-49a0-bb62-2e9622a71052)
![IMG_1134](https://github.com/nightscout/nightguard/assets/149300740/f505997d-4eda-4c28-a8a8-819cb6ed8871)

**Comment by dhermanns** [comment]
Hi! Works all on my machine with the latest TestFlight (but I think had now such Problems with the latest App Store version):
![47AD7431-47D3-48D3-BD87-713339ADE4C2_4_5005_c](https://github.com/nightscout/nightguard/assets/3207317/40cb3a0e-dbaa-4a21-ab5e-5d550b58afe0)

You can try the latest TestFlight. But we had some issues with the gluroo hosted version. So maybe you should try to reproduce this with a vanilla nightscout backend.

**Comment by dhermanns** [comment]
Just checked the delta api that I`m using:
/api/v2/properties

The delta entries that are retrieved from gluroo seems to be always 0:

`{
"delta": {
"absolute": 0,
"elapsedMins": 1,
"interpolated": false,
"mean5MinsAgo": 83,`

It should look like

`
"delta": {
"absolute": -23,
"elapsedMins": 4.998083333333334,
"interpolated": false,
"mean5MinsAgo": 226,
`

So it should be something in your setup and/or gluroo.

**Comment by Cash59710** [comment]
Hello,

Thank you for your quick feedback.

I'm going to try it all out, thanks again for your very clear instructions.

Have a nice Sunday

**Comment by Cash59710** [comment]
Re, I need a developer code to use the latest TestFlight

And if I've understood vanilla Nightscout correctly, it's all about :
Reproduce with a vanilla Nightscout backend: the same scenario, but using a
"vanilla" Nightscout backend, i.e. a basic unmodified version of
Nightscout. Where can I find the unmodified version? If you have the time,
I'll look for it, thanks. I'll also pass the information on to Gluroo.
Thank you very much. Have a nice day! Traduit avec DeepL (
https://www.deepl.com/app/?utm_source=ios&utm_medium=app&utm_campaign=share-translation
)
