### ISSUE TITLE
Apple Watch complication / Smart stack empty

### ISSUE THREAD

**Issue by jonathanbertholet** [nightscout/nightguard#259]
Hi there,

I just discovered & installed the app on my iphone & apple watch series 9, both running the latest public OS versions (10.1 and 17.1). 

Everything works fine, except that the app is not displaying the graph on both iphone and apple watch. 

Thank you!

![Screenshot 2023-10-29 at 19 49 05](https://github.com/nightscout/nightguard/assets/59562971/8863255d-1811-4e62-bfd6-8840be102e92)

![incoming-49E8714D-593F-4623-94CB-473C560988E3](https://github.com/nightscout/nightguard/assets/59562971/e277306e-7d47-4632-967a-da8a385e37bd)

**Comment by dhermanns** [comment]
Please use the search before opening issues. This should be due to a missing or incorrect token for your nightscout backend.
