### ISSUE TITLE
Complication not showing up in the IOS Watch App when using the modular watch face

### ISSUE THREAD

**Issue by mommymommymommy** [nightscout/nightguard#26]
Hello -

I have downloaded the test flight version of the app, the complication shows up under "complications" but does not appear as an option for the modular watch face. Have I missed a step?

Thanks,

Steph

**Comment by dhermanns** [comment]
![3e47e58e-96e4-457a-aed1-ccea8b84bbf3](https://user-images.githubusercontent.com/3207317/35172860-9fd9dccc-fd69-11e7-9372-6d4d91ab10f5.png)
 
I‘m using this modular face and it shows up.

**Comment by mommymommymommy** [comment]
It showed up as an option in the previous iteration but not since the last update.

**Comment by dhermanns** [comment]
My screenshot is from the current TestFlight build. So you should try build
1.5.1.145
mommymommymommy <notifications@github.com> schrieb am Sa. 20. Jan. 2018 um
15:31:

> It showed up as an option in the previous iteration but not since the last
> update.
>
> Sent from my iPhone
>

**Comment by Tjerkhv** [comment]
Same issue here, in the Apple Watch app the nightguard complication shows up. But when I want to add it to a watch face, nightguard does not show up.

The nightguard app on the phone and watch work correctly when I open them regularly, they show the current nightscout data.

**Comment by dhermanns** [comment]
So what have you both in common? What Version are you using? I think I should release the current Build, since at least on my watch it’s working fine ;-)

**Comment by Tjerkhv** [comment]
I’m using the following:
Nightscout 0.10.2-release20171201
Nightguard V1.5.0.131
IOS 11.2.2
WatchOS 4.2

If there is a way to test a beta build, just let me know.

**Comment by dhermanns** [comment]
Yes - I can add your email to the list of beta testers.
Tjerkhv <notifications@github.com> schrieb am So. 21. Jan. 2018 um 00:30:

**Comment by Tjerkhv** [comment]
Sure... It’s in my profile

**Comment by dhermanns** [comment]
I added you. Let me know whether its solved with it.

**Comment by dhermanns** [comment]
As Tjerkhv pointed out: There seems to be a bug in the watch iOS app: You can't select the nightguard complication there. At least this is the problem on my iPhone, too.

The workaround is to select the complication directly on the phone. That works for me.
Hope this helps...

**Comment by dhermanns** [comment]
Did the workaround to select the complication directly on the watch work for you?

**Comment by Tjerkhv** [comment]
Yes, that worked. The conplication showed the correct data all day.I’ve googled a bit on the complication issue, I’ve found some posts on redit and stachoverflow, but no hint of a couse or a solution.
Cheers,
Tjerk


Verzonden van Yahoo Mail voor iPhone


Op maandag, januari 22, 2018, 8:10 PM, dhermanns <notifications@github.com> schreef:


Did the workaround to select the complication directly on the watch work for you?

**Comment by dhermanns** [comment]
Great - good to hear ;-)
Tjerkhv <notifications@github.com> schrieb am Di. 23. Jan. 2018 um 20:59:

**Comment by mommymommymommy** [comment]
The workaround didn’t work for me.

**Comment by dhermanns** [comment]
I don't think that I can do much more for it. Looks like an apple bug to me. Feel free to reopen if it turns out that we can do more about it.
