### ISSUE TITLE
documentation for complication colors ?

### ISSUE THREAD

**Issue by lsandini** [nightscout/nightguard#260]
I can't remember when this exaclty happened, and was it after an iOS or Nightguard update? I have an issue about the colors of the BG value and circle around it in the complication. Here the circle and the value 6.2 were both red. Tapping the complication opens the main app where the curve and 6.2 mmol/l values are green. Back to the mains watch face now the 6.2 mmol/l value is red and the circle is red.

Is there any explanation or setting for defining the BG zones for which the color is green, red, white or yellow ? This used to work well right out of the box, but suddenly I find no logic at all anymore.

![iOS 9.6.3.](https://lh3.googleusercontent.com/pw/ADCreHdjryLEJ3o6KLNgN4L1U3SU7PZqF6tdLbb43l7nn4-iXgDoQbZuno1sD_FYxVioBG3kvuGXoR2Zcm_ao2zhs8UoWz933BQjJyfQUASXD9ll1z5NkEWrACpUPwzp9c0S7SEcmqWWUFNUrff23Oighrk0M4HCVB1pGX7BMfBnMBhhf6jiNnzX4CmXaCc0bwNi41V6gBeZ4Bs6pCNBIw0QCegi_pOWJ_Ak7zBmPKgkluURsqN8XBJ9LoSbpjraLwCwygszTWsk143FI35jBmyFtdJKhqWXV5I6raUlx2CB-Gvy4MEQjOSo4olsZREXzG5AC_MqwnsXA_RApspQmN683UFJ5ZXQM2IyvkSlTtN9kTFGSPtk2JwzUjluzBL-FkvBJlIX1xuO1yypSpqSdEKYnJgncYMrtrvQfRdrLeLrtiUVhB8utZ-ZeU577R2CkFh1QvoJRJzK2N5pdzC84C1nvHkuPqc7W0DIxIYK6ITgwC_KZZUu6a2gwDhMmVfMAJGFw9nXzCwtmXq7bOVIo96jML536MChJpegW-hs8jelY72sS1gTFGnRanDvxN029yBUsbp8GCGyZ8t2-R0nRJHnv7oSf3bhgLfvHUk5JGXReWewf7HlYt6rC3jaBaH6oELSrkKgxqadgWkSgDXSB9yds3-sS00AIZkh6HqyIC1zcfPgTdxRRHgxcv7hkv11WWJPkUsyBHejGRofNBVQrgLI0Y88sEtfOwo7noOF0EWstPQoPKkKI_1E7xRACkHOXrjghWwNu0yl-BiqVvYONZ2YRSV7PcKJ2_kiUxZFK3Vite_juW1zw1iHxqLpULHy0PGXtGCWVGyRq77I9rDbVR7k708UK-RgPIsVsIJntb59ASGbuYUZZiauNBUEI2qDnk0IsVD8PH_uCE3IdNsGFzYDqQVep2U=w368-h448-s-no-gm?authuser=0)

**Comment by dhermanns** [comment]
This is not configurable, but already fixed within the latest TestFlight Version.

**Comment by lsandini** [comment]
Thank you, excellent !
