### ISSUE TITLE
Yesterday's BGs no longer show.

### ISSUE THREAD

**Issue by bgga12** [nightscout/nightguard#266]
Hi - I had the day over day graphs showing for a while and suddenly the previous day's trend line stopped showing, even when the button is switched on in preferences. Any ideas? 

UPDATE: it shows the previous day's BG values from what appears to be an 8 hour window, usually in the evening only from 16:00 - 24:00.

Also, the stats area only shows the last day selected, even if all are 5 days are selected to show. Not sure if this is related.

V3.9.0.867
iPhone 13
iOS 17.2

Thank you for any assistance.

**Comment by dhermanns** [comment]
No - not really. But your current version is much behind the Testflight. You could try the beta:

https://testflight.apple.com/join/Ub8WcpcE

**Comment by bgga12** [comment]
Same with the beta - just tried it.
V3.9.0.851

**Comment by bgga12** [comment]
I could add that if I remove the app, then reinstall, then the previous day's data shows up for just a few milliseconds with the gray trend line, then it disappears again.

**Comment by dhermanns** [comment]
How do you upload your data. What is your Sensor? A bit more background could be helpful.

**Comment by bgga12** [comment]
> How do you upload your data. What is your Sensor? A bit more background could be helpful.

I use glooroo connect with the nightscout url and a librelink 2 cgm.
