### ISSUE TITLE
Nightguard cannot be build because files are missing

### ISSUE THREAD

**Issue by Joerg-Schoemer** [nightscout/nightguard#267]
Pods.xcodeproj missing in workspace
Content of Products missing
Folder Pods missing

<img width="417" alt="Bildschirmfoto 2023-11-30 um 16 36 43" src="https://github.com/nightscout/nightguard/assets/8568035/b571449f-d4f9-4280-b408-8aa7efe7d79e">

I've made a clean clone of nightguard and opened Xcode within the fresh folder.

**Comment by dhermanns** [comment]
I see. Fixing this...

**Comment by poml88** [comment]
Excellent. Thanks for fixing the Podfile. And thanks for updating the README, it will help people.
Could you also fix the string files:
Build input files cannot be found: '/Users/dirk/workspace/nightguard/nightguard/fi-FI.lproj/Duration.strings', '/Users/dirk/workspace/nightguard/nightguard/de.lproj/Duration.strings', '/Users/dirk/workspace/nightguard/nightguard/Base.lproj/Duration.storyboard'?
And for the README it could be usefule to mention in what files the group profile needs to be changed.
It seems not worthwhile to do a pull request for this...
Thanks!

**Comment by dhermanns** [comment]
I didn't get these errors. So not quite sure what you ment. Feel free to provide a PR for it.

**Comment by poml88** [comment]
Yes, I guess, because you are Dirk. :-)
It is easy: Open the workspace and go to nightguard - rescources - Duration.storyboard. In the file inspector you will see that the location is set to "absolute path". "Users/Dirk/..."
It is a bit complicated to make a PR for that, because it is a xcode configuratin detail.

**Comment by Joerg-Schoemer** [comment]
Hi Dirk,
can you add a developer hint to request critical alert permissions from apple.
Kind regards,
Jörg

**Comment by Joerg-Schoemer** [comment]
The Duration.storyboard points to “/Users/dirk/workspace/nightguard/nightguard/Duration.storyboard” and thus results in a missing file in the project.

<img width="332" alt="Bildschirmfoto 2023-12-04 um 16 45 12" src="https://github.com/nightscout/nightguard/assets/8568035/e7fb3070-61fd-4b3b-a9d9-8ea343f5556f">

**Comment by dhermanns** [comment]
Added this one:
https://github.com/nightscout/nightguard/commit/6d6b62851ada5bbae8af651c1f86307ec3c3c8ae

**Comment by poml88** [comment]
Thanks to both of you for fixing these issues. Still waiting for the critical notification entitlement from Apple. Meanwhile having fun with the testflight build!

**Comment by dhermanns** [comment]
> Thanks to both of you for fixing these issues. Still waiting for the critical notification entitlement from Apple. Meanwhile having fun with the testflight build!

Have a look at the readme.md if you don't want to wait.
