### ISSUE TITLE
Unexpected switch to the Apple Watch Face

### ISSUE THREAD

**Issue by dhermanns** [nightscout/nightguard#27]
We should distinguish this in contrast to the real app crashes reported by issue24.
My hope was that that could be fixed by issue24, but it seems like this is something different.

**Comment by hummelstrand** [comment]
Build 150 installed fine on both iPhone SE and 38 mm Series 2. It still unloads and goes back to the watch face, it has happened two times in three hours of use so far. The info screen says it's currently has 120/286 cached values.

**Comment by dhermanns** [comment]
So that looks fine. Crazy that there have been these install problems.

**Comment by hummelstrand** [comment]
After running build 150 on 38 mm Series 2 for 24 hours, it keeps unloading itself constantly. I'm estimating that it has unloaded itself 50% of the times I raise the watch to look at it. If it is still loaded, I always have to wait for a few seconds before all the values (except the _x min_ data) are updated and shown correctly, if that may be a clue (perhaps that's by design?)

**Comment by dhermanns** [comment]
Yes - the delay is designed by Apple for maximum battery guarding :-/.

I had another idea. Did you try to set just your watch to airplane mode? This would be a test to be sure that no other installed app can interfere.

If the watch app still leaves foremost state, you could try to enable the airplane mode on the watch, too. 

I‘m curious whether that gives us some more insights.

**Comment by hummelstrand** [comment]
I'll test with the watch in Airplane Mode today. 
I still think a stripped version of the watch app would be a good idea.

**Comment by dhermanns** [comment]
Yes - we can try that, too.
Jonas Hummelstrand <notifications@github.com> schrieb am Do. 25. Jan. 2018
um 07:14:

**Comment by hummelstrand** [comment]
I've been running the watch in Airplane Mode the last six hours, and nightguard has not managed to stay in front more than it seemed to do when it was connected.

**Comment by dhermanns** [comment]
Ok - so no new insights here. I will build a stripped version next.
Jonas Hummelstrand <notifications@github.com> schrieb am Do. 25. Jan. 2018
um 14:59:

**Comment by NightscoutLS** [comment]
I'm also still experiencing the intermittent unloading of the Nightguard watchface. Would be happy to do any tests. I have a 42mm Series 1. Thanks

**Comment by hummelstrand** [comment]
Hi, thanks for the stripped build 151. I've been running it since you released it and I'm afraid it still unloads. It seems to be with the same frequency as the full version, but I haven't kept a written log. 187/287 cached values right now.

**Comment by hummelstrand** [comment]
I could try to strip everything from the Watch and see if that helps, but I don’t have a spare iOS phone that I can wipe clean.

**Comment by dhermanns** [comment]
I think that the problem really seems to arise outside of the app. We had another user (Debbie) who switched to a clean iPhone and the issue stopped there using the same watch and the same version of the nightguard app.

**Comment by hummelstrand** [comment]
I'm now uninstalling app by app to see if I can notice any improvements. I'm down to a single watch face and only six installed apps.

**Comment by hummelstrand** [comment]
v1.5.1.150: I'm now down to one Face ("Simple") without the Activity complication (I thought that it might want to update the complication and therefore switch back to the watch face) and only three apps installed (nightguard, Pushover and Workflow). 164/286 cached values.
The watch still switches back to the watch face very frequently. I'll post if there's any change.

**Comment by dhermanns** [comment]
But sounds like it’s more a setting on the phone :-/
Jonas Hummelstrand <notifications@github.com> schrieb am Mi. 7. Feb. 2018
um 13:51:

**Comment by hummelstrand** [comment]
I'd love to help you isolate this further, but I don't really have time to wipe my phone and start from scratch. I'll just wait and see how the problem develops, it's not really a big deal to have to switch back to nightguard...

**Comment by dhermanns** [comment]
Ok. But just a few user seem to have this. So I would expect not much
progress here ...
Jonas Hummelstrand <notifications@github.com> schrieb am Do. 8. Feb. 2018
um 11:54:

**Comment by dhermanns** [comment]
V2.0.0 and Florians Background Updates should ease the problem hopefully a bit. Feel free to reopen if we have new insights here.
