### ISSUE TITLE
Question mark on Apple Watch complication

### ISSUE THREAD

**Issue by Pensiondude** [nightscout/nightguard#271]
App was working great until today.  I can no longer view the BG level on the Apple watch 9 complication.  I can view the level if I press the question mark on the complication.  How do I fix?  Thank you.

**Comment by Pensiondude** [comment]
It looks like this may be due to a recent release.

**Comment by dhermanns** [comment]
Yes, it is. Complications still don't update very often. If they have no data, a question mark is displayed.

I noticed that Apple learns how valuable the app is to you. If you use it frequently, suddenly you get more update budget.

For me after a day, updates suddenly reappear. As noted in the release notes, I'm still trying to improve this.

Do you have a lock screen nightguard widget installed?

**Comment by flieger42** [comment]
I also have problems on the Apple Watch since the last update of Nightscout to V3.9.0.876. The widget only shows three groups of three dashes side by side. And both complications show now valid data. The gauge only shows questionmarks and the text complication shows a value of 2838…

**Comment by dhermanns** [comment]
Can you change the alarm ranges from the iOS Part and do they change on the watch? If not try reinstalling. This happened to me sometimes, too. Seems to me like an watchOS Bug.

**Comment by flieger42** [comment]
> I also have problems on the Apple Watch since the last update of Nightscout to V3.9.0.876. The widget only shows three groups of three dashes side by side. And both complications show no valid data. The gauge only shows questionmarks and the text complication shows a value of 2838…
> 
> the app looks OK. Also app and widget on iPhone.

Now, one day later complications and widget in watch are OK. Without any doing from my side.

**Comment by dhermanns** [comment]
Yes - that is what I noticed too. Would be interesting if someone finds out what circumstances have an influence on the update behavior.

**Comment by GUY2242** [comment]
Mine is still off after 2 days just shows ?? and no numbers . have tried everything i can think of to put it right but no . I even uninstalled and re installed but still not working .

**Comment by jetcrabs** [comment]
Same issue. On 3 Apple Watches, 5,6 ultra2 after NG update. Random time when values as text and question tags when as Gauge. I removed the apps. It took a while. I changed the ranges at least a few times. Also changed  many other setup and suddenly appeared the volume of BG on the facewatch but still remains the same value. Even after refreshing. When the ultra 2 switched to night mode with a different face, the question marks appeared and also remained on the current face watch again.

**Comment by GUY2242** [comment]
I Think they are working on a fix . Mine did the same jetcrabs it went to 11.5 for over a day but wouldnt change to the right value then restarted watch and back to ? marks . Still like that .

**Comment by dhermanns** [comment]
Have you been on the testflight version before? What I noticed is that all nightguard complications are duplicated when selecting them on the watch. As if the app is installed twice.

Maybe I build a new TestFlight and see if that changes something.

**Comment by Evs-nazgul** [comment]
I noticed the same the same issue,  before I used an older nightgaurd version, then the update was pushed on the iphone, and also on Iwatch 7. Suddenly all data numbers disappeared from the complications.  When I touch the ?? or --- nightguard opens and shows all values. I'm 4 days later now, still no indications in gauges. Changing the faceplate did not change anything.  We probably need to expect an update??

**Comment by dhermanns** [comment]
Did you have duplicated nightguard complications when selecting them on the watch? Did you had testflight installed before?

**Comment by GUY2242** [comment]
mine has just started to work again . techs even working on christmas day . Thank you who ever you are .

**Comment by Evs-nazgul** [comment]
Yes I tried flightcase and it worked fine for some days.Then suddenly, even with flightcase, I got ??And —-, so I reverted to the version before the flightcase version being 875.Now it remains, for the moment at ?? And —-.The double complications did not gave an issue. I just tried to see the graph and have the gauge value.Needed to refresh sometimes both complications separartely.If one if the colplications would work it would be nice , as now no data is given, except when tapping on it.Thank you anywayErwinOp 25 dec 2023 om 15:32 heeft dhermanns ***@***.***> het volgende geschreven:﻿
Did you have duplicated nightguard complications when selecting them on the watch? Did you had testflight installed before?

**Comment by Evs-nazgul** [comment]
I sent in some feedback on the most reecent flightcase test version.Just installed, to have a valuable feedback, so far, no change in displaying data in compilations in my case.Op 25 dec 2023 om 18:44 heeft Erwin Van Steenacker ***@***.***> het volgende geschreven:﻿Yes I tried flightcase and it worked fine for some days.Then suddenly, even with flightcase, I got ??And —-, so I reverted to the version before the flightcase version being 875.Now it remains, for the moment at ?? And —-.The double complications did not gave an issue. I just tried to see the graph and have the gauge value.Needed to refresh sometimes both complications separartely.If one if the colplications would work it would be nice , as now no data is given, except when tapping on it.Thank you anywayErwinOp 25 dec 2023 om 15:32 heeft dhermanns ***@***.***> het volgende geschreven:﻿
Did you have duplicated nightguard complications when selecting them on the watch? Did you had testflight installed before?

**Comment by Evs-nazgul** [comment]
I just tested the previous flightcases and added screenshots of the tested version and it’s result on my Applewatch 7.Final version 3.9.1Maybe this helps to track backKind regardsErwinOp 25 dec 2023 om 20:21 heeft Erwin Van Steenacker ***@***.***> het volgende geschreven:﻿I sent in some feedback on the most reecent flightcase test version.Just installed, to have a valuable feedback, so far, no change in displaying data in compilations in my case.<image0.jpeg>Op 25 dec 2023 om 18:44 heeft Erwin Van Steenacker ***@***.***> het volgende geschreven:﻿Yes I tried flightcase and it worked fine for some days.Then suddenly, even with flightcase, I got ??And —-, so I reverted to the version before the flightcase version being 875.Now it remains, for the moment at ?? And —-.The double complications did not gave an issue. I just tried to see the graph and have the gauge value.Needed to refresh sometimes both complications separartely.If one if the colplications would work it would be nice , as now no data is given, except when tapping on it.Thank you anywayErwinOp 25 dec 2023 om 15:32 heeft dhermanns ***@***.***> het volgende geschreven:﻿
Did you have duplicated nightguard complications when selecting them on the watch? Did you had testflight installed before?

**Comment by Evs-nazgul** [comment]
Now, after changing so many times, suddenly on re-installing the last version of flight testcase, all values are shown on complicationsJust for your infoErwinOp 25 dec 2023 om 20:21 heeft Erwin Van Steenacker ***@***.***> het volgende geschreven:﻿I sent in some feedback on the most reecent flightcase test version.Just installed, to have a valuable feedback, so far, no change in displaying data in compilations in my case.<image0.jpeg>Op 25 dec 2023 om 18:44 heeft Erwin Van Steenacker ***@***.***> het volgende geschreven:﻿Yes I tried flightcase and it worked fine for some days.Then suddenly, even with flightcase, I got ??And —-, so I reverted to the version before the flightcase version being 875.Now it remains, for the moment at ?? And —-.The double complications did not gave an issue. I just tried to see the graph and have the gauge value.Needed to refresh sometimes both complications separartely.If one if the colplications would work it would be nice , as now no data is given, except when tapping on it.Thank you anywayErwinOp 25 dec 2023 om 15:32 heeft dhermanns ***@***.***> het volgende geschreven:﻿
Did you have duplicated nightguard complications when selecting them on the watch? Did you had testflight installed before?

**Comment by Evs-nazgul** [comment]
Next problem now, values are shown, but nightguard app does not open anymore nor can be refreshed.ErwinOp 25 dec 2023 om 22:10 heeft Erwin Van Steenacker ***@***.***> het volgende geschreven:﻿Now, after changing so many times, suddenly on re-installing the last version of flight testcase, all values are shown on complications<image0.jpeg><image1.jpeg>Just for your infoErwinOp 25 dec 2023 om 20:21 heeft Erwin Van Steenacker ***@***.***> het volgende geschreven:﻿I sent in some feedback on the most reecent flightcase test version.Just installed, to have a valuable feedback, so far, no change in displaying data in compilations in my case.<image0.jpeg>Op 25 dec 2023 om 18:44 heeft Erwin Van Steenacker ***@***.***> het volgende geschreven:﻿Yes I tried flightcase and it worked fine for some days.Then suddenly, even with flightcase, I got ??And —-, so I reverted to the version before the flightcase version being 875.Now it remains, for the moment at ?? And —-.The double complications did not gave an issue. I just tried to see the graph and have the gauge value.Needed to refresh sometimes both complications separartely.If one if the colplications would work it would be nice , as now no data is given, except when tapping on it.Thank you anywayErwinOp 25 dec 2023 om 15:32 heeft dhermanns ***@***.***> het volgende geschreven:﻿
Did you have duplicated nightguard complications when selecting them on the watch? Did you had testflight installed before?

**Comment by brianlee0523** [comment]
> App was working great until today. I can no longer view the BG level on the Apple watch 9 complication. I can view the level if I press the question mark on the complication. How do I fix? Thank you.

**Comment by brianlee0523** [comment]
Any fix for this?

**Comment by dhermanns** [comment]
You can try the latest TestFlight. Works better for me. But still not perfect.

**Comment by brianlee0523** [comment]
Can you advise what to download? Please and thanks.

Brian L. Smith, AAI, FSCP®, LUTCF®
770-851-8173

**Comment by brianlee0523** [comment]
I got glucose direct, but how to install on watch?

Brian L. Smith, AAI, FSCP®, LUTCF®
770-851-8173

**Comment by dhermanns** [comment]
Latest Testflight is here:

https://testflight.apple.com/join/Ub8WcpcE

**Comment by brianlee0523** [comment]
Thank you

Brian L. Smith, AAI, FSCP®, LUTCF®
770-851-8173

**Comment by Evs-nazgul** [comment]
Hello,Thank for the several new test flight versions.I tried them all, none of them provide me a visual feedback on my iwatch 7, except form the older version 3.9.0.851.This version provides me data in the complications circular ad gauge and rectangular as text.From time to time the data disappears and becomes the ?? Or —-. Or even nothing at all (although the rectangular complication is active)Picture from newest test flight version 3.9.1.882Can it be a setting on my iphone and/or iwatch? As it worked fine until the last update has been launched?Many thanks in advance as the app is great and helps a lotErwinOp 28 dec 2023 om 18:29 heeft dhermanns ***@***.***> het volgende geschreven:﻿
Latest Testflight is here:
https://testflight.apple.com/join/Ub8WcpcE

**Comment by dhermanns** [comment]
Still experimenting with it. The last TestFlight version worked fine for me for a day. Then suddenly stopped. I will drill this further down.

**Comment by brianlee0523** [comment]
Thank you please keep us posted!

Brian L. Smith, AAI, FSCP®, LUTCF®
770-851-8173

**Comment by Evs-nazgul** [comment]
Hello,Just for your info …No idea what happened nor why, but all of a sudden, the latest test flight 3.9.1.882. Shows data on my iwatchWander how long it will take. Keeping you posted.Small next question, causing possibly a lot of (great) work: would it be possible to have the graph in future in the rectangular complication, as it is really nice to predict the trend.Enjoy your year end and happy and healthy 2024ErwinOp 31 dec 2023 om 18:06 heeft dhermanns ***@***.***> het volgende geschreven:﻿
Still experimenting with it. The last TestFlight version worked fine for me for a day. Then suddenly stopped. I will drill this further down.

**Comment by dhermanns** [comment]
Latest TestFlight works fine for me now: For 24h every 10 to 20 minutes updates on the watch complication. That is what is promised by apple. So looks great on my watch.

**Comment by Evs-nazgul** [comment]
Indeed, also installed to check it out. Whole day long updates with some delay, nevertheless data is shown and usable.Looking forward to other improvements.ErwinOp 1 jan 2024 om 17:39 heeft dhermanns ***@***.***> het volgende geschreven:﻿
Latest TestFlight works fine for me now: For 24h every 10 to 20 minutes updates on the watch complication. That is what is promised by apple. So looks great on my watch.

**Comment by Fakhori** [comment]
Still have the question marks here on Apple Watch 6. App works fine. Is there any way to push the notification updates to less than 10-20min?

**Comment by dhermanns** [comment]
Are you using the Infograph Watchface? For me, all other warchfaces are working fine, but this one.

Feels like a watchos bug to me. Its the same code running. Just the face is different.

And no: No possibility to get more than 75 Updates a day. Ask apple to increase this. At least for medical applications 😉.

But for me, every 10-20min ist fine to get a fast Impression how things are going.

**Comment by dhermanns** [comment]
V3.9.1 is out on the Appstore now.
