### ISSUE TITLE
Cryptic value in watch complication

### ISSUE THREAD

**Issue by gemueselasagne** [nightscout/nightguard#272]
Just installed Nightguard on my moms watch (having the readings on her watch makes things so much easier for her. She asked me to say thank you ;-)). 

I couldn't figure out what the circled values indicate. It looks like a timestamp but it doesn't match up with the time of the latest reading or anything else. 
I couldn't find any documentation on that.

Can someone help?

**Comment by dhermanns** [comment]
Happy to hear that ;-). What circled values do you mean? Do you have a screenshot?

**Comment by gemueselasagne** [comment]
Here you go 😃 
Forgot to upload...

![image](https://github.com/nightscout/nightguard/assets/10177993/f2c0b95a-d589-492f-a083-3b63222c2052)

**Comment by dhermanns** [comment]
Yes - thats the timestamp. But right now we have a problem with the complication update. Are working on it to improve...

**Comment by gemueselasagne** [comment]
I see! Thanks for looking into it :) 🙏🙏

**Comment by dhermanns** [comment]
More in #271
