### ISSUE TITLE
NIghtguard defaults to 'snoozed for 1min' and so no alarms?

### ISSUE THREAD

**Issue by bmcnightscout** [nightscout/nightguard#275]
Hi there. New user so may be my mistake. I have the alarms configured, alert notifications set on and background app refresh also on for Nightguard

The problem is that 'Snoozed for 1min' seems to be default on when I am not using the App, so when a low/high event happens I don't get alarms unless I am in the app. I can turn the snooze off, but as soon as I exit the app and go back in, it resets to 'Snoozed for 1min'.

Am I doing something wrong is my expectation that I would get alarms when not actively in the app wrong (seem's kind of pointless...)

Using iPhone 14 Pro

**Comment by bmcnightscout** [comment]
See [video ](https://1drv.ms/v/s!Ai-MCDSJ72gIhrcuCkiP1_UgnJXV6Q?e=FobfSy)

**Comment by dhermanns** [comment]
Hi! The 1min snooze ist just activated when you open the app. Otherwise you could get an immediate alert which could be disturbing.

Read about background updates in the issues here. If the app isn't in foreground this is limited basically to new values every 10-20 minutes. And therefore push notifications with alerts every 10-20 minutes, too.

So for the night, keep the app in foreground to get immediate alerts.

**Comment by bmcnightscout** [comment]
Thanks for the reply, so if I understand what you're saying:

- If the app is open and in foreground it will prevent the phone auto-lock and alerts will sound aligned with the time of the low/high event (so this would essentially be nighttime/sleep mode)
- If the app is in background, the alert won't sound at the time of the event, but there will be a push notification 10-20 minutes later to indicate the alarm was triggered

Correct?

As an aside, we're coming from dexcom/dexcom follow to a new setup (new pump). What prevents something like Nightguard doing the immediate alerts when the app is in background, as Dexcom does?   (not a criticism, the app is great, just curious :) )

**Comment by dhermanns** [comment]
I don't know what dexcom does. Would assume they are sending immediate push notifications. For this to be possible, your backend would need a Apple qualification for it, that you don't have.

So nightguard can only send local notifications, which are limited from apple to 75 a day.

**Comment by bmcnightscout** [comment]
Makes sense. Last question - would the push notifications be limited by having nightguard hitting the same nightscout app on 2 devices? My wife and I have it on both our phones, set up exactly the same and while she got a push notification for a high alert that occurred earlier today, I didn't?

**Comment by dhermanns** [comment]
On every device, you have your own limits. Apple times the pushes depending on your behavior and app usage.

What is very important is: Add the nightguard widget to your lock screen. That will improve your update behavior.

**Comment by bmcnightscout** [comment]
Thanks again, I have done that (very useful) and we left the nightguard in foreground mode and it worked perfectly last night. I am still  a little confused by the push notification. See this example - BGL was in range at the time (see lock screen) and not sure what this push is trying to say . My wife - who is using night guard on her iOS device with apparently all the same settings - is not getting these. They've been appearing every 30 minute or so for me - they seem to be showing the variance between readings? We haven't had a low BGL event for 24 hours, and the last high was 12 hours.

![20240108_022953000_iOS](https://github.com/nightscout/nightguard/assets/31397983/b210bcfa-0098-4f88-9b12-565c1baa00d3)

**Comment by dhermanns** [comment]
Have a look at #274 and try the TestFlight version. Looks like a bug to me in the current release.

**Comment by bmcnightscout** [comment]
OK, I'll give TestFlight  a go. For info, seems to be mostly coming up with 0.3, but have also seen 0.1, 0.2 and 0.4

**Comment by bmcnightscout** [comment]
Still getting the notifications on the testflight version, although its changed from mostly being 0.3 to now 0.4

**Comment by dhermanns** [comment]
Is it still the delta of the two latest bg values?

**Comment by bmcnightscout** [comment]
Actually, last few have been 0.3 again. I don't think it is the delta, the last couple of hours most changes have been 0, 0.1, 0.2 so that must have been a coincidence.

**Comment by dhermanns** [comment]
Interesting - maybe a wrong mmol to mgdl conversion then. Closing this in favor of #275.
