### ISSUE TITLE
Trend arrows and time and background in complications / widgets

### ISSUE THREAD

**Issue by poml88** [nightscout/nightguard#277]
I saw from #215 that trend arrows were implemented at some point. What happened to the trend arrows? Was this dumped?

It is, of course, very useful to show the time in the complication when it was updated. I know from iOS widgets, that it is possible to have a running minute:second timer in a widget, that is counting every second, without the widget being updated. Means, that instead of the time, there could be an increasing timer in the widget showing how many minutes:seconds ago it was updated. Would that make people's life easier? No need to calculate the time difference.

Also, it is possible in some apps to have a widget with a blurred background, which makes the values easier to read in case you have for example a photo as screen background. Could that be implemented?

**Comment by dhermanns** [comment]
Trend arrows are right now dumped in favor of more background updates, yes.

I don't think that active timers or the like are possible for custom complications. Do you have code examples for that?

**Comment by poml88** [comment]
Hi, ok, that is interesting. What is the connection between trend arrows and more background updates? The arrow plus the value, it is the same update, isn't it?

I will look for code. But since nightguard also has phone widgets, it could be implemented there...

**Comment by dhermanns** [comment]
I'm using the entries endpoint from nightscout to do the background updates.

And this endpoint doesn't provide the trend arrows.

Code for the widgets would help, too. Yes.

**Comment by poml88** [comment]
Oh, I see thanks. I do not know the code in such detail. 
However, I would like to mention, that the trend arrow is about the most useful thing the CGMs have to offer. THE FSL3 one is really good. It is a pity we are missing out on them.
But in principle the background updates are an Apple algorithm, so it should not change whereever the data is taken from?

**Comment by dhermanns** [comment]
It measures the compute time consumed. So you should return as soon as
possible and do as little as possible network traffic.

I believe the newer nightscout api V3 has an endpoint that provides the
state plus multiple bg entries. Maybe this is the way to go. But quite some
effort to switch to it.

Phil ***@***.***> schrieb am Mi. 10. Jan. 2024 um 16:43:

**Comment by poml88** [comment]
Ok, so the less battery you use the more updates you get.

could you point me to the line of code where you do the updates, pls?

**Comment by dhermanns** [comment]
Its in the TimelineProvider

**Comment by dhermanns** [comment]
V3.9.1 is out on the Appstore now.

**Comment by poml88** [comment]
Thanks, 3.9.1 is working great on my watch. But I still would like to provide some code samples for trend arrows, timers, and blurred background...

**Comment by poml88** [comment]
Ok, actually for a lock screen widget a timer is very simple, just add this:
```
Text(Date(), style: .timer)
                         .font(.system(size: 20, weight: .heavy))
                         .foregroundColor(color.1)
                         .multilineTextAlignment(.center)
                         .monospacedDigit()
                         .padding(4)
```

**Comment by poml88** [comment]
Hm... and for the arrow, in the TimeLineProvider, there is a bgdeltaArrow? But it is not read?

```
private func convertToTimelineEntry(_ data: NightscoutData, _ bgValues: [BgEntry], _ errorMessage: String) -> NightscoutDataEntry {
        
        return NightscoutDataEntry(
            date: Date(timeIntervalSince1970: data.time.doubleValue / 1000),
            sgv: UnitsConverter.mgdlToDisplayUnits(data.sgv),
            sgvColor: UIColorChanger.getBgColor(data.sgv),
            bgdeltaString: UnitsConverter.mgdlToDisplayUnitsWithSign(data.bgdeltaString),
            bgdeltaColor: UIColorChanger.getDeltaLabelColor(data.bgdelta),
            bgdeltaArrow: data.bgdeltaArrow,
```

**Comment by poml88** [comment]
Ah, and the blurred background can be achieved with:
`AccessoryWidgetBackground()`

**Comment by dhermanns** [comment]
Hi Phil. Great hints. The bgdeltaArrow isn't updated and therefore not displayed right now.

If you can get the timer working, PR is appreciated.

**Comment by poml88** [comment]
I did set up a build enviroment. I built the latest version and am waiting if I can get the testflight vor external testing reviewed. Then I can play a bit. I have a few more questions, I will ask in another place.

**Comment by poml88** [comment]
Ok, Thanks for the bgdeltaArrow advice. I am planning to make some FSL3 optimized version of NG, maybe just one configuration switch "FSL3 yes/no" or so.

**Comment by dhermanns** [comment]
If you wan’t to add minute based updates, I would prefere preference
switches for each feature. Like “Check for updates any minute (yes/no)”.

Because I would expect more and more sensors will switch to more recent
updates.

Phil ***@***.***> schrieb am So. 31. März 2024 um 22:28:

**Comment by poml88** [comment]
Sorry to come back to this, but does the entries v1 api not deliver the "direction"?

```
[
  {
    "type": "string",
    "dateString": "string",
    "date": 0,
    "sgv": 0,
    "direction": "string",
    "noise": 0,
    "filtered": 0,
    "unfiltered": 0,
    "rssi": 0
  }
]
```

**Comment by poml88** [comment]
So, if I get some entries via `https://nightscout.cmdline.net/api/v1/entries.json` then it does provide the arrow, does it not?

`{"_id":"660aa97cfae3e1519455056f","type":"sgv","sgv":108,"direction":"Flat","device":"nightscout-librelink-up","date":1711974755000,"dateString":"2024-04-01T12:32:35.000Z","utcOffset":0,"sysTime":"2024-04-01T12:32:35.000Z","mills":1711974755000}`

**Comment by dhermanns** [comment]
Yes - the api provides this. The problem was that my internal NightscoutService wasn't designed to retrieve the direction in the method readChartDataWithinPeriodOfTime. 

This could be changed, but would mean quite some redesign. So when changing this, I would like to switch to the new nightscout v3 api. That would have to be done sooner or later...

**Comment by poml88** [comment]
I agree it woule be best added while moving to the v3 api. More interesting could be the timers to have less calculation to find out how old the values are (current time -- time of widget update -- age of value) :-)

**Comment by poml88** [comment]
Question: The delte of the BG values that is displayed, how is that calculated? Is that the last 5 values, or last 10 minutes, or...?

**Comment by poml88** [comment]
Ah, ok. Since the Libre reports 5 values in that 5 minutes I was a bit confused.

**Comment by dhermanns** [comment]
So, I would expect 5 minutes there, too. Since the delta of 1 minute makes not so much sense. But just a wild guess, since I'm not using Freestyle. The delta is retrieved via backend in just all cases.

The only exception from this is right now during background updates. There I'm calculating the delta on my own right now. But should be removed there too, when switching to V3.

**Comment by poml88** [comment]
I guess for FSL2/3 users it would be interesting to get this nororious arrow there, maybe instead of the delta. It is a good indicator how quickly things are changing. I agree that a delta of 1 minute is quite useless. :-)

**Comment by dhermanns** [comment]
Don't introduce UI differences depending on this feature. It will be hard to test if there is a different rendering whether 1 minute updates are enabled or not.

At least I won't expect that the arrows are rendered just in the case ;-)

**Comment by poml88** [comment]
I do not plan to play with the UI... Well, on the watch app main screen I would prefer to make the arrow a bit larger. Maybe re-arrange the delta, arrow, and time, it is quite small. And there seems to be a bit of space to the right of it.

**Comment by poml88** [comment]
Hi, ok, I made quite a lot of progress on this. It is really just adding one line or so, nothing complicated.

* I have added the `AccessoryWidgetBackground()` to the supported widgets. That makes it much easier to read at least on my phone, because I have a picture of the dog as the background. For people with simple background it is not necessary. We could of course add an option to the preferences to switch these backgrounds on and off. Then people can decide.

* The timers are working just fine on watch and phone. Very simple. I have chose the "offset" type for the moment [see these examples](https://sarunw.com/posts/swiftui-text-date-format/), perfect. I think, for the rectangular we can even omit the 4th line, or add a 4th value, because each time the widget refreshes, we could calculate the age and then the timer will start from there, so we would see every second how old each value is. Much better already, it says now "+8 minutes" instead of some time...

* There is something: For the FSL3 people who have 1 minute updates it might even be better to calculate some sort of average of the last 0-5, 5-10, 10-15 minutes, to get some more useful info? On the other hand, if we could hack the notorious arrow in, as discussed above, that would be enough.

* I was also wondering if it was not better after 30 minutes or so, to change very old values to "---" instead of still showing them. Would make it much clearer, that they are useless now.

**Comment by dhermanns** [comment]
2) If offsets are working fine, Line 4 could indeed be removed - great! The 4th line caused clippings under circumstances.

**Comment by poml88** [comment]
1. This background is adaptive, so I am not sure it has to be in the preferences. Some people would need to try it out, it is working fine for me. 

> An adaptive background view that provides a standard appearance based on the the widget’s environment.
> The system only displays this view inside a [WidgetFamily.accessoryCircular](https://developer.apple.com/documentation/widgetkit/widgetfamily/accessorycircular), [WidgetFamily.accessoryCorner](https://developer.apple.com/documentation/widgetkit/widgetfamily/accessorycorner), or [WidgetFamily.accessoryRectangular](https://developer.apple.com/documentation/widgetkit/widgetfamily/accessoryrectangular) widget. In any other context, the system displays an empty view instead.

2. Indeed, the box is very full, to get rid of the 4th line would be good. The question is how to format the timer. The shortest one is a simple timer "9:59", I prefer the "+9 minutes" one but it is long. But it can be clipped, but then it could shoe "min" "mi" or m" or anything in between. It is a bit difficult to test for me, because the widget preview is incredibly slow and does not work for me. I did not manage to have my watch show up in xcode as well, I can't access the developer mode on it. But I guess this is because I don't own a Mac...

3. That needs some thinking.

4. Ok, it does not harm. There could be a preference though "remove old values", easy.

**Comment by poml88** [comment]
There is this [TestFlight Version](https://testflight.apple.com/join/dyfTHeDx) if someone wants to try out the new timer and backgrounds.

**Comment by dhermanns** [comment]
The background of the widget looks quite strange on my wallpaper. I would prefer at least a transparent background with rounded corners.

The auto updated time is amazing. It would be great to have the time for each bg value adjusted. And the 4th line would be obsolete.

Great work 👍

**Comment by poml88** [comment]
You mean the rectangular widget? Yes, the background is very sharp and rectangular at the moment. Needs a bit more work.

**Comment by poml88** [comment]
It is tricky to format the timer... At the moment you have 1m, 2m, 3m, the timer is dynamic, so not easy to clip I think. Any ideas? I will update the code in my fork.

Also time consuming, because the preview does not work, for iOS 17 it always wants this stupid `.containerBackground(for: .widget)` and I am trying to implement that, but still the preview does not work. Rubbish...

**Comment by poml88** [comment]
So, I need some advice for the timers, they are running, but how to format? It is a bit tricky. I made an example app where the preview works. In the NG app I cannot get them to work. Here two screen shots. There are three timers: .timer, .offset, .relative. See the examples in a post above. 
![1 Widget_Extension_watchOS](https://github.com/nightscout/nightguard/assets/68424827/7e15734b-6c55-46b7-8d53-86235a146bb6)
![2 Widget_Extension_watchOS](https://github.com/nightscout/nightguard/assets/68424827/d0e987ed-489a-451b-850b-fdd0fd11cab8)

**Comment by dhermanns** [comment]
When looking into your examples I think all output is much to long. What looks promising is to use a .timer style instead.

**Comment by poml88** [comment]
Yes, but then the display is full of numbers everywhere, and they all change every second. Very busy.

**Comment by dhermanns** [comment]
Would be enough for the first value. Second could be +5m and so on.

**Comment by poml88** [comment]
As far as I understood these timers are not really formattable. 
The first line could be .timer the other two .relative or so.

**Comment by dhermanns** [comment]
Yes. I would just hardcode the second line as static +5m

**Comment by poml88** [comment]
But with widget update every 15 min or so that can lead to strange results.

**Comment by dhermanns** [comment]
Why? Should look like

15:21 102-5
  +5m 107+0
 +10m 107-2

**Comment by poml88** [comment]
Maybe this is too complicated by email ;-)
Because we are combining two ages here: The age of the entry and the age of the widget.
Maybe I am too stupid. :-)

So:
Line 1: timer starts at 0 widet age + X entry age
Line 2: static at widget age + entry age?
Line 3  same as Line 2?

**Comment by dhermanns** [comment]
Line 2 just relative age to line 1.
Line 3 the same.

**Comment by poml88** [comment]
Ah, ok, maybe I get it. But then we have the calculation again as with the time... 15 min+ 5 min, ok, much less complicated, but I liked the idea of having the exact age at every line.

**Comment by dhermanns** [comment]
Only option seems to be .timer. If used for all lines gets indeed more noisy.

**Comment by poml88** [comment]
So you don't like the shortened lines with
1 mi...
10 m....
2 hrs....
?

**Comment by dhermanns** [comment]
Looks ugly ;-)

**Comment by poml88** [comment]
Another issue is, that I cannot align the .timer to .trailing, it will always be on the leading edge.

**Comment by dhermanns** [comment]
No - different Types. Double and Date.

**Comment by poml88** [comment]
Uff, ok, thanks, let's see when I can figure that out how to calculate...

**Comment by dhermanns** [comment]
We are living in Copilot century ;-)

Copilot.microsoft.com

```

import Foundation

// Create a reference date (e.g., current date)
let referenceDate = Date()

// Define your double timestamp (e.g., 1621939200.0)
let doubleTimestamp: Double = 1621939200.0

// Calculate the time interval (difference) in seconds
let timeInterval = TimeInterval(doubleTimestamp)

// Subtract the time interval from the reference date
let resultingDate = referenceDate.addingTimeInterval(-timeInterval)

// Print the resulting date
print("Resulting Date: \(resultingDate)")

```

**Comment by poml88** [comment]
Wow... What did you enter as a question for the KI?

**Comment by poml88** [comment]
No, the KI seems to be wrong. So the timestamp seems to be something 1716626685 from 1.1.1970, so I have to add the same number (1.1.1970-25.5.2024) and the difference of that is it....

**Comment by dhermanns** [comment]
sure - that was just an example of how to subtract the different data types.

**Comment by poml88** [comment]
I am now at something like this:

```
var entryTimeInterval = entry.entryDate.addingTimeInterval(-bgEntry.timestamp).timeIntervalSince1970
                            
                            Text(entry.entryDate.addingTimeInterval(-entryTimeInterval), style: .timer)
```

But it seems to be off by some thousand seconds.

**Comment by poml88** [comment]
BTW you are going through the three lines via a ForEach, so it will be difficult to make the first line .timer and the other two static.

**Comment by poml88** [comment]
Uff, finally fixed the previews, now it is easier to work.

**Comment by poml88** [comment]
Ok, the solution is 
`Text("    \(entry.entryDate.addingTimeInterval(-(Date.now.timeIntervalSince1970 - (bgEntry.timestamp / 1000))), style: .timer)")`

With the previews much easier to figure out. So, how do we do the formatting?

**Comment by poml88** [comment]
So, for me, currently this is the best option, I know you don't like it. 
Is there a good trick how to deal with the `ForEach`, to have the first line .timer and the other two static?
![Clipboard01](https://github.com/nightscout/nightguard/assets/68424827/1ada8552-3ee1-43f7-843f-9c20e971c664)

**Comment by poml88** [comment]
Ok, it is done, as you asked for. I'll make a testflight.

![Clipboard01 png](https://github.com/nightscout/nightguard/assets/68424827/505c2ee1-7799-4e70-b8f4-e172349215b6)

**Comment by dhermanns** [comment]
Looks great

**Comment by poml88** [comment]
So, how it is currently done is:
Line 1 timer = age entry + age widget
Line 2 +Xm = timer Line 1 + Xm = age entry 2
Line 3 +Xm = timer Line 1 + Xm = age entry 3

So, in the screen shot the age would be
4m
7m
11m
![Clipboard01](https://github.com/nightscout/nightguard/assets/68424827/e9f1da6b-39fa-4b69-bebf-c472753cc09c)

**Comment by poml88** [comment]
Latest [TestFlight](https://testflight.apple.com/join/dyfTHeDx) is available.

**Comment by poml88** [comment]
> A quick hack would be to add the direction to the BloodSugar class.

Ok, I see, because the timelineprovider is reading its data like this. And this is only the three needed values. Could add the arrow, right?

```
NightscoutService.singleton.readTodaysChartData(oldValues: []) { (result: NightscoutRequestResult<[BloodSugar]>) in
            
            BackgroundRefreshLogger.info("TimelineProvider received new nightscout data...")
            var bgEntries : [BgEntry]
            var errorMessage = ""
            if case .data(let bloodSugarValues) = result {
                NightscoutDataRepository.singleton.storeTodaysBgData(bloodSugarValues)
                bgEntries = bloodSugarValues.map() {bgValue in
                    return BgEntry(
                        value: UnitsConverter.mgdlToDisplayUnits(String(bgValue.value)),
                        valueColor: UIColorChanger.getBgColor(String(bgValue.value)),
                        delta: "0", timestamp: bgValue.timestamp)
                }
```

**Comment by poml88** [comment]
Ok, I added the arrow to the BloodSugar class. And a miracle: it works. It is shown on the widgets. So, then I think I have everything implemented from my list.

**Comment by poml88** [comment]
For me, I do not need these +1 -1 0 really, I can see the difference between those values, but ok, why not.

![IMG_0580](https://github.com/nightscout/nightguard/assets/68424827/f40b4301-0ab1-4481-aa2f-4758419c0428)

**Comment by poml88** [comment]
Cool, in ios17 it is possible to tap a widget and then it refreshes. Super cool. I’ll implement that!

**Comment by dhermanns** [comment]
Great. Keep in mind to finish the open features first and provide PRs for them, if you want them in the app. Otherwise big PRs are hard to review.

**Comment by poml88** [comment]
Sure! I am back to normal life anyway. 

So, how do we do? I can commit to my fork. Then you’ll see the changes and can have a look?

**Comment by dhermanns** [comment]
Yes - by merging your fork changes in using the PR.

**Comment by poml88** [comment]
Ok. Just to explain: I cannot do PR from the fork branch I work on directly -- too many changes to build the project locally. I will do that somehow via another branch.

I just thought you wanted to quickly browse though the changes beforehands, but ok, I will come up with one or more PRs.

**Comment by dhermanns** [comment]
That is why you normally build each new feature on a new branch. Thats how you get it separated from other modifications on your fork.

**Comment by poml88** [comment]
So, would it be ok if I made one pull request for the changes so far? Or shall I make individual ones?

**Comment by dhermanns** [comment]
Normally you would make one for each feature naming it with the issue number. Github automatically links them to the ticket.

But to keep it easy this time, just do one. Hopefully it isn't too big ;-)

**Comment by poml88** [comment]
Hi, the PR will come, not forgotten, but I need to find a MAC first, it is too slow on my setup.
Meanwhile I am really enjoying the latest improvements. :)

**Comment by dhermanns** [comment]
TestFlight is read to go
