### ISSUE TITLE
Blood Sugar graph errors

### ISSUE THREAD

**Issue by Michaelmarks768** [nightscout/nightguard#278]
On my large  iwatch the graphs generated from gluroo stay on screen till I swipe

On my wife's smaller iwatch they only flash up and do not stay on screen - what can I do

**Comment by dhermanns** [comment]
Hi! What versions is your wife using?

**Comment by Michaelmarks768** [comment]
We both use the latest app from nightscoutWe are transferring freestyle libre data via gluroo to nightscout, that works On the 45 watch I get a complete graph which stays open On the 42 watch the graph shows for 1 secondAlso the complication selected never shows a graph say like blood pressure - so is that availableRegards Michael______________________+64 20 407 66 006 NZ +61 2 8091 3391 AUS+1 920 939 0705 USOn 11/01/2024, at 6:26 PM, dhermanns ***@***.***> wrote:﻿
Hi! What versions is your wife using?

**Comment by Michaelmarks768** [comment]
Regards Michael______________________+64 20 407 66 006 NZ +61 2 8091 3391 AUS+1 920 939 0705 USOn 11/01/2024, at 6:38 PM, Michael MARKS ***@***.***> wrote:﻿We both use the latest app from nightscoutWe are transferring freestyle libre data via gluroo to nightscout, that works On the 45 watch I get a complete graph which stays open On the 42 watch the graph shows for 1 secondAlso the complication selected never shows a graph say like blood pressure - so is that availableRegards Michael______________________+64 20 407 66 006 NZ +61 2 8091 3391 AUS+1 920 939 0705 USOn 11/01/2024, at 6:26 PM, dhermanns ***@***.***> wrote:﻿
Hi! What versions is your wife using?

**Comment by dhermanns** [comment]
I ment: Nightguard Version, WatchOS Version, iOS Version?

**Comment by Michaelmarks768** [comment]
Latest software - all up to date - and Apple 9 watches. Does the video help? I can send a video of it working on the 45 watch later if neededVersion 3.9.0.876Regards Michael______________________+64 20 407 66 006 NZ +61 2 8091 3391 AUS+1 920 939 0705 USOn 11/01/2024, at 6:48 PM, dhermanns ***@***.***> wrote:﻿
I ment: Nightguard Version, WatchOS Version, iOS Version?

**Comment by dhermanns** [comment]
Latest Software means you are using Nightguard Testflight Version? What Video?

**Comment by Michaelmarks768** [comment]
I am using  Version 3.9.0.876The video shows the problemAttached here againRegards Michael______________________+64 20 407 66 006 NZ +61 2 8091 3391 AUS+1 920 939 0705 USOn 11/01/2024, at 7:08 PM, dhermanns ***@***.***> wrote:﻿
Latest Software means you are using Nightguard Testflight Version? What Video?

**Comment by dhermanns** [comment]
Your Video seems to get lost. You can try the current Testflight:

https://testflight.apple.com/join/Ub8WcpcE

My wife has the small Series 9 Apple Watch, too. The chart is displayed fine, there.

**Comment by Michaelmarks768** [comment]
Will try it out here is a screen shot of all I get that lasts for 1 secondRegards Michael______________________+64 20 407 66 006 NZ +61 2 8091 3391 AUS+1 920 939 0705 USOn 11/01/2024, at 10:37 PM, dhermanns ***@***.***> wrote:﻿
Your Video seems to get lost. You can try the current Testflight:
https://testflight.apple.com/join/Ub8WcpcE
My wife has the small Series 9 Apple Watch, too. The chart is displayed fine, there.

**Comment by dhermanns** [comment]
You should try to enter your image in the github webfrontend. Not via eMail. Screenshot is missing for me, too.

**Comment by Michaelmarks768** [comment]
Have downloaded and initial result is goodRegards Michael______________________+64 20 407 66 006 NZ +61 2 8091 3391 AUS+1 920 939 0705 USOn 11/01/2024, at 10:44 PM, Michael MARKS ***@***.***> wrote:﻿Will try it out here is a screen shot of all I get that lasts for 1 second<image0.jpeg>Regards Michael______________________+64 20 407 66 006 NZ +61 2 8091 3391 AUS+1 920 939 0705 USOn 11/01/2024, at 10:37 PM, dhermanns ***@***.***> wrote:﻿
Your Video seems to get lost. You can try the current Testflight:
https://testflight.apple.com/join/Ub8WcpcE
My wife has the small Series 9 Apple Watch, too. The chart is displayed fine, there.

**Comment by Michaelmarks768** [comment]
Hi - can you advise best watch face that allows this graph to be on the main screen as a complication
The software changes are all working as expected thankyou.


Regards Michael
______________________

+64 20 407 66 006 NZ 
+61 2 8091 3391 AUS
+1 920 939 0705 US

> On 11/01/2024, at 11:04 PM, Michael marks ***@***.***> wrote:
> 
> Have downloaded and initial result is good
￼
> Regards Michael
> ______________________
> 
> +64 20 407 66 006 NZ 
> +61 2 8091 3391 AUS
> +1 920 939 0705 US
>

**Comment by dhermanns** [comment]
You can actually display the last three values, but not as a graph. You can use e.g. the modular watchface and then the rectangular complication.

**Comment by Michaelmarks768** [comment]
Thank you that is what I would have hoped I could get a graph like pulse rate.Regards Michael______________________+64 20 407 66 006 NZ +61 2 8091 3391 AUS+1 920 939 0705 USOn 16/01/2024, at 6:13 PM, dhermanns ***@***.***> wrote:﻿
You can actually display the last three values, but not as a graph. You can use e.g. the modular watchface and then the rectangular complication.

**Comment by dhermanns** [comment]
Right now the focus was to provide frequently updating complications. Just by using local updates.

This is very hard to do. Collecting all values for the chart will not work. So whats on my list is a much more simplistic graph just visualizing the last values.

**Comment by Michaelmarks768** [comment]
As someone who has type 1 and uses Freestyle, which does not have any watch app - I use your key graph (for the last 12 hours)  - all the time - for information, and to be able to display a chart of even the last hour on the watch's main screen would be fantastic.

Regards Michael
______________________

+64 20 407 66 006 NZ 
+61 2 8091 3391 AUS
+1 920 939 0705 US
