### ISSUE TITLE
Nightguard

### ISSUE THREAD

**Issue by danielcapitaine** [nightscout/nightguard#279]
Bonjour mon Nightguard fonctionne bien sur mon IPhone 15 max pro plus ou je je put lire mes valeurs part contre sur mon Apple Watch 9 les valeurs ne s'affiche pas ou reste erroné . Je suis sous IOS 17.3 & Watch 10.3 . Merci

**Comment by dhermanns** [comment]
Sorry - english only here. My french is too bad.

**Comment by danielcapitaine** [comment]
Hello my Nightguard works well on my IPhone 15 max pro plus where I was able to read my values on the other hand on my Apple Watch 9 the values are not displayed or remain incorrect. I am running IOS 17.3 & Watch 10.3. THANKS

**Comment by dhermanns** [comment]
Have you tried the latest TestFlight version? There have been quite some improvements for the watch:

https://testflight.apple.com/join/Ub8WcpcE

**Comment by susierdmann** [comment]
Es funktioniert wieder mit der TestFlight-Version, ich sehe meine Daten wieder auf der Apple Watch - Danke

**Comment by dhermanns** [comment]
Thx for your feedback 👍

**Comment by danielcapitaine** [comment]
I have a testfligt version downloaded from Apple Store I don't have a code My version is 3.4.3 (63) Thank you

**Comment by dhermanns** [comment]
I'm not sure what you mean. V3.9.1 is the latest nightguard version. Its on the App Store now. Apple Watch should work fine with it now. 

But you will have to habe the latest WatchOS Version installed. Sometimes there is a bug where you have to deinstall/reinstall the watch part of nightguard.

**Comment by danielcapitaine** [comment]
Et quand je tape sur les chiffres en bas a droit voici ce que j'ai avant cela était automatique  . Merci beaucoup  
![thumbnail_IMG_0214](https://github.com/nightscout/nightguard/assets/77685608/d3aa14b3-e5f1-4c07-a3db-16d39c24e19b)

**Comment by danielcapitaine** [comment]
Merci beaucoup cela refonctionne
