### ISSUE TITLE
Trend arrow 45 degrees up is flipped

### ISSUE THREAD

**Issue by hummelstrand** [nightscout/nightguard#28]
Just a small and cosmetic bug, but one of nightguard's arrows is flipped horizontally, making it inconsistent with Nightscout and all other of nightguard's arrows.
![img_1724](https://user-images.githubusercontent.com/2979793/35267212-d4a045ea-0025-11e8-9646-df500d9675ef.PNG)
![img_1722](https://user-images.githubusercontent.com/2979793/35267213-d4b8dfba-0025-11e8-858c-5ca2bf0b6a82.PNG)
![img_1723](https://user-images.githubusercontent.com/2979793/35267214-d4d1ac5c-0025-11e8-8106-22691aa1d7e0.PNG)
I tried to look through the code to see if I could submit a fix in a pull request, but I'm not really a developer at all so I couldn't find the correct place to fix this.

**Comment by dhermanns** [comment]
Yes - this is known. As far as I know, there is no unicode item for an upper right arrow. And I don't like to introduce images, since I would have to deal with different image sizes and scaling in that case.

**Comment by hummelstrand** [comment]
How about 2197 from the official Unicode specification: ↗
https://www.unicode.org/charts/PDF/U2190.pdf

By the way, let me know if you need SVGs.

**Additional feature request:** would it be possible to make the trend arrow on the 38 mm Watch app slightly larger?

**Comment by dhermanns** [comment]
I missed that ;-) Thanks for the input. I will try that.

**Comment by dhermanns** [comment]
This is fixed within 1.5.2 which is available as soon.
