### ISSUE TITLE
Missed Readings....

### ISSUE THREAD

**Issue by DJAnj** [nightscout/nightguard#280]
You may have seen this on the app store - I have the same issue and it still ocvcurs in 3.9.0:

__Despite disabling the “missed readings” toggle in the alarms preferences, the Apple Watch app still constantly vibrates every few seconds to alert of missed readings (even if I’m not wearing the watch). I understand that I can snooze this (ie. at night when my nightscout setup is recharging) but it’d be nice if I didn’t have to manually snooze the watch app every night when in theory it shouldn’t be alerting me of anything at all...

**Comment by dhermanns** [comment]
Hi! Try the latest TestFlight:

https://testflight.apple.com/join/Ub8WcpcE

**Comment by dhermanns** [comment]
V3.9.1 is out on the Appstore now.
