### ISSUE TITLE
Widget time intervals

### ISSUE THREAD

**Issue by Argon-** [nightscout/nightguard#281]
Greetings!

I’m a little confused about the 0/1/2m in this widget:

![IMG_4883](https://github.com/nightscout/nightguard/assets/540920/0ca6829e-9eca-4786-b550-47fdbb04e912)

I would assume this means minutes but that doesn’t make sense since the update interval is 5min. What does this value refer to then? 🤔

**Comment by Argon-** [comment]
Libre 3, yes. But my nightguard instance only does 5min intervals. The nightguard app also only shows me a new value every 5min. I'll check that again though.

Thanks for that awesome app by the way and the recent addition of a timestamp on that widget is really useful!

**Comment by rterras** [comment]
Hello, since the last update on my iPhone SE 2022, the widget is clipped.
<img width="375" alt="Screenshot 2024-01-18 at 15 59 09 png" src="https://github.com/nightscout/nightguard/assets/156584841/f6a8246f-3416-49cf-b5b7-c716858643af">

**Comment by dhermanns** [comment]
This will have to do with the new 4th line in the widget.

**Comment by dhermanns** [comment]
Yes - noticed the clipping, too. Will look into it.
