### ISSUE TITLE
I watch not showing on main dusplay

### ISSUE THREAD

**Issue by Oren-Yul** [nightscout/nightguard#283]
I am Using the latest sw of all. Iphone, apple watch and nightguard.
SE 44mm. MNK03HB/.
The main display on the watch was stuck on reading. I uninstalled it and reinstalled.
Now it shows nothing.
The detailed display works.
Please advise.
Oren

**Comment by dhermanns** [comment]
Do you have a screenshot?

**Comment by Oren-Yul** [comment]
![image](https://github.com/nightscout/nightguard/assets/153934828/9a512564-31b6-433e-bde7-d0984b537bb8)

https://github.com/nightscout/nightguard/assets/153934828/37589118-c251-4100-b92f-8b5a5e80b97d

**Comment by dhermanns** [comment]
You mean the watch app is working but the complication is not rendered? You can try to reinstall just the watch part of the app. Or try another watchface with a different nightguard complication.

**Comment by Oren-Yul** [comment]
I reinstalled the watch app.
I tried another watch face with the complication. Same result.
I tried also thr a along and text.
Both do not work.

**Comment by dhermanns** [comment]
Do you had the TestFlight Version installed before? Do the complications appear twice in the dropdown if you change them?

Did you have nightguard lockscreen widgets installed on your phone? Did they update fine?

**Comment by Oren-Yul** [comment]
None of the above.
Reset helped a bit

**Comment by Oren-Yul** [comment]
![image](https://github.com/nightscout/nightguard/assets/153934828/e5cc1ae3-67a4-49ff-80b3-3c5f1af6f171)

**Comment by Oren-Yul** [comment]
0m is always there. What does it mean?

**Comment by dhermanns** [comment]
Great. 0m is the age of the reading you are seeing. But at the time of the last complication update. If you switch to the large rectangular complication, you can even see the timestamp the 0m is relative to.

**Comment by dhermanns** [comment]
![image](https://github.com/nightscout/nightguard/assets/3207317/9216921d-461e-4387-bd8b-08d44124db2f)

**Comment by Oren-Yul** [comment]
OK.
Thanks.
Where and how do I get the large complication?

**Comment by dhermanns** [comment]
By selecting the modular watchface

**Comment by Oren-Yul** [comment]
![image](https://github.com/nightscout/nightguard/assets/153934828/b2ef35e5-9ba9-4a8f-bd0b-0c2d89908e81)
![image](https://github.com/nightscout/nightguard/assets/153934828/8b514da3-41fa-4e42-b883-7b44d8c99144)
How does these go together?

**Comment by OrenYul** [comment]
Hi
I see big differences.
See pictures attached.
Please advise.

![image](https://github.com/nightscout/nightguard/assets/7289339/10ff9eb4-573e-4a2b-b8e8-189ee0c00903)
![image](https://github.com/nightscout/nightguard/assets/7289339/d33c1fbd-0d38-40f3-8fb2-ad5265f94900)
![image](https://github.com/nightscout/nightguard/assets/7289339/f5921617-b732-4332-aaea-a7a009322b97)

**Comment by OrenYul** [comment]
See below complications

![image](https://github.com/nightscout/nightguard/assets/7289339/51f4440b-04c0-44b8-b778-389ae0de0d0e)
![image](https://github.com/nightscout/nightguard/assets/7289339/95987356-276e-4e83-8070-2a89e1afaacf)

**Comment by dhermanns** [comment]
Apple allows 75 Background Updates for Complications. So you should see vales every 10-20 Minutes.

But the new cool features are critical push notifications (if you enable them in the alarms tab). So you don't have to always keep an eye at your watch at all.

If you need it more often, you will have to open the watch app and keep it running. You can configure that, too.
