### ISSUE TITLE
Apple Watch app not working after upgrading to Watch OS 10.2

### ISSUE THREAD

**Issue by painter9** [nightscout/nightguard#284]
The app was working on my Apple Watch until I upgraded from OS 9. something to 10.2.  Now it just opens and immediately closes.  It does create a diagnostic log each time.

**Comment by dhermanns** [comment]
Then the log would be very useful.

**Comment by painter9** [comment]
Please find attached the most recent log  file.Sent from my iPhoneOn Jan 22, 2024, at 11:48 AM, dhermanns ***@***.***> wrote:﻿
Then the log would be very useful.

**Comment by dhermanns** [comment]
It got filtered. You can send it to:

Issue284.hermanns@spamgourmet.com

**Comment by painter9** [comment]
I attached and sent the log file to the other email address as requested on Monday.  Did you receive it?By the way, my phone is now updated to iOS 17.3 and my watch to OS 10.3.  It did not resolve the issue.Sent from my iPhoneOn Jan 22, 2024, at 12:29 PM, Alan Painter ***@***.***> wrote:﻿Please find attached the most recent log  file.<nightguard-2024-01-22-105219.ips>Sent from my iPhoneOn Jan 22, 2024, at 11:48 AM, dhermanns ***@***.***> wrote:﻿
Then the log would be very useful.

**Comment by dhermanns** [comment]
No - nothing received yet

**Comment by dhermanns** [comment]
Correction - found it in spam ;-)

**Comment by painter9** [comment]
Great Sent from my iPhoneOn Jan 25, 2024, at 8:36 AM, dhermanns ***@***.***> wrote:﻿
Correction - found it in spam ;-)

**Comment by dhermanns** [comment]
It crashing during
NightscoutDataRepository.singleton.storeTodaysBgData(bloodSugarValues)

So looks like its something wrong with the received data or with access to the userdefaults.
You can send me your URI using the email above and I will try to reproduce this on my side.

**Comment by painter9** [comment]
I just accidentally deleted the URL in the app on my phone while attempting to copy it.  I will send it after I get it back.Sent from my iPhoneOn Jan 25, 2024, at 9:21 AM, dhermanns ***@***.***> wrote:﻿
It crashing during
NightscoutDataRepository.singleton.storeTodaysBgData(bloodSugarValues)
So looks like its something wrong with the received data or with access to the userdefaults.
You can send me your URI using the email above and I will try to reproduce this on my side.

**Comment by painter9** [comment]
Gluroo Nightscout API for Alanns.gluroo.com https://86ef.ns.gluroo.com/?token=86efa451-2cfd-49a8-807b-66220bf69a60Sent from my iPhoneOn Jan 25, 2024, at 9:21 AM, dhermanns ***@***.***> wrote:﻿
It crashing during
NightscoutDataRepository.singleton.storeTodaysBgData(bloodSugarValues)
So looks like its something wrong with the received data or with access to the userdefaults.
You can send me your URI using the email above and I will try to reproduce this on my side.

**Comment by painter9** [comment]
https://86ef.ns.gluroo.com/?token=86efa451-2cfd-49a8-807b-66220bf69a60By the way, it does work on my iPhone.Sent from my iPhoneOn Jan 25, 2024, at 9:21 AM, dhermanns ***@***.***> wrote:﻿
It crashing during
NightscoutDataRepository.singleton.storeTodaysBgData(bloodSugarValues)
So looks like its something wrong with the received data or with access to the userdefaults.
You can send me your URI using the email above and I will try to reproduce this on my side.

**Comment by painter9** [comment]
Did my response get trapped again?Sent from my iPhoneOn Jan 25, 2024, at 9:21 AM, dhermanns ***@***.***> wrote:﻿
It crashing during
NightscoutDataRepository.singleton.storeTodaysBgData(bloodSugarValues)
So looks like its something wrong with the received data or with access to the userdefaults.
You can send me your URI using the email above and I will try to reproduce this on my side.

**Comment by dhermanns** [comment]
You should answer directly in github. This would redruce the visual noice send, too.

Your case remembers me of #217. Was gluroo and Libre3, too. The idea was that the much bigger amount of blood-values could cause this.

What helped there was reinstalling/installing the app. The it runs to a certain level.

I tried your URI and they work fine with my Ultra1. No crashes.
Do you have enough free space on your watch/phone?

**Comment by painter9** [comment]
My watch has 6..7 of 16 GB free.

The app ran fine on both my phone and watch until I updated the OS.  It stopped working on the watch.  If you think uninstalling that app could resolve the issue with the watch, I would try it.

**Comment by painter9** [comment]
I tried uninstalling and reinstalling.  The result is the same.

**Comment by dhermanns** [comment]
You can reinstall just the watch app first. Maybe that is even enough.

**Comment by dhermanns** [comment]
If you are not on the testflight, try that.

**Comment by painter9** [comment]
It appears that uninstalling the app from just the watch and then reinstalling it has made it operational again.

My previous message referred to uninstalling from the phone.  That did not work.

Thanks for your help.

**Comment by dhermanns** [comment]
Great - but I would expect that this could happen again. Have a look at certain data situations that occur. Or error situations that could mess the amount of data.

**Comment by dhermanns** [comment]
And feel free to come back here then.
