### ISSUE TITLE
APP homepage does not display charts on IOS

### ISSUE THREAD

**Issue by fanshengshuai** [nightscout/nightguard#287]
APP首页的图表不显示，数据源用的Nightscout 
![214a4ac1a628311e323f137b65a2d18](https://github.com/nightscout/nightguard/assets/1038290/c15ac16e-c51e-45b2-92b0-f3e3e4b9a36e)

**Comment by dhermanns** [comment]
Sorry - my chinese is very bad. Please use the search. Could be something like #133.
If not - a little bit more background information could be useful. E.g. what is your nightscout version you are using.

Can you access your nightscout entries manually e.g. using:

/api/v1/entries.json?token=yourtokenhere

**Comment by fanshengshuai** [comment]
thiank you, the same thing！please close this issue
