### ISSUE TITLE
Numbers on bottom axis illegible

### ISSUE THREAD

**Issue by Chicagogrl** [nightscout/nightguard#288]
On my iPhone 13 I can’t read the times. They’re too long and overlap each other. The display is illegible. They need to be shortened or displayed sideways so users can read them. I have a screenshot to illustrate what it looks like for me.

**Comment by dhermanns** [comment]
Hi! Did you forget to attach?

**Comment by Chicagogrl** [comment]
Sorry, I couldn’t find a way to attach.

[image0.jpeg]


Sean Pakieser
she/her
773-807-8655

On Feb 19, 2024, at 11:15 PM, dhermanns ***@***.***> wrote:

﻿

Hi! Did you forget to attach?

**Comment by dhermanns** [comment]
You can attach it via github Webfrontend. Not via email.

**Comment by Chicagogrl** [comment]
[
![IMG_7797](https://github.com/nightscout/nightguard/assets/160558847/552af345-d11f-4188-8a32-aaadf5c249b5)
](url)

**Comment by dhermanns** [comment]
Is this the statistics tab?

**Comment by Chicagogrl** [comment]
It’s the graph that appears at the Home Screen

**Comment by dhermanns** [comment]
Looks like the problem is it tries to show more than 24h of data. And that should not be the case.

Hard to say whats causing this, since I can't reproduce it here. You can leave me a read-only URI here:

issue288.hermanns@spamgourmet.com

But I expect that with a fresh setup, this is even not reproducible.

**Comment by Chicagogrl** [comment]
![image](https://github.com/nightscout/nightguard/assets/160558847/bad2dcb3-1d99-42ab-88a5-1af5a445f8ab)

Nightguard randomly shows the correct display. I haven’t changed display settings, or de and re-installed. If I toggle the text size on iPhone for just this app, to larger or smaller, only the font for navigation in the app changes, never the graph tab/section.

I can’t force the problem to appear no matter which time period (8 hours, 24 hours, yesterday and today) I choose. I turn on and off “yesterday data” to no effect. I close the app and re-launch it without a change. 

Sometimes the times appear legible, but most times they do not. I notice that when they display correctly, there are 8 vertical bars of data on screen, so the chart is widely spread and so must the labels. When they overlap incorrectly, there are 12 or 14 vertical bars on screen. Again, I do not modify the settings on my phone unless it was to test the conditions that might cause the issue.

**Comment by dhermanns** [comment]
Yes - that is what I expected. The huge amount of bars shown is due to a much too wide range of data displayed.

Normally, they are reduced to just 24 hours. Seems to not work correctly on your system.

**Comment by dhermanns** [comment]
Is this still an issue? I had this once after day-light-saving changes. But am not able to reproduce this anymore.
