### ISSUE TITLE
Nightguard Apple Watch issues

### ISSUE THREAD

**Issue by mdhdixie06** [nightscout/nightguard#289]
The Nightguard app is not appearing as an available app on my Apple Watch. How do download the app to my watch to get the widget?
![IMG_8177](https://github.com/nightscout/nightguard/assets/160801413/17b96524-de4c-4105-8c25-ba0bc35311cf)

**Comment by dhermanns** [comment]
Hi! Please use the search before opening new issues: #286

**Comment by skimark1** [comment]
I successfully installed nightguard on my iPhone 15 Pro Max and the Nightguard app for my Apple Watch shows up on the Watch app on my iPhone, but when I click on install for Nightguard, it puts up a spinner, doesn't install and just goes back to offering to Install the app. I've tried multiple times with no success. Any ideas?
Thanks

**Comment by dhermanns** [comment]
No - looks more like an issue with iOS and/or watchOS. Have you tried turning it off and on again ;-)?

**Comment by skimark1** [comment]
I force restarted both the watch and phone and it is working now. I appreciate you!

Thanks,
Mark Cillis
***@***.***

**Comment by dhermanns** [comment]
Works all the time 😉
