### ISSUE TITLE
No more background alarms

### ISSUE THREAD

**Issue by motinis** [nightscout/nightguard#290]
So I've noticed this the last couple of months. I have Nightguard on my phone set up with 25 minutes low prediction. This used to work very well - even if I didn't have my phone unlocked or I was using other apps, I would usually get an alert from Nightguard within 3-4 minutes (so e.g. with 21 minutes predicted to the low). These have definitely saved us a few times in the past. We're now no longer getting these at all (and notifications are enabled in settings for Nightguard)

I think this maybe related to iOS changes - maybe the notifications need to be changed to be time sensitive and/or critical? 

Thank you!

**Comment by dhermanns** [comment]
Did you have Notifications activated in Nightguard? And do you have the nightguard lockscreen widget configured? If so, you should get background alerts at least every 20 minutes.

**Comment by motinis** [comment]
> Did you have Notifications activated in Nightguard? And do you have the nightguard lockscreen widget configured? If so, you should get background alerts at least every 20 minutes.

Yes to the first, and no to the second. I will add that on. Still though, I wonder if the notifications could be updated to be time sensitive and/or critical (maybe as part of the nightguard settings) to help shorten the notification time?

**Comment by dhermanns** [comment]
You mean to get alerts more often then every 20mins?

**Comment by motinis** [comment]
Yes - to try and see if we can get it more than every 20 minutes. 

Although e.g., maybe a Loop / (x)APS extension which pulls their predicted curves and uses that? I'm not sure what kind of logic you can drive once you get the data when you're in the background.

It could be the only way to handle with the predicted low we just need to setup an additional IFTTT/Push

**Comment by dhermanns** [comment]
You won't get more often updates. That is an Apple restriction for background updates. But it works very well when using the lockscreen widget. During most of the day you should get alarms within 5-10 minutes.

**Comment by motinis** [comment]
Just trying the lock screen widgets - the values displayed there seem to have quite a bit of lag in terms of updating (even if e.g., I just had Nightguard open). I think it may be a good idea to use actual timestamps there rather than e.g., -3m, -8m, etc. since those aren't accurate if the data isn't being updated frequently enough.

**Comment by dhermanns** [comment]
This is why the rectangular widget has a timestamp 😉

**Comment by dhermanns** [comment]
Yes - relative to the timestamp displayed:

![image](https://github.com/nightscout/nightguard/assets/3207317/38a11d10-6504-4bc9-9c44-bb62a492ab49)

**Comment by motinis** [comment]
So I understand the idea but it’s not updating for me. Phone time has since updated by 10 minutes but the rows displayed are still old and not with correct relative times now.

**Comment by motinis** [comment]
Maybe I need to update? Mine doesn’t have that last line with the time stamp on it. I’m using a test flight version though I think (with 5 bg intervals for lows)

**Comment by motinis** [comment]
Yes. Updating helped. Although annoyingly it is cropping the top line and the timestamp. I don’t know if I can resize the widget area.

**Comment by motinis** [comment]
Can’t be resized. Oh well. Still I can see the values well enough. Thank you!!

**Comment by motinis** [comment]
Changing the date widget to the nightguard one is also very nice. Gives the timestamp too

**Comment by motinis** [comment]
Lagging updates / different frequency I could understand - the issue is that the times seem completely off. Like resolving to different time-zones but in an inconsistent way. Looks like a weird bug to me.
