### ISSUE TITLE
I can´t set up a Widget on my iphone with IOS17.4

### ISSUE THREAD

**Issue by pedroConsuegraMateo** [nightscout/nightguard#292]
Hi all!

## Context:

First of all, sorry if I am not taking something into account but I have the following issue.
I just started to use the app, and it is working, I get all my sugar data in the app but I want to set a widget on my iphone and I'm not having an option to add a nightguard widget. I'd say that the feature exist because I saw in some tutorials but I can't see on my device.

I am using an iphone 14 with last ios version (17.4) and my nightguard version is the v3.9.1.902.

Could anyone help me? 

Thank you in advice!

**Comment by dhermanns** [comment]
Hi! Did you try to add it to the lock-screen? Other widgets are not available right now.

**Comment by pedroConsuegraMateo** [comment]
Hi @dhermanns ! I have tried that right now and yes.. it works. So, it is working fine in the lock screen. 
Thank you! I think we can close the issue :D

**Comment by dhermanns** [comment]
Perfect ;)
