### ISSUE TITLE
Doesn't show on Apple watch

### ISSUE THREAD

**Issue by ASF93** [nightscout/nightguard#293]
Hello all.

I don't now if it is normal, but in this moment Test Flight doesn't allowed me to try Beta Version of the app. Before that, the app was running smoothly on my apple watch without problems.

Right now I can't even access it. Do you have any idea why this is happening?

Thanks a lot fro your help

**Comment by dhermanns** [comment]
Hi! Yes, this is normal. Current Beta is older than 3 Month. So you will have to switch to the app store version. But it should be functional identical.

**Comment by ASF93** [comment]
Hello @dhermanns.

Thanks for your reply.

Followed your advice. All solved. 
Thanks a lot 🫡

**Comment by andypituch** [comment]
I have the same issue.

Since the beta has expired how do we "roll back" to the app store version of the nightguard app and how smooth/disruptive is this (e.g. will I need to add the configuration back to the app or will it carry over).

**Comment by ASF93** [comment]
Hey.

Basically I just uninstalled the beta version e reinstalled the app store one. Also removed the old one from apple watch.

About the configuration, probably you will gonna have to do it again

**Comment by dhermanns** [comment]
You can easily switch between the versions. No reconfiguration necessary.
