### ISSUE TITLE
Apple Health

### ISSUE THREAD

**Issue by eichmat** [nightscout/nightguard#294]
v3.9.1.902

I’m not seeing data flow to Apple Health after enabling the feature in NightGuard and Apple Health. 

![IMG_0982](https://github.com/nightscout/nightguard/assets/13202205/857df3e7-4e1f-4590-8d30-c8f4abc8373b)
![IMG_0983](https://github.com/nightscout/nightguard/assets/13202205/dad93a58-8f49-4746-ac2a-fe407423d511)
![IMG_0984](https://github.com/nightscout/nightguard/assets/13202205/d992c45f-3002-49a7-ad6b-364128fd7c13)

**Comment by dhermanns** [comment]
Have a look at #255. The feature has been provided by @sebdei who will have a look at it. 

So closing this in favor of #255. Would expect that this will be fixed afterwards, too.
