### ISSUE TITLE
Questions about refresh of watch app and background refresh

### ISSUE THREAD

**Issue by poml88** [nightscout/nightguard#298]
* So, is it so, that when the watch app becomes active it should refresh the BG data? When I lift my arm, and the screen of the watch comes on and shows the NG app, normally it updates the data immediately. Is that how it is supposed to be? Because 50% of the time, it takes too long, let's say 10 seconds and the screen gets dark before the updated data is shown. And sometimes I even have to press the "refresh" button on the second screen. What is the intended behaviour here?

* On the last screen of the watch app there are some statistics about background updates. But it is all always 0 for me. Should there actually be something happening there?

* In the same context, I played with turning on and off the background updates (Hintergrundaktualisierung) on phone and watch, but it did not seem to have any effect on neither the phone app nor the watch app. Is that correct?

**Comment by dhermanns** [comment]
1) The update when the watch is active is done through a timer every 10 seconds. But that works only if the watch is running. That is causing the inconsistency. 

The delay during startup of the app could be removed when using callbacks as soon as new values are retrieved. But right now values are retrieved from backend. But usually get displayed during the next 10 seconds.

**Comment by poml88** [comment]
Thanks for your answers.

3. About the lockscreen widget, are you sure? I have another app with a lockscreen widget and it makes no difference. Also for the lockscreen widget of NG I did not notice any difference. It does update anyway only, if the screen is active.

**Comment by dhermanns** [comment]
Yes - it updates for me in background.
Do you have alarm notifications enabled in NG? And background updates in general?

You will have to have it running under this configuration for a certain time. iOS learns your behavior and schedules more and more background updates for NG, the more you use the app.

**Comment by poml88** [comment]
Hm, ok, well, it updates really often for me, that is fine, but only if I look at the phone or watch. Which is fine, because if I don't for an hour I save on refreshes from my budget.

No, alarms are activated, but not the notifications, the Benachrichtigungen switch.

I am testing both with background updates on and off.

**Comment by dhermanns** [comment]
You can try to activate notifications. You should get them even if your phone isn't in use at all...

**Comment by poml88** [comment]
1. This?
```
// update the ui every 15 seconds:
    let timer = Timer.publish(every: 15, on: .current, in: .common).autoconnect()
```

**Comment by dhermanns** [comment]
Yes - looks like

**Comment by poml88** [comment]
Ok, 15 seconds. That would fit. Would it be bad to choose 5 or 10? Battery drain?

Could we implement a refresh when UI becomes active?

**Comment by dhermanns** [comment]
I think the issue is to implement a callback as soon as the data is retrieved. That should improve this.

**Comment by poml88** [comment]
Ok, so do I understand that:
1. the timer does not count in background? But continues when the app becomes active?
2. You mean, the phone app retrieves new data and the watch gets those in background, so the latest data is already shown when the UI becomes active and the timer will be obsolete?

**Comment by poml88** [comment]
Ok, I implemented a Notification, when the app becomes active a refresh is done. I did not touch your timer. Just two lines. Very handy for me, because when I do a wrist raise, the latest data is shown, no need to wait 15 seconds (in the worst case). If that is annoying to you I could do it as a preference on / off.

**Comment by dhermanns** [comment]
No - that should be default. Was on my list. But lets see how you solved it...

**Comment by poml88** [comment]
We could alsoi have the timer fire in background every minute or so....

I did in MainView.swift
`    let refreshDataOnAppBecameActiveNotification = NotificationCenter.default.publisher(for: .refreshDataOnAppBecameActive)
`
and
`            .onReceive(refreshDataOnAppBecameActiveNotification) { _ in
                viewModel.refreshData(forceRefresh: false, moveToLatestValue: false)
`

in ExtensionDelegate
```
func applicationDidBecomeActive() {
        NotificationCenter.default.post(name: .refreshDataOnAppBecameActive, object: nil)
```

and in a helper file

```
extension Notification.Name {
    static let refreshDataOnAppBecameActive = Notification.Name("Thisneedsagoodname")
}
```

I wanted to try if `applicationWillEnterForeground` is better....

**Comment by dhermanns** [comment]
Latest TestFlight is ready now

**Comment by poml88** [comment]
So , as an update on this: After some months of testing, it seems that it works better to have

```
func applicationDidBecomeActive() {
        NotificationCenter.default.post(name: .refreshDataOnAppBecameActive, object: nil)

```
The current version in `applicationWillEnterForeground `does not always lead to a refresh.

Not sure why. We shall change this.
