### ISSUE TITLE
Question on Watch UI layout

### ISSUE THREAD

**Issue by poml88** [nightscout/nightguard#299]
1. I noticed, that there is quite a lot of space above the view. Is that emtpy space for smaller watches?
2. There is quite some space to the left of the BG value. And the three lines are very small and look quite squeezed. I would tend to make the BG number a bit larger, move the arrow to the right and make all three things a bit larger. Would that work?

![incoming-ACA99B0E-8538-4FDF-94E6-E2273D307BB4](https://github.com/nightscout/nightguard/assets/68424827/04b1648c-ffec-4ce2-b31f-c1d139e9edd0)

**Comment by dhermanns** [comment]
You should test this on the 40mm watch first. There is not so much space left.

**Comment by poml88** [comment]
Are there no preview values for the watchOS UI? It is pretty empty... the view. Only dashes etc.

**Comment by poml88** [comment]
Ok, I see. On a 40 mm watch it is quite tight. Agreed.
Since you already have a "show loop and cara data" toggle, maybe we could have another toggle "show pump data" that could remove the two pump values (reervoir and battery?) for pen users and enlarge the remaining values. The default could be "show pump data" and the view would remain the same per default. I could rearrange things a bit for pen users.

**Comment by poml88** [comment]
I was thinking about something like this, shows a 40 mm watch 6.
![Simulator Screenshot - Apple Watch Series 6 (40mm) - 2024-06-22 at 23 45 36](https://github.com/nightscout/nightguard/assets/68424827/52b36186-0e42-44a8-86b9-57825a0f2ea0)

**Comment by dhermanns** [comment]
I don't want to complicate the preference options. Every option that modifies the UI multiplies the efforts to keep up the quality.

**Comment by poml88** [comment]
Fair enough. :-) I will stick with this version -- much better for my case. At least until I will get the pump / loop, god knows what....

For me it is always showing 0 R and ?%, so two really useless confusing values. See first post.

**Comment by poml88** [comment]
BTW, on the 40 mm watch the German translation is a bit too long. Could be improved...
And I would swap the buttons. To have the accept on the right side I find much more intuitive.
![Simulator Screenshot - Apple Watch Series 6 (40mm) - 2024-06-23 at 00 26 27](https://github.com/nightscout/nightguard/assets/68424827/dc405cec-8200-498c-b1a8-8acde9745336)

**Comment by poml88** [comment]
I made a Testflight 910 for this UI, for me it is perfect. But I can keep this Testflight to myself, so not to confuse... But in case you want to try it I can open it for external testers.

**Comment by dhermanns** [comment]
I will close this so far. If someone likes this, your fork can be used instead.
