### ISSUE TITLE
Apple Watch

### ISSUE THREAD

**Issue by Quattro25** [nightscout/nightguard#3]
Hi
I have read some of these posts, and I wonder if I too could have this beta version...? 
I can't get the watch to recieve data, even though the app works fine on my iPhone. I live in Norway and we use mmol, is that a problem? 
Susanne

**Comment by dhermanns** [comment]
Hi! Mmol should work fine now, too. Leave me your eMail and I can add you
to the beta Version. But I think I will push the version to the App-Store
within the next week.
Quattro25 <notifications@github.com> schrieb am Mo. 18. Juli 2016 um 14:40:

**Comment by dhermanns** [comment]
Current version with mmol is in the App Store by now ...
