### ISSUE TITLE
Request: Please enable ability to change low/high values on watch version of Nightguard

### ISSUE THREAD

**Issue by AmeliaByko** [nightscout/nightguard#30]
I would appreciate if you could please give us the ability to either edit the low and high values on Nightguard for Apple Watch, or simple copy over those that are user-setup on Nightguard for iPhone. My watch shows a range of 80-180, but Nightguard for iPhone I keep set to 70-130. It's hard to tell when out of range due to how different the high&low range is on the watch. 

Also, if there was an option to change the color of the graph line for "today"'s highs and lows so that you could easily see when you were out of range while scrolling, this would also be hugely appreciated. Thanks for your help!

**Comment by dhermanns** [comment]
Hi! This seems to be a bug right now. As a workaround, you can do a force press on the watch and select "refresh". The high/low bounds from the app should update on the watch afterwards. You could do this multiple times. I will have a look at this.

**Comment by dhermanns** [comment]
This will be fixed with the upcoming 2.0.0 release. Once more thanks to Florian!!
