### ISSUE TITLE
Can anyone help?

### ISSUE THREAD

**Issue by DancerEm** [nightscout/nightguard#307]
Hello, 

I don’t have any idea of how to fix this, I’ve got the guardian monitor from yourselves and it’s not recognising my Medtronic username and password and have no idea how to implement any of this do that I can check my bloods and guardian sensor online or on my phone. How to do guardian monitor as can’t get my iOS 18 on Medtronic apps
@dhermanns

**Comment by dhermanns** [comment]
Are you sure you are right here? This is nightguard, not the guardian monitor. Nightguard is not directly linked to any cgm or pump like Medtronic.
