### ISSUE TITLE
Update past data from nightscout

### ISSUE THREAD

**Issue by poml88** [nightscout/nightguard#309]
Is there any specific reason, why NG is not pulling past data from NS if there has been no network for a while? The data in NS is there, NG just seems to care about the current value(s). I'll attach some screen shots.

![IMG_1106](https://github.com/user-attachments/assets/5d944940-d787-4536-b1db-8212fc3bdf9e)

![incoming-D1E21BF0-DA25-4EAB-B48B-3200276F00AE](https://github.com/user-attachments/assets/172258b0-2528-47a1-a300-71cda4806257)

**Comment by dhermanns** [comment]
It reads all data starting from the last item already read today:

https://github.com/nightscout/nightguard/blob/master/nightguard/external/NightscoutService.swift#L354

So normally It should catch up all missed data.

**Comment by poml88** [comment]
Hm, ok, well, it doesn't. :)

**Comment by dhermanns** [comment]
Would expect that you had some broken data so it could read only some values. As soon it has one value retrieved, it won't catch up older ones. Could be a manual measurement as well.

**Comment by poml88** [comment]
Hm... Well, it happens everytime after network interruption.
Maybe it depends on how the data is inserted into NS. 
So if network comes back, maybe first the libre3 will send the most recent value to LLU, which is then uploaded into NS. NG sees that and downloads it. Then the libre3 will send the historical data to LLU and they are added to NS. But NG "thinks" it is already at the latest data.
Something like this...

**Comment by dhermanns** [comment]
Yes - that would explain it. And maybe why I didn't recognize this. I'm using xdrip to catch and upload the bg values. This could be the reason also, why some people experience missing values in uploaded healthkit data.

You can simply verify this thesis by removing the optimization and get always the data starting from midnight. You will get duplicates, but shouldn't experience any more gaps.
