### ISSUE TITLE
Incorrect time in text complication

### ISSUE THREAD

**Issue by ermanitu** [nightscout/nightguard#310]
In text complication there is two problems.

first, time is incorrect, probably related to the actual timezone, as can be seen in the Image.

second, in some watchfaces, there is no space for all the text; I guess that it’s better to have bg in the first place because it is the more important data. Also can be seen in the image.

![IMG_8424](https://github.com/user-attachments/assets/7142aff2-57fc-438f-9b98-b74cfdeb14fb)

**Comment by dhermanns** [comment]
The time is the time the Bg Value has been retrieved.

But the visualization is really broken on this Watchface.

**Comment by ermanitu** [comment]
Seriously? Look at this screen:

![IMG_8425](https://github.com/user-attachments/assets/eb8925d8-d0e5-4dab-a2ef-5a83233cb882)

21:20 and last reading at 04:33?

or perhaps is the time since last reading? I.e. 4 min 33 sec? I’m that case, the best solution is tu removing seconds. It’s not relevant.

**Comment by dhermanns** [comment]
You are right - looks broken. I will have a look and prepare a testflight.

**Comment by ermanitu** [comment]
Thanks! It’s possible to have a TestFlight access to test the changes?

**Comment by dhermanns** [comment]
Sure:

https://testflight.apple.com/join/Ub8WcpcE

**Comment by dhermanns** [comment]
On complication with less space, the bg value only is displayed:

![Simulator Screenshot - Apple Watch Series 4 (40mm) - 2024-10-23 at 14 32 46](https://github.com/user-attachments/assets/911cd7a7-eb2e-4cda-8be1-c5da60de2191)

If there is more space, the age is displayed as a postfix:

![Simulator Screenshot - Apple Watch Series 4 (40mm) - 2024-10-23 at 14 32 31](https://github.com/user-attachments/assets/3bfa9784-c655-4cac-9645-caa1ccab577c)

**Comment by dhermanns** [comment]
3.9.3.912 will contain this feature in TestFlight. The TestFlight Link has changed. I will post the new link as soon as apple has approved the TestFlight.

**Comment by ermanitu** [comment]
Fantastic! Thanks.

**Comment by dhermanns** [comment]
You can test this now using TestFlight:
https://testflight.apple.com/join/zE4CfcRn

**Comment by ermanitu** [comment]
Now it’s perfect, thanks!

**Comment by dhermanns** [comment]
Excellent- thanks for your feedback
