### ISSUE TITLE
Cannot set temporary target with nightscout 15

### ISSUE THREAD

**Issue by khskekec** [nightscout/nightguard#311]
Hi,

Setting temporary target with nightguard does not work. Aaps client works as usual. The token was the same for both cases.

Can someone help?

Nightguard version is 3.9.2.

Kind regards

Selcuk

**Comment by dhermanns** [comment]
Hi! I'm using this setup on my own and it works fine.

But Aaps had made same changes here.
You have to enable it on Aaps to sync TempTargets wir nightscout.

**Comment by khskekec** [comment]
Nice to hear...

As I said: setting tts over aaps client just works why I think that aaps host is downloading data correctly. I can also see the tt in nightguard if this is originated from host or aaps client. But setting it over nightguard does not have any effects 😭.

Do you also use nightscout 15?

Thank you so much for your fast response ❤️

**Comment by dhermanns** [comment]
Aaps client uses a different mechanism nightscout can use. Can you set the Temp Target using the nightscout webclient?

**Comment by khskekec** [comment]
This is possible that ...

Like this??

![Screenshot_2024-09-06-17-28-12-997_com.android.chrome.jpg](https://github.com/user-attachments/assets/290cbbc7-a631-4b8b-bc65-3f546976f1b7)

**Comment by khskekec** [comment]
Ok solved... Had to use the old client instead of v3 api

![IMG_20240906_173645.jpg](https://github.com/user-attachments/assets/e0a04927-dee7-4ec2-8eae-8c624f4e60a7)

**Comment by dhermanns** [comment]
Great 👌
