### ISSUE TITLE
Large iPhone widget and "last updated" timestamp

### ISSUE THREAD

**Issue by Argon-** [nightscout/nightguard#312]
Greetings,

with a recent update, the larger iPhone widget went from a timestamp to displaying the minutes since the last update. I must admit though, for my use case, the simple timestamp worked better. My iPhone has an always-on screen and I usually glance at the dimmed screen without activating it. Herein lies my problem: with the good old timestamp there was never a surprise. I always knew if the values were old. With the relative time since last update however, I never know if the value is correct or if it just didn't update. Often when I touch the screen (activating it), it quickly updates. But that kind of defeats the purpose of not having to interact with the device and just glancing at it.
Now, on the flip side, the update reliability has definitely improved by a lot. So it's not that big of an issue and I guess many people are better served by the relative time. However, not updating occasionally still happens and the old timestamp simply gave me a lot more confidence.
Would it somehow be possible to make the timestamp/relative time a setting? Or maybe have both widgets?

Greatly appreciate your support and thanks for your work!

**Comment by dhermanns** [comment]
For me, the duration updates even if on lockscreen.

**Comment by Argon-** [comment]
>But it seems it updates immediately when just touching the screen (not unlocking).

Yes, same for me. But that means I have to touch the phone when I want a more-up-to-date reading. I might appear pedantic here 😅 but if I have to touch/grab the phone, I can also just launch the app through the action button or another shortcut. Not having to touch my phone, just have it sitting there on the desk in a meeting room, that's the game changer and unique selling point for me.
And the absolute timestamp gave me 100% reliability in this use case. It just can't be wrong.

>For me, the duration updates even if on lockscreen.

It also does for me, sorry if I made it sound like it doesn't. But not always. Sometimes it gets a little stuck, around once or twice a day*. And I won't know if it did until I grab/activate the phone. With an absolute timestamp this is not an issue.

* Fun fact: that's during the day. In the late evening, the update frequency goes down by a lot for me. Not a big deal at these hours but always makes me wonder/curious why this is the case.

**Comment by dhermanns** [comment]
Apple trys to learn when you use the app most and issues more background update during this time.

I think instead of using static timestamps one more time, the new live widgets maybe are the way to go.

And for sure, if you have one, the apple watch helps a lot to have always values at a glance.

**Comment by poml88** [comment]
In principle we could add a second widget, I assume we talk about the "systemSmall" type. It is just copying the code and put back the time. A user could then choose whatever widget is preferred or even both...

**Comment by dhermanns** [comment]
Since we have quite some config options, I would like to keep it simple. But If you would like to add another widget, it would make both sides happy ;-)

**Comment by Argon-** [comment]
>Apple trys to learn when you use the app most and issues more background update during this time.

That might actually be a problem because given the widgets work fine, I don't use the app all that much. 😅

I realize that duplicated code is not exactly what a developer favors in their code base. But as long as updates are not 100% reliable - and I pessimistically assume they will never be simply because of Apple's black box magic - the static timestamp was the only option that provided a 100% certainty/reliability without the need to verify if it really updated or not.

If it's too much hassle, I guess I could create my own version and run that self-signed on my phone. I'm not up do date with Apple's restrictions though as I'm not a macOS/iOS developer nor do I speak Swift. Do you still have to re-sign such an app every two weeks? I suppose the necessary change would need to go here? https://github.com/nightscout/nightguard/blob/f67e6769e9a87999d7b1a06e803af88e8e8574a3/nightguard%20Widget%20Extension/SystemSmallView.swift#L27 (remove the interval calculation).
Would need to wait until next year to try that because I currently don't own a still supported macOS version and thus don't have a recent Xcode/tool chain.

**Comment by poml88** [comment]
In any case, this is interesting.
I know from the watch that in always on mode but the app not being actively used the update frequency is reduced. This is clearly stated in the developer docs. But at least for the fitness app etc this is still every second or so. So you say the timer in the widget is not updated at all?
That would be very strange. From which iPhone model this always on mode is supported? I would like to play with that.

**Comment by Argon-** [comment]
Yes, that's my problem. I assumed that's normal. Is that not how it works for you?
Now, as mentioned, it's not always like that. It used to reliably update approximately 4 times per hour (each 15 minutes) for me. It rarely missed that 15 min deadline and in these cases  (when the static timestamp was >15min in the past) tapping the screen would often trigger an update. 

Now an additional issue (and reason for me to ask for the static timestamp) is that the relative timer sometimes stops being updated as well. It gets "stuck" at least once per hour. Actually, hard to say how often that happens because I don't tap the phone to check that often. In this case I would see e.g., "6 min..." and when I tap the screen it updates to "20 min...". That happens frequently enough that it feels like at least every second tap/wakeup of the phone screen makes the relative timestamp jump, sometimes significantly (20+ minutes). I also see a lot more >20 min times as I used to as previously it would update close to the 15 min mark for me.
 
I'm not sure if this may be related to iOS 18 though, at least the longer update intervals may be.
Also on this note, I've switched from a iPhone 14 Pro to a 16 Pro and either the phone or iOS 18 changed the font size on the homescreen. On top of that, there seems to be a weird blur creeping into the widget over time. Unfortunately, I've failed to make screenshots of the lockscreen so I made a photo:

![IMG_0067](https://github.com/user-attachments/assets/2aeeb4cc-e5ae-4384-b1be-ec6f1ffc3dad)
![IMG_0069](https://github.com/user-attachments/assets/972351e5-3828-4535-a07f-642c89bf05b2)

Considering that the number seems to be hanging in the air looks a bit like the screen update stopped halfway. Note that the blur can also occur within the text part and blur characters within "minutes" string. The longer the phone stays dormant, the more of the upper left string can blur up. But it's not clear cut. When it crosses the 20 min mark, a clear looking 2 may appear, while the rest of the string is blurry. 

Aaaand while writing this, I just found a beautiful instance of a 2 half-way transitioning into a 3 and getting somehow "stuck" in the process with also parts of the "minutes" being blurry:

![IMG_0072](https://github.com/user-attachments/assets/64c5f62a-a5b5-4667-859b-9f5e018339fb)

**Comment by poml88** [comment]
Oh, ok, we talking about "that" widget. That's the normal lockscreen widget. Looks like the font is too large.
It seems to me that Apple has to put some more work into theirs widgets and the always on thing.
I have an iPhone 12, so not using an OLED, and anyway, I usually use the watch...

**Comment by Argon-** [comment]
Oh sorry I probably didn't make that clear. Yes, I was talking about the larger widget on the lockscreen. I forgot for a second that you can have widgets on the home screen(s).

**Comment by poml88** [comment]
Indeed, on the always on locked it is updated less frequently, but still once per minute or so... And the type of timer seems to change.

**Comment by poml88** [comment]
Can we test in SwiftUI if we have the always on displayed? Then we can change the .timer to a normal time if always on is displayed... That would be the easiest.
Anybody knows? We do can detect if we have dark or light mode and other stuff, too.

**Comment by poml88** [comment]
Maybe something like this:
https://stackoverflow.com/questions/76640146/how-to-detect-always-on-display-in-swiftui-in-a-live-activity

**Comment by dhermanns** [comment]
I would prefer the additional timestamp widget. There will be people who prefer the relative time even on always on didplays.

So its more flexible and leaves the decision to the user.

**Comment by dhermanns** [comment]
I will implement the additional widget providing a fixed timestamp.

**Comment by Argon-** [comment]
Thank you so much!

**Comment by dhermanns** [comment]
I will keep this one open, so that I keep it in mind till its fully implemented 😉

**Comment by dhermanns** [comment]
Checkout the latest TestFlight and let me now if it works for you:
https://testflight.apple.com/join/Ub8WcpcE

**Comment by Argon-** [comment]
Awesome, thank you! I'm currently on a business trip, will be able to test it approx. end of the week :)

**Comment by Argon-** [comment]
Works great! Thanks!

**Comment by dhermanns** [comment]
Thanks for your feedback. Happy to hear. A new release is coming up soon.
