### ISSUE TITLE
URL disappeared 

### ISSUE THREAD

**Issue by Kym1593** [nightscout/nightguard#315]
Hi the url on my night guard has disappeared I can’t get it back even if I delete and down load again I have no idea how to get the url back.

**Comment by dhermanns** [comment]
Do you have a screen shot?

**Comment by Kym1593** [comment]
Hi,

Yes I do I’ve attached it to this email.

**Comment by dhermanns** [comment]
You can't send this via email - you would have to attach it to the ticket.

**Comment by Kym1593** [comment]
![IMG_1421](https://github.com/user-attachments/assets/a54eb203-130e-430f-8419-1008f4eaeb77)
![IMG_1422](https://github.com/user-attachments/assets/9beb06ca-1abd-4fd2-8b1e-9d5003ce01c0)

**Comment by dhermanns** [comment]
This is strange. I can't reproduce it here. Maybe you can try this on a different device?
