### ISSUE TITLE
iwatch does not show any BG value anymore intermittently

### ISSUE THREAD

**Issue by Evs-nazgul** [nightscout/nightguard#316]
Hello,

I used to test the beta version of version 3.9.2.906. Since it has been released "officially" I experience several times a day issues with the value display on my IWATCH 7.  The value is gone, no more display in the gauge nor text widget; When I tap on my iwatch , it used to shoz the graphic trend and the current value.  Very often, the value is shoz and immediately disappears; I noticed the shozn value is not accurate and an old value. From time to time I see the NIGHTGUARD icoon displayed with a progress bar circulating, and then everything disappears.

I re-installed nightguard on the iwatc, sometimes it last for a day , maybe 2, sometimes not even for an hour.

I have really no idea what causes this and trying to figure it out. 

I made a little video to illustrate and would appreciate if anyone has the same issue and has a solution. 

https://github.com/user-attachments/assets/5e40dc6a-582e-4207-9e9c-8a5e6bafa35f

It worked fine, with the beta version, it started failing since the day the beta was officially released.

**Comment by dhermanns** [comment]
Looks like something is causing the app to crash. At what exact time where you able to cause this crash?

**Comment by Evs-nazgul** [comment]
It acts as shown whole day long. And when I get it to work after re-installation of nightguard on the iwatch, it is a matter of tile before it restarts crashing, sometimes immediately, sometimes hours later.Nightguard works perfectly on my iphone.ErwinOp 22 okt 2024 om 21:46 heeft dhermanns ***@***.***> het volgende geschreven:﻿
Looks like something is causing the app to crash. At what exact time where you able to cause this crash?

**Comment by Evs-nazgul** [comment]
![IMG_2628](https://github.com/user-attachments/assets/716922a3-16d4-42f6-b0e8-102bf6623c91)
![IMG_2629](https://github.com/user-attachments/assets/a7c41969-aa05-4269-926c-4f969f32f562)

**Comment by Evs-nazgul** [comment]
Update:  I noticed that when I switch off and back on my Iwatch, the readings are normal.  Now, additionaly after some days of testing, it seems I need to switch off and on every day mostly around the same time the iwatch.  Is there something in the recent code that requires a reset or restart for whatever reason? Because after the restart of the watch, it works fine for somewhat more then 24hours.

**Comment by dhermanns** [comment]
You should try to switch to the latest TestFlight:
https://testflight.apple.com/join/zE4CfcRn

Let me know if this eliminates the crashes. Sometimes new iOS Updates introduce some strange behavior. Maybe this is such a case.

**Comment by Evs-nazgul** [comment]
Installed testflight and testing, keep you postedIphone has ios version 17.6.1Iwatch runs version watchos 10.6.1Thanks in advance ErwinOp 25 okt 2024 om 19:08 heeft dhermanns ***@***.***> het volgende geschreven:﻿
You should try to switch to the latest TestFlight:
https://testflight.apple.com/join/zE4CfcRn
Let me know if this eliminates the crashes. Sometimes new iOS Updates introduce some strange behavior. Maybe this is such a case.

**Comment by Evs-nazgul** [comment]
Small update on new testcase:  since installation on friday, no more hangs nor hickups of data transmittions sofarErwi Op 25 okt 2024 om 19:08 heeft dhermanns ***@***.***> het volgende geschreven:﻿
You should try to switch to the latest TestFlight:
https://testflight.apple.com/join/zE4CfcRn
Let me know if this eliminates the crashes. Sometimes new iOS Updates introduce some strange behavior. Maybe this is such a case.

**Comment by djrob1010** [comment]
My watch does not crash. Rather I had 1 Apple Watch 6. Worked fine. Ran into battery issue so watch was replaced. After installing new watch text no longer transfers from night guard to watch. I get the graph bar in blue and ?? Right above it where glucose reading should be. Using latest vision of iOS watch os. Can you help me solve this? Gluroo is feeding correct value to Nightguard

**Comment by dhermanns** [comment]
Hi! Normally this is fixed by reinstalling just the watch part of nightguard. Or by entering the nightscout url manually on the watch app.

**Comment by djrob1010** [comment]
So if I uninstall Nightguard and reinstall I should be fine?Sent from my iPhoneOn Oct 31, 2024, at 12:43 PM, dhermanns ***@***.***> wrote:﻿
Hi! Normally this is fixed by reinstalling just the watch part of nightguard. Or by entering the nightscout url manually on the watch app.

**Comment by dhermanns** [comment]
Just the watch part could be enough. You can do this in the Watch-App on your iPhone.

**Comment by djrob1010** [comment]
I checked and the night guard app pulls blood sugar if open it on watch. But the data does not appear on the watch face.Sent from my iPhoneOn Oct 31, 2024, at 1:17 PM, dhermanns ***@***.***> wrote:﻿
Just the watch part could be enough. You can do this in the Watch-App on your iPhone.

**Comment by dhermanns** [comment]
Does the watch app has your nightscout URL?

**Comment by djrob1010** [comment]
So there are 4 apps on iPhone1 Libre app2 Libre link up app3 Gluro4 NightguardI uninstalled Nightguard on phone re installed it copied and pasted the link from Gluroo. I can get the Nightguard app to show value on watch. But when on the face nothing? Sent from my iPhoneOn Oct 31, 2024, at 1:17 PM, dhermanns ***@***.***> wrote:﻿
Just the watch part could be enough. You can do this in the Watch-App on your iPhone.

**Comment by djrob1010** [comment]
Ok it’s working now 👍Sent from my iPhoneOn Oct 31, 2024, at 1:35 PM, Robert Young ***@***.***> wrote:﻿So there are 4 apps on iPhone1 Libre app2 Libre link up app3 Gluro4 NightguardI uninstalled Nightguard on phone re installed it copied and pasted the link from Gluroo. I can get the Nightguard app to show value on watch. But when on the face nothing? Sent from my iPhoneOn Oct 31, 2024, at 1:17 PM, dhermanns ***@***.***> wrote:﻿
Just the watch part could be enough. You can do this in the Watch-App on your iPhone.

**Comment by djrob1010** [comment]
Ok so now my phone has 111 which was an earlier reading with a line through it. The app has not refreshed and pulled sugar readings for about 40 minutes. What my libre says is not what’s in GlurooSent from my iPhoneOn Oct 31, 2024, at 1:31 PM, dhermanns ***@***.***> wrote:﻿
Does the watch app has your nightscout URL?

**Comment by djrob1010** [comment]
I need helpSent from my iPhoneOn Oct 31, 2024, at 1:35 PM, Robert Young ***@***.***> wrote:﻿So there are 4 apps on iPhone1 Libre app2 Libre link up app3 Gluro4 NightguardI uninstalled Nightguard on phone re installed it copied and pasted the link from Gluroo. I can get the Nightguard app to show value on watch. But when on the face nothing? Sent from my iPhoneOn Oct 31, 2024, at 1:17 PM, dhermanns ***@***.***> wrote:﻿
Just the watch part could be enough. You can do this in the Watch-App on your iPhone.

**Comment by djrob1010** [comment]
Changed all my passwords uninstalled and reinstalled all apps blood sugar readings still not being refreshedSent from my iPhoneOn Oct 31, 2024, at 3:49 PM, Evs-nazgul ***@***.***> wrote:﻿
I also had a good working gluroo, nightguard (on the iphone) and libre app.When I looked at the iwatch, no data shown on BG , when I touched the iwatch face , the nightguard opened and showed graph and bg value, next it started refreshing and closed the nightguard app.After installing the latest test version , I had no more issuesErwinOp 31 okt 2024 om 20:01 heeft djrob1010 ***@***.***&gt; het volgende geschreven:﻿
<br>
Ok so now my phone has 111 which was an earlier reading with a line through it. The app has not refreshed and pulled sugar readings for about 40 minutes. What my libre says is not what’s in GlurooSent from my iPhoneOn Oct 31, 2024, at 1:31 PM, dhermanns ***@***.***&amp;gt; wrote:﻿
<br>
&lt;br&gt;
<br>
Does the watch app has your nightscout URL?
<br>
&lt;br&gt;
<br>

<br>
&lt;br&gt;
<br>
—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***&amp;gt;
<br>

<br>

**Comment by Evs-nazgul** [comment]
Maybe you try the test flight version I got  To see if this makes a differenceOp 31 okt 2024 om 21:23 heeft djrob1010 ***@***.***> het volgende geschreven:﻿
Changed all my passwords uninstalled and reinstalled all apps blood sugar readings still not being refreshedSent from my iPhoneOn Oct 31, 2024, at 3:49 PM, Evs-nazgul ***@***.***&gt; wrote:﻿
<br>
I also had a good working gluroo, nightguard (on the iphone) and libre app.When I looked at the iwatch, no data shown on BG , when I touched the iwatch face , the nightguard opened and showed graph and bg value, next it started refreshing and closed the nightguard app.After installing the latest test version , I had no more issuesErwinOp 31 okt 2024 om 20:01 heeft djrob1010 ***@***.***&amp;gt; het volgende geschreven:﻿
<br>
&lt;br&gt;
<br>
Ok so now my phone has 111 which was an earlier reading with a line through it. The app has not refreshed and pulled sugar readings for about 40 minutes. What my libre says is not what’s in GlurooSent from my iPhoneOn Oct 31, 2024, at 1:31 PM, dhermanns ***@***.***&amp;amp;gt; wrote:﻿
<br>
&lt;br&gt;
<br>
&amp;lt;br&amp;gt;
<br>
&lt;br&gt;
<br>
Does the watch app has your nightscout URL?
<br>
&lt;br&gt;
<br>
&amp;lt;br&amp;gt;
<br>
&lt;br&gt;
<br>

<br>
&lt;br&gt;
<br>
&amp;lt;br&amp;gt;
<br>
&lt;br&gt;
<br>
—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***&amp;amp;gt;
<br>
&lt;br&gt;
<br>

<br>
&lt;br&gt;
<br>
—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***&amp;gt;
<br>

<br>

**Comment by dhermanns** [comment]
Looks like the current TestFlight fixed this
