### ISSUE TITLE
Apple Watch not showing Graph... Here's the Fix. Developer Please.

### ISSUE THREAD

**Issue by ddt714** [nightscout/nightguard#318]
I’m having a problem on my Apple Watch email to get to the developer of the Nightguard iPhone/iWatch Application.

The problem is that on the Apple Watch the Glucose reading Rectangular graph doesn’t show up as an option in the complications to place on the Home Screen for a rectangular complication on the Modular Watch face. (any watch face)

I spent an Hour at the Apple Store with a Technician looking at the application code. This tech happened to be an App developer himself.

Basically if you take the “.accessoryRectangular” piece of code from line 54, copy it, and place it on line 78, just under “.accessoryCircular” Me and everyone else who has an Apple Watch will be able to view the glucose graph readings directly from the watches Home Screen as a rectangular complication with the graph on the watch face.

This would be really helpful to add to the Apple Watch to see the graph easier at a glance on our wrists. 

Check the picture to see the spot to change/fix.
![IMG_2253](https://github.com/user-attachments/assets/18d7316e-461b-40d4-bae2-3e5b49add879)

Thank you & hope this helps,

Derek

**Comment by dhermanns** [comment]
Hi Derek! The GaugeWidget just shows a gauge, not a graph. Right now a Graph ist not supported on any widget. But there is already a ticket asking for it. But till now, no one has found the time to implement it.

**Comment by dhermanns** [comment]
![image](https://github.com/user-attachments/assets/d0e01a5a-f682-4d66-a5fc-77183df7a37e)

And the rectangular widget can already be used on the modular watchface.

**Comment by ddt714** [comment]
Yah but the above fix should be able to show the directional graph instead of just the numbers.

**Comment by dhermanns** [comment]
Can you show an image of what directional graph you mean?

**Comment by ddt714** [comment]
This one here:

![IMG_2953](https://github.com/user-attachments/assets/d6106a7f-81c1-48ff-8363-8e28c33d1786)

**Comment by dhermanns** [comment]
Ok great. Than we are definitely talking about the same thing. The suggestion won't work in that case. This is definitely no simple one line change 😉. Sorry.
