### ISSUE TITLE
How to change unit of measurement. With mg(100-180) on mmol (4.9-6.8).

### ISSUE THREAD

**Issue by viktorily** [nightscout/nightguard#319]
How to change unit of measurement. With mg(100-180) on mmol (4.9-6.8). Hello app works great . But there's a problem. Installed today on apple watch se. First showed sugar in mmol. After a couple of hours began to show mg (example: 100-180). How can you return back to mmol (example 5.9-6.8 mmol)😭🙏🏻🙏🏻

**Comment by dhermanns** [comment]
Hi! Normally this is determined from your nightscout backend. If this is not configured correctly, you can overrule this in the app settings. Have you tried to force mmol there?

**Comment by viktorily** [comment]
Thank you very much ! Everything works
