### ISSUE TITLE
Slider for selecting alarm values

### ISSUE THREAD

**Issue by marcosdetry** [nightscout/nightguard#40]
I think that the slider for the alarm that goes in steps of 10 is to much. I agree that step of one as before was not precise nor practical, but for example I usually want my alarm at 65. Steps of 5 would be great. The steps could be a configurable value to suit all needs, or 5 that I think it's a better value than 10 for most cases

**Comment by dhermanns** [comment]
I‘m currently working on a new Snooze Screen that is easier to read. That
will contain 45min, too ;-)
Florian Preknya <notifications@github.com> schrieb am So. 22. Apr. 2018 um
10:16:

**Comment by dhermanns** [comment]
It should be fine now in the current Version 2.6 now.
