### ISSUE TITLE
iOS 12/Watch OS 5

### ISSUE THREAD

**Issue by mjphillips20** [nightscout/nightguard#41]
Nightguard does not work on either of these. Insta-crashes when opened on phone or watch. I realize this most likely has not been optomized for these but wanted to give you a heads up.

**Comment by dhermanns** [comment]
I didn’t have installed the beta versions. Good to know that Apple has broken something. I will install it before it’s going to be golden Master.

**Comment by dhermanns** [comment]
I was able to upgrade to IOS12/WatchOS 5 Beta 12. Seems like apple has fixed the incompatibility issues. The app works fine for me now. Without having to change anything.

Feel free to open up again, if this error still exists for you...

**Comment by mjphillips20** [comment]
Looks like it was fixed the next beta. Everything works great again. I appreciate your follow up on this.
