### ISSUE TITLE
App is crashing when URI containing authentication token

### ISSUE THREAD

**Issue by verunightscout** [nightscout/nightguard#42]
On iPhone with iOS 11.3 right after entering URL of my NightScout server into Preferences. Then it crashes every time when I start the app.

**Comment by dhermanns** [comment]
YouTube could leave meine your URI and I will see if I can reproduce it.

**Comment by verunightscout** [comment]
https://veru.herokuapp.com/

**Comment by dhermanns** [comment]
Ah ok - you are entering the URI with an access token included? We already have a pull request for this, but it doesn't compiles right now. So I can't integrate it. I'm not using access tokens myself. So I can't test this.

**Comment by dhermanns** [comment]
This is the Pull Request:
https://github.com/nightscout/nightguard/pull/29

Maybe you could help to integrate this.

**Comment by verunightscout** [comment]
Thanks for info, this will be cool if you add that to app. 
I changed AUTH_DEFAULT_ROLES to readable, but still it doesn´t work. Error is now The request timed out, this is because I don´t have any data there ?

**Comment by dhermanns** [comment]
The current beta release 2.3 should fix this. Security tokens are supported as soon as it gets to the store. Feel free to twitter me you email to add you as beta testers...
