### ISSUE TITLE
The request timed out.

### ISSUE THREAD

**Issue by verunightscout** [nightscout/nightguard#43]
With web browser I´m able to open the site. I currently have AUTH_DEFAULT_ROLES set to readable, then no authentication is needed. Site is on Heroku ( free ) , if I open the site for the first time, it takes couple of seconds to open.

Thanks for help.

**Comment by dhermanns** [comment]
I have your URI and will see whether I can reproduce this.

**Comment by dhermanns** [comment]
I just tried it. But I don't get any values. Even not when using the browser. So it seems to me like a general problem on your backend side.

**Comment by verunightscout** [comment]
Hi, you don´t get numbers because I´m in preparation phase and haven´t uploaded data yet. My only concern is that your app shows error ( The request timed out ) , but other  like Nightscouter shows that there aren´t data , but without any error. Your application need non zero data to be working ?

**Comment by dhermanns** [comment]
The ios app simply doesn't display any values if no values can be retrieved. The watchos app wants to parse the data and for me shows 

"Unknown error while trying to extract data"

error. Let us know when you have data in your backend. We can see if that turns out to be a problem.

**Comment by dhermanns** [comment]
Closed due to inactivity. I think we already have an improved behavior with less warnings now.
