### ISSUE TITLE
Glances -  My watch

### ISSUE THREAD

**Issue by francescaneri** [nightscout/nightguard#5]
Good morning , I wanted to ask if it was possible to view the application in Glances, and if you could also add raw. The immagne is just an example . thanks and good job. Matteo

**Comment by francescaneri** [comment]
![img_20160910_133049](https://cloud.githubusercontent.com/assets/9915825/18410322/3999d340-775f-11e6-8307-12eff4c767f6.jpg)

**Comment by dhermanns** [comment]
HI Matteo!

Thanks for the input, but glances will not be available at all with watchOS
3 anymore. But I will add support for complications which should work much
better in watchOS 3.

What are you using the raw values for? I'm not using them and I think the
space on the screen would be too valuable if just a few people are using
them...

Cu,
Dirk
Matteo Neri <notifications@github.com> schrieb am Sa. 10. Sep. 2016 um
14:03:

**Comment by francescaneri** [comment]
Hi, @dhermanns 
I am currently using iphone 5 - ios 10 pubblic , and iwatch 1 version 2.2.2 .
By the looks it remains more comfortable the clock reference. As for the raw data I'm using DexCom G4 . The app uses my 7 year old daughter recently and is well. congratulations again for the application .

**Comment by francescaneri** [comment]
question: the iPhone's alarm sound you can also have sull'watch ?

**Comment by dhermanns** [comment]
No - right now Apple has noch WatchOS Api to control the speaker using
custom apps :-(
Matteo Neri <notifications@github.com> schrieb am Sa. 10. Sep. 2016 um
20:36:
