### ISSUE TITLE
IOS 12 Shortcuts app not listing Nightguard

### ISSUE THREAD

**Issue by HappyFlyBoy** [nightscout/nightguard#50]
I am using the new Shortcuts app to try to write a script that turns my screen brightness down, turns my volume up and then launches Nightguard. In the “open app” step Nightguard is not listed. I suspect it is because the app doesn’t have a url scheme.

**Comment by dhermanns** [comment]
Sounds like a great idea. I haven’t any experience with the Shortcuts App
but will have a look at it.
HappyFlyBoy <notifications@github.com> schrieb am Fr. 21. Sep. 2018 um
07:21:

**Comment by dhermanns** [comment]
Yes - that was exactly the case. Thanks for your hint. Current version 2.1.2 now supports the shortcuts app. It will be available soon. Setting the brightness and volume before starting the app is a very useful feature for the nightguard app!

**Comment by dhermanns** [comment]
Here the new feature in action:
https://youtu.be/HLP5knr9z0Y

**Comment by HappyFlyBoy** [comment]
Thanks is fantastic!  Thank you so much!  We love nightguard it has literally been a lifesaver!

Greg

**Comment by HappyFlyBoy** [comment]
Thought you might be interested in this, I used some code from another shortcut, this will have Siri read your BG number. 

Check out the shortcut I built! What’s My Blood glucoses


Greg
