### ISSUE TITLE
App not showing up on Apple Watch 

### ISSUE THREAD

**Issue by rmgarrido** [nightscout/nightguard#51]
Nightguard does show as an option to install on Apple watch 4. I’m using iPhone XS. Please advise.

**Comment by dhermanns** [comment]
Hi! My Apple Watch 4 will arrive tomorrow. So I will be able to test it. Right now, it has been designed for Series 1 to 3 only.

But support will be available soon.

**Comment by rmgarrido** [comment]
Thanks. Looking forward to update. Love the app!

**Comment by dhermanns** [comment]
Thanks. I was able to test now on a Series 4. The app looks ugly right now, but starts up fine. What is exactly your error you are getting?

**Comment by rmgarrido** [comment]
The app is now installable on Series 4 with new update. Thank You!

**Comment by dhermanns** [comment]
Great. The new version 2.2 will support the new Watches and the new complications. It's coming soon.
