### ISSUE TITLE
App crashes after entering nightscout URL

### ISSUE THREAD

**Issue by niepi** [nightscout/nightguard#54]
- installed  2.2 fresh from Appstore
- after entering NS URL without Auth Token the app crashes
- restarting/opening the app crashes the every time

NS URL: https://*****.herokuapp.com
iPhone 8, iOS 12.1

**Comment by dhermanns** [comment]
Hi Thomas - hard to say what is causing this. It has something to do with your backend. You can send me your Uri to my twitter handle @h3rmanns.

**Comment by niepi** [comment]
Ok, thanks for the answer. I will close the issue and subscribe to the PR, to test when this is merged
