### ISSUE TITLE
High BG showing when in range 

### ISSUE THREAD

**Issue by harryrowe2010** [nightscout/nightguard#59]
High BG is shown in red text at bottom of watchface even though BG is within range (uk mmol)

**Comment by florianpreknya** [comment]
I'll take a look on this one of these days. Thanks @harryrowe2010 !

**Comment by dhermanns** [comment]
Hi Debbie!

Florians fix is on the way to the app store. You should get a new Testflight version soon...

**Comment by dhermanns** [comment]
I think this should be fixed with the current version 2.4 now. Otherwise - let us know ;-)

**Comment by harryrowe2010** [comment]
Yes all fixed

Thanks very much 👍🏻
