### ISSUE TITLE
Refresh rate?

### ISSUE THREAD

**Issue by patrickchoi** [nightscout/nightguard#6]
What is the refresh rate of the Nightguard app? I can see the values updated on my iPhone but despite constant refreshing on my Watch, I cannot see the updated values. Is there a configuration setting somewhere?

**Comment by dhermanns** [comment]
Hi Patrick,

do you see no updates at all on your watch? The watch will check for new
values as soon as your displayed values are older than 5 minutes.
Patrick Choi <notifications@github.com> schrieb am Do. 8. Dez. 2016 um
13:19:

**Comment by patrickchoi** [comment]
Yeah, the screen shows "> 1 hr" for the last reading, but the iOS app has been updated.

On the watch, using Force Press to bring up the refresh button doesn't appear to affect anything. It wasn't until I killed the app on the dock and reopened it did the new values show.

**Comment by dhermanns** [comment]
Strange - maybe you can leave me your uri, so I can try to reproduce this.
What Apple Watch do you use? Series 1/2, 38/42mm?
Patrick Choi <notifications@github.com> schrieb am Do. 8. Dez. 2016 um
13:59:

**Comment by dhermanns** [comment]
If you have some more informations - feel free to reopen...
