### ISSUE TITLE
Missed reading when access denied

### ISSUE THREAD

**Issue by gabriellm1** [nightscout/nightguard#61]
I have installed the Nightguard at my moms iPad so at night she can see my bg. The problem is that I don't want her to be able to see bg values all day long, then I configured Nightscout token so I can permit her iPad to have the readings. 

With that problem solved, another one appeared. The Nightguard will have an alarm for missed readings but I don't see where I can deactivate it.

The solution already exists ?

**Comment by dhermanns** [comment]
Hi! You can configure the duration after which you would like to get Alarms for missed values on the Alarm Tab. You can go up to 45 Minutes. If you like, we could rise that to a longer duration.

**Comment by gabriellm1** [comment]
There is no possibility to implement a disable button? This would be nice for  a "follower" user of the app

**Comment by dhermanns** [comment]
possible is everything ;-) I will have a look...

**Comment by florianpreknya** [comment]
@dhermanns please leave this task to me, I already changed the UI in the alarm screen. I'll give you more details tomorrow.

**Comment by dhermanns** [comment]
Great 👍
Florian Preknya <notifications@github.com> schrieb am Mo. 25. Feb. 2019 um
01:57:

**Comment by dhermanns** [comment]
@gabriellm1 : If you send me your email, I can add you to the group of beta testers for it. Or you could wait until we do an official release of it...

**Comment by gabriellm1** [comment]
That's awesome, please send me at gabriellopesmonteiro41@gmail.com
