### ISSUE TITLE
Nightguard complication on apple watch

### ISSUE THREAD

**Issue by CasousaM** [nightscout/nightguard#67]
Hello. I would like to know what I have to do to the nightguard complication update by itself. In my apple watch, the complication refreshes only when I get in to the app

**Comment by dhermanns** [comment]
Hi! This is a general question about how you make watchOS Apps run in background. You will find articles on the web discussing how you prevent apps from doing that - because it comes (a little bit) at the costs of battery life.

Maybe I find the time to write an own article of that...

**Comment by dhermanns** [comment]
I have written something about how to enable the background updates:
https://medium.com/@h3rmanns/enabling-background-updates-for-you-iphone-and-watch-4b8167a70b24

Have a look - hopefully that helps.

**Comment by kaptepia** [comment]
Appreciate you documenting this but background updates being disabled doesn't seem to be the issue for us. The data is on the phone app but only comes through to the watch and complication after the Watch App is opened. Any more tips?

**Comment by dhermanns** [comment]
Sorry but not really. You can have a look at the info popup screen at the watch. Normally there is a detail log of all background updates executed. Maybe that gives you some insights.

**Comment by michel-numan** [comment]
Happening to me too.
Background app refresh scheduled  (interval every 10m) but never updates the widget unless i open the watch app itself

**Comment by dhermanns** [comment]
How did you schedule the 10min intervall?
