### ISSUE TITLE
Apple Watch missed reading alerts despite setting disabled in app

### ISSUE THREAD

**Issue by matthewstathis** [nightscout/nightguard#70]
Even though I disable the missed readings alert setting in the iPhone app, my Apple Watch will still give a haptic feedback tap for missed readings (ie. when I disconnect my nightscout setup to recharge). Even if my watch is locked and on its charger, there’s still random haptic feedback coming through because of the missed readings. And for some reason, even if I snooze alerts for 24 hours (to stop the haptic feedback alerts), it always seems to shorten that to a few hours at most and then starts buzzing/tapping on my wrist again...

**Comment by dhermanns** [comment]
Yes - i noticed that too. I think we have two issues here:

1) the watch doesn‘t store the snooze state right now. If watchos kills it, the selected snooze gets disabled, too.

2) the configuration of the missed readings from the ios app doesn‘t get synchronized to the watch.

Workaround is to do a long snooze on the watch and keep the app in foreground.

I will see if I can find some time to improve this.

**Comment by dhermanns** [comment]
Ah - didn't saw florians PR. Excellent @florianpreknya. Incredible fast as ever ;-)
