### ISSUE TITLE
12 hour clock

### ISSUE THREAD

**Issue by craigpress** [nightscout/nightguard#73]

**Comment by craigpress** [comment]
Can we have an option for a 12 hour or AM/PM clock?  This would make it easier to just look at watch os complication and know what time the last check was.

**Comment by dhermanns** [comment]
The complication already shows this information. It takes less space to show 23:12 instead of 11:21 pm. The space is very limited, especially for the complication.

**Comment by craigpress** [comment]
Is there a way to not show the AM/PM and just the 12 hr time as a option? I can tell AM vs PM faster than calculating afternoon times? I am just appreciative of all the work you put into this. So much better than Dexcom follow app and their useless complication!


________________________________

**Comment by dhermanns** [comment]
I don‘t like too many options and buttons. But we can align this visualization to your ios settings. If we omit the am/pm information this shouldn‘t bring us layout problems.

**Comment by craigpress** [comment]
That would be great. I appreciate the simplicity and benefit of streamlining the app, so it it is possible that would be appreciated by many I suspect. If not it clearly isn’t a critical element.

Craig


________________________________

**Comment by dhermanns** [comment]
The next upcoming version V2.7.5 will have this feature. There will be a german, english and finish translation, too.

Have fun!

**Comment by craigpress** [comment]
Great!

________________________________
