### ISSUE TITLE
Not Featured On Nightscout Website

### ISSUE THREAD

**Issue by DonaldBough** [nightscout/nightguard#74]
Hello,

I only came across this app by looking through the nightscout repos, because it isn't documented anywhere on the official nightscout website. I ran into an older, un-maintained iOS client here http://www.nightscout.info/wiki/welcome/nightscout-for-ios-optional but it's apparent this should obviously be in its place. 

Does anyone know how to get this repo onto the main nightscout website so you can all get more visibility onto your app?

**Comment by dhermanns** [comment]
Hi Donald, you are right. We should be mentioned there. I already asked for it, but doesn‘t happen till now. @jasoncalabrese: Do you know who could mention our ios client there?

**Comment by dhermanns** [comment]
Too bad - but I tried to place nightguard there. But didn't get any respone :-/
