### ISSUE TITLE
Feature Requirement: Integrate Carbs from Healthkit

### ISSUE THREAD

**Issue by DonaldBough** [nightscout/nightguard#75]
_(figured I would open this question on a different issue)_

Has adding carbs from Healthkit into Nightscout been considered before? I realize the great difficult Spike has experienced with Apple lately, so I would understand if that is a reason why carbs from Healthkit haven't been considered yet. 

The inspiration for this came from me regularly logging food into MyFitnessPal, and then having to enter the carbs from those foods into Nightscout. I could see a lot of use from letting the two communicate, and would be willing to add on the feature as long as everyone thinks the idea is okay.

Thanks!

**Comment by dhermanns** [comment]
I would be surprised if that would cause trouble. But I have no experience with health kit access policies and how apple handles it.

**Comment by DonaldBough** [comment]
So the Healthkit policies from [here](https://developer.apple.com/documentation/healthkit/protecting_user_privacy) and [here](https://developer.apple.com/app-store/review/guidelines/) essentially say as long as it's soley for benefit of the user we're okay. I'll go ahead and take a crack at it this week and hopefully send a PR or ask some more questions soon.

**Comment by dhermanns** [comment]
And that’s definitely the case here.

**Comment by dhermanns** [comment]
For me the way is to go with AAPS and directly add carbs there. Because you definitely need these informations for the closed loop to work fine. So I see the carbs closely tied to nightscout and not to healthkit or other apps. Sorry.
