### ISSUE TITLE
Alerts 

### ISSUE THREAD

**Issue by adirazran** [nightscout/nightguard#76]
On iphone while the app at the background I’m not getting any alerts, only when I’m opening the app, is it a bug ? How can I get alerts when my phone is in my pocket .. it’s very important ( I did all the correct setting and still is not working ) many thanks

**Comment by dhermanns** [comment]
Hello! Have you enabled background updates on your phone?

Have a look here. Maybe that helps:
https://medium.com/@h3rmanns/enabling-background-updates-for-you-iphone-and-watch-4b8167a70b24

**Comment by adirazran** [comment]
Of course .
Still not working on iphone 

I try already Nightscouter+Nightguard and enable sleep mode 
And still no alert 
I tried with 3 different iphone 
Still ... nothing 

Thanks,
Adir.

**Comment by dhermanns** [comment]
Then - tell us how your settings in your nightguard app are. Screenshots would be nice.

**Comment by adirazran** [comment]
Thanks,
Adir.

**Comment by adirazran** [comment]
Any news ?


Thanks,
Adir.

**Comment by dhermanns** [comment]
Did you send us Screenshots showing your nightguard settings?

**Comment by adirazran** [comment]
Of course 
I will send again 

Here


Thanks,
Adir.

**Comment by dhermanns** [comment]
You can’t send them by eMail. You will have to link them directly in the github issue.

**Comment by adirazran** [comment]
How can I link my screen shot to the forum 

Thanks,
Adir.

**Comment by dhermanns** [comment]
https://stackoverflow.com/questions/10963205/how-to-attach-file-to-a-github-issue/10963250#10963250

**Comment by jizhongwen** [comment]
![back](https://user-images.githubusercontent.com/25942874/61952458-7d3d0280-afe6-11e9-9e31-f103ac271018.jpg)
![微信图片_20190726204117](https://user-images.githubusercontent.com/25942874/61952459-7dd59900-afe6-11e9-9205-72a41310bf6f.jpg)
![微信图片_20190726204135](https://user-images.githubusercontent.com/25942874/61952462-7dd59900-afe6-11e9-9b90-1b0656ec89c2.jpg)
![微信图片_20190726204141](https://user-images.githubusercontent.com/25942874/61952463-7e6e2f80-afe6-11e9-84c1-06e242047727.jpg)
![微信图片_20190726204146](https://user-images.githubusercontent.com/25942874/61952464-7f06c600-afe6-11e9-8f0f-e068623868b8.jpg)
![微信图片_20190726204151](https://user-images.githubusercontent.com/25942874/61952465-8037f300-afe6-11e9-89f3-510fbc368e7d.jpg)
![微信图片_20190726204210](https://user-images.githubusercontent.com/25942874/61952466-8037f300-afe6-11e9-97d7-3d28b925869c.jpg)
![微信图片_20190726204445](https://user-images.githubusercontent.com/25942874/61952467-80d08980-afe6-11e9-91b6-8ecdbd4b25b1.jpg)
The alarm did not work after put this app in the background, I tried many times. It stayed on Snoozed for 1min when I opened this app, and then alarm.  Thank you for help, I hope this isse can be resolved.

**Comment by dhermanns** [comment]
Looks good to me. Only thing could be: how did you set your background
updates? For Wifi only?

**Comment by adirazran** [comment]
No , also data and WiFi 
It’s mean all update should push and only this no..
I already tried this in 5 different iphone .. it seems that push not working 
Only when the app is open it’s work 


Thanks,
Adir.

**Comment by jizhongwen** [comment]
![wifi](https://user-images.githubusercontent.com/25942874/61960001-37d50100-aff7-11e9-8b16-bacd75678c00.jpg)
Also data and wifi. In the appstore, only nightguard support alarm. I hope it can work. DM need it. Thanks for your quick response

**Comment by adirazran** [comment]
So what to do
Is there is any option that I will get alarm without open the app all night ? 
Can’t it work like Whatsup ?... 

All my setting is correct 
But still .. push doesn’t work .. 
I think the developer should fix the issue it’s not that my setting are not correct 
Waiting for help 


Thanks,
Adir.

**Comment by dhermanns** [comment]
You would need a server side pushing service to achieve reliable push
notifications like used from whats app.

You can configure something like pushover on your nightscout backend to do
so.

Nightguard needs to depend on what apple allows us to do. We already had
others here that don‘t get any background updates at all. But I can’t
reproduce it on my side.

Therfore can‘t fix it. Sorry.

**Comment by Lakomova** [comment]
The alarm is not working, I tried different settings and checked my iphone settings also. It stayed on Snoozed for 1min. But when I open the app, alarm is working. What’s wrong?

**Comment by dhermanns** [comment]
Hard to tell. Background updates are under the control of apple. We get
update time if apple lets us.

Lakomova <notifications@github.com> schrieb am So. 15. Sept. 2019 um 12:57:

**Comment by iteemh** [comment]
I have a similar problem. The app does not push notifications/alerts when it is not open.

**Comment by dhermanns** [comment]
Have a look at the answers here. If all doesn‘t help - use something like pushover to have real push notification. Nightguard can do only background updates and this is limited by design.

**Comment by Babuci1** [comment]
Hello! Could you tell me which iPhone works with Nightguard and iwatch. I have the same issue as "adirazran" (don't refresh in the background when the watch is not open) and have iPhone X.. Thanks!

**Comment by dhermanns** [comment]
>
>
> Hi! This should have nothing to do with your iPhone. Just your
configuration of your background updates and the algorithm apple uses to
determine how many updates they allow. There are a lot of parameters apple
takes into account for that. E.g. if you use our complication, you should
get more updates.

**Comment by Babuci1** [comment]
Thank you for your answer.So we can't do anything.. I'm disappointed. So I have to sell my iwatch.. :-/My daugther is only 4, and the alarms are very important for me.Has anyone ever reported the problem for apple?
Thank you in advance..
Henrietta

Sent from Yahoo Mail for iPhone


On szerda, augusztus 26, 2020, 7:55 du., dhermanns <notifications@github.com> wrote:



>
>
> Hi! This should have nothing to do with your iPhone. Just your
configuration of your background updates and the algorithm apple uses to
determine how many updates they allow. There are a lot of parameters apple
takes into account for that. E.g. if you use our complication, you should
get more updates.

**Comment by dhermanns** [comment]
No - not reported to apple since this is works-as-designed for them. But
normally you should get notifications maybe 2 times an hour.

If you don‘t get any at all, you should check your settings on the
phone/watch.

Babuci1 <notifications@github.com> schrieb am Mi. 26. Aug. 2020 um 22:12:

>
>
>
> Thank you for your answer.So we can't do anything.. I'm disappointed. So I
> have to sell my iwatch.. :-/My daugther is only 4, and the alarms are very
> important for me.Has anyone ever reported the problem for apple?
>
>
>
> Thank you in advance..
>
>
>
> Henrietta
>
>
>
>
>
>
>
> Sent from Yahoo Mail for iPhone
>
>
>
>
>
>
>
>
>
>
>
> On szerda, augusztus 26, 2020, 7:55 du., dhermanns <

**Comment by Babuci1** [comment]
All of my notifications settings are correct (exactly like "adirazran").


2 times an hour..?😯 It is very dangerous for a little girl with T1DM.. :( the delta alarms would be the most important.. and not only 2 times/hour.I'm very sad about that..Unbelievable there is no solution..

Sent from Yahoo Mail for iPhone


On szerda, augusztus 26, 2020, 10:17 du., dhermanns <notifications@github.com> wrote:



No - not reported to apple since this is works-as-designed for them. But
normally you should get notifications maybe 2 times an hour.

If you don‘t get any at all, you should check your settings on the
phone/watch.

Babuci1 <notifications@github.com> schrieb am Mi. 26. Aug. 2020 um 22:12:

>
>
>
> Thank you for your answer.So we can't do anything.. I'm disappointed. So I
> have to sell my iwatch.. :-/My daugther is only 4, and the alarms are very
> important for me.Has anyone ever reported the problem for apple?
>
>
>
> Thank you in advance..
>
>
>
> Henrietta
>
>
>
>
>
>
>
> Sent from Yahoo Mail for iPhone
>
>
>
>
>
>
>
>
>
>
>
> On szerda, augusztus 26, 2020, 7:55 du., dhermanns <

**Comment by dhermanns** [comment]
As mentioned above, if you want immediate notification you should configure the pushover service. This is the way Apple wants this to be implemented.

If your child is very hard to keep in glucose range (like mine), you could be considering a looping solution like Android Aps.

**Comment by iteemh** [comment]
Hello Babuci1,

One solution is to dedicate a smartphone that runs the app 24/7 to be able to continuously monitor the glucose level and receive alerts. 

Kind regards,

**Comment by Babuci1** [comment]
Hello,
thanks!I’m aware of this, but there are situations when it doesn’t work. For example in a playground, etc. with a 4 years old little girl.. That would be the solution my iwatch... but it doesn't work.. and it's annoying.(I have an iPhone X and iwatch, my daugther has an Android with a Contour link and otg.. for nightscout. It's  already too much.)
Best regards


Sent from Yahoo Mail for iPhone


On péntek, augusztus 28, 2020, 8:22 de., iteemh <notifications@github.com> wrote:




Hello Babuci1,

One solution is to dedicate a smartphone that runs the app 24/7 to be able to continuously monitor the glucose level and receive alerts.

Kind regards,

**Comment by dhermanns** [comment]
You could keep the nightguard app open on your watch then. We get the
chance to give an alarm whenever your watchface lights up.

Babuci1 <notifications@github.com> schrieb am Sa. 29. Aug. 2020 um 08:23:

**Comment by Babuci1** [comment]
But it doesn't work, because after 10 min the watch is in "home position" and alarms are off..I get messenger, viber, sms but I don't get the nightguard alarm's.I have already sent screenshot, all of my settings are correct.
My veryfirst question was that: can cause this problem my Iphone X?I have more friends (also "diab parents..") and have the same issue.. So I'm not alone.
I would like to get the alarms from nightguard on my watch - always.. and not only 2 times/ hours, etc.

Sent from Yahoo Mail for iPhone


On szombat, augusztus 29, 2020, 9:03 de., dhermanns <notifications@github.com> wrote:



You could keep the nightguard app open on your watch then. We get the
chance to give an alarm whenever your watchface lights up.

Babuci1 <notifications@github.com> schrieb am Sa. 29. Aug. 2020 um 08:23:

**Comment by dhermanns** [comment]
Do other apps stay in foreground on your watch?

Babuci1 <notifications@github.com> schrieb am Sa. 29. Aug. 2020 um 09:22:

>
>
>
> But it doesn't work, because after 10 min the watch is in "home position"
> and alarms are off..I get messenger, viber, sms but I don't get the
> nightguard alarm's.I have already sent screenshot, all of my settings are
> correct.
>
>
>
> My veryfirst question was that: can cause this problem my Iphone X?I have
> more friends (also "diab parents..") and have the same issue.. So I'm not
> alone.
>
>
>
> I would like to get the alarms from nightguard on my watch - always..
> and not only 2 times/ hours, etc.
>
>
>
>
>
>
>
> Sent from Yahoo Mail for iPhone
>
>
>
>
>
>
>
>
>
>
>
> On szombat, augusztus 29, 2020, 9:03 de., dhermanns <

**Comment by iteemh** [comment]
Hello,

Have you also tried to turn on "Always on" setting under "Display and Brightness" setting of your Apple watch and turn ON "Wake Screen on Wrist Rise" and choosing "Always" setting for "On Screen Wake Show Last App"? This may allow you to run Nightguard app continuously. 

Kind regards,

**Comment by Babuci1** [comment]
This is what I see now.Don't refresh the nightguard and don't see my daugther's sugar and can't get any alarms on my watch from nightguard.I get other notifications (messenger, viber, call, weather, play, health..).





Sent from Yahoo Mail for iPhone


On szombat, augusztus 29, 2020, 9:45 de., iteemh <notifications@github.com> wrote:




Hello,

Have you also tried to turn on "Always on" setting under "Display and Brightness" setting of your Apple watch and turn ON "Wake Screen on Wrist Rise" and choosing "Always" setting for "On Screen Wake Show Last App"? This may allow you to run Nightguard app continuously.

Kind regards,

**Comment by Babuci1** [comment]
Everything is OK, but I can't turn on "Always on" setting under "Display and Brightness" setting of my Apple watch..
I attach the screenshots:







Sent from Yahoo Mail for iPhone


On szombat, augusztus 29, 2020, 9:45 de., iteemh <notifications@github.com> wrote:




Hello,

Have you also tried to turn on "Always on" setting under "Display and Brightness" setting of your Apple watch and turn ON "Wake Screen on Wrist Rise" and choosing "Always" setting for "On Screen Wake Show Last App"? This may allow you to run Nightguard app continuously.

Kind regards,

**Comment by iteemh** [comment]
Your screenshots are not showing for some reason. I am not entirely sure why your Apple watch is not giving you the option to turn on "Always on" setting. I think in this case you should get in touch with Apple Tech Support to show you how you could keep the display of your Apple watch always ON, as this option should be available. 

Best regards,

**Comment by Babuci1** [comment]
Dear All,
many thanks for your help!!I have the solution.. I have iwatch series 4.. and on this I couldn't turn the screen always on :( My friend showed me her screenshot, she has apple watch series 5 and she has this option already.. (both have iPhone X, software 13.6.1.)I hope you can see the screenshots.

Thanks again!
Best regards,
Henrietta





Sent from Yahoo Mail for iPhone


On szombat, augusztus 29, 2020, 11:28 de., iteemh <notifications@github.com> wrote:




Your screenshots are not showing for some reason. I am not entirely sure why your Apple watch is not giving you the option to turn on "Always on" setting. I think in this case you should get in touch with Apple Tech Support to show you how you could keep the display of your Apple watch always ON, as this option should be available.

Best regards,

**Comment by iteemh** [comment]
Aha that's the reason why then. Too bad that this option is only available on series 5. I hope Apple introduces this option to the older series as well. 

You're welcome! I wish you all the best.

Kind regards,

**Comment by Babuci1** [comment]
Thank you, I hope the same :) 
Best regards,
Henrietta


Sent from Yahoo Mail for iPhone


On szombat, augusztus 29, 2020, 12:08 du., iteemh <notifications@github.com> wrote:




Aha that's the reason why then. Too bad that this option is only available on series 5. I hope Apple introduces this option to the older series as well.

You're welcome! I wish you all the best.

Kind regards,

**Comment by muhannad-alh** [comment]
Hello,

Since today, I have been unable to access Nightscout to monitor the blood sugar level on both my iphone and the website. The below error message appears on the website: 

Unable to connect to Mongo
{"stack":"Error: MongoDB connection string is missing. Please set MONGO_CONNECTION environment variable
at maybe_connect (/app/lib/storage/mongo-storage.js:23:15)
at init (/app/lib/storage/mongo-storage.js:77:10)
at setupStorage (/app/lib/server/bootevent.js:117:44)
at Object. (/app/node_modules/bootevent/index.js:12:7)
at EventEmitter.saw.nest (/app/node_modules/chainsaw/index.js:86:12)
at Object.acquire (/app/node_modules/bootevent/index.js:10:9)
at saw.next (/app/node_modules/chainsaw/index.js:62:18)
at augmentSettings (/app/lib/server/bootevent.js:94:7)
at Object. (/app/node_modules/bootevent/index.js:12:7)
at EventEmitter.saw.nest (/app/node_modules/chainsaw/index.js:86:12)","message":"MongoDB connection string is missing. Please set MONGO_CONNECTION environment variable"}

Can you please help me identify what the problem is and how it can be fixed?

I appreciate your support.

Kind regards,

Muhannad

**Comment by dhermanns** [comment]
Hi!

This is the wrong place for your question.
It is regarding the cgm-remote-monitor.

But I would say you didn‘t set the connection string to your database:

Please set MONGO_CONNECTION environment variable

Cu,
Dirk

**Comment by muhannad-alh** [comment]
@dhermanns Thank you very much. Correct, mongo_connection was missing. 

Best,

**Comment by hanoii** [comment]
Hey all, in helping a friend dealing with this I ended up setting him with

IFTTT+Integromat+Twilio for sms/phone calls.

Basically nightscout will send notifications to IFTTT, IFTTT will call a webhook on Integromat and integromat will either make a phone call for urgent alarms and send sms for those as well as the regular warnings. Just mentioning this here in case it helps any one of you or the rest. Obviously some of this comes at an expense (so far only paying for twilio but might end up paying for integromat as well)

**Comment by dhermanns** [comment]
Thanks for your feedback. Another option could be to enable pushover on
your nightscout backend.

Am Do., 18. Nov. 2021 um 19:55 Uhr schrieb Ariel Barreiro <
***@***.***>:

**Comment by cmayrink** [comment]
After so long, is there any solution to solve the problem with nightscout notifications when it is in the background?

**Comment by dhermanns** [comment]
As described above. They should work as designed. But they will never update as we would like them to do: Every 5 minutes.

Sorry.
