### ISSUE TITLE
I want to translate this app to simplified Chinese

### ISSUE THREAD

**Issue by jizhongwen** [nightscout/nightguard#78]
Hi, Dhermanns 
This app is really helpful for us, I want to translate this app to simplified Chinese, where I can translate it? My mail address is 68481617@163.com. Thank you.

**Comment by dhermanns** [comment]
Hi!

Thanks for your offering. We are trying to keep
the app as simple and stable as possible.

This is because we haven‘t localized it.
So there is no simple way to translate it.

Sorry!

**Comment by jizhongwen** [comment]
Got it, thanks.
