### ISSUE TITLE
apple Watch issue

### ISSUE THREAD

**Issue by timwa124** [nightscout/nightguard#8]
Thanks for sharing your new version:

#1 Zoom Mode: not stable right now. if i scroll to the past, it jumps back again to the actual value
#2 Zoom Mode: Values above 180 will be shown as green after zoom out to see the whole diagram.
#3  Scroll Mode: High values above 180 and below 80 will be shown as flat. would be nice to see the high or low values in more detail

it's so great to have your nightguard app! Its much more easy to handle our son's diabetes (4years old)... we love it!!

**Comment by dhermanns** [comment]
Great to hear this is of some help for others. It was build for my 6 year old son ;-).

#1 should happen only if new values were loaded. If that's the case, it's supposed to be a feature ;-).
You can scroll to the past but will be aware of the new values as soon as there are new values from the backend.

#2 Which Version of the are you running? I've already pushed a beta version 1.4.0.97. In this version I'm painting a red line to indicate that there are values above 180 when zooming out.

#3 You can zoom out first. If you then start scrolling you should see values above 180 or below 80 (as good as the small apple watch display allows me to ;-).

I'm planning to let you select certain values by scrolling. Maybe this would be useful for #3, too.

**Comment by dhermanns** [comment]
Just pushed V1.4.0.98. Maybe you can wait until Apple activates it for beta testing. A problem with resetting the zoom level, after new values are read from the backend, is fixed in it.

**Comment by dhermanns** [comment]
Hope this is fixed now. Feel free to reopen otherwise.
