### ISSUE TITLE
Feature request: Re-enable screen rotating when on 'Fullscreen monitor'

### ISSUE THREAD

**Issue by marcusfpereira** [nightscout/nightguard#84]
Version 2.7.2 disabled screen rotating when on "Fullscreen monitor" mode.
All my phone supports are adapted to keep the phone on landscape position and I keep monitoring  almost all day.
Without screen rotating is very annoying to have the numbers and letters rotated.

Please re-enable screen rotating when on Fullscreen monitor mode.

**Comment by dhermanns** [comment]
This was a change that has been introduced with xcode 11. The default for popups have been changed. But I was able to opt out to the real fullscreen we know from IOS12. 
The upcoming version 2.7.3 will have it. Testflight version is already available.

**Comment by dhermanns** [comment]
Still not working with 2.7.3 - sorry. But upcoming 2.7.4 should have screen rotation again.
