### ISSUE TITLE
Always snoozed for 1 minute

### ISSUE THREAD

**Issue by Rijak0** [nightscout/nightguard#87]
Hey there!

First of all thanks for making that Wunderheiler App. Looks and feels great!
But somehow I do not get alerts - when I open the App, it‘s always snoozed for 1 Minute. 
When I wait inside the App, alarms will start after one minute.
Am I doing something wrong?

Thanks a lot!

**Comment by dhermanns** [comment]
Hi!

The snooze if you open the App is intended: It prevents immediate alarms
the would play maybe just the app hasn‘t time to update to new values.

But hard to say what‘s wrong with your setup. Do you see values and are
they in your configured range?

**Comment by dhermanns** [comment]
Ah - I think I get it: You have to have the app opened all the time to get alarms. Otherwise you could get push notifications when the app is in background. But this is not often enough e.g. to use it at night.

**Comment by Rijak0** [comment]
Hey dhermanns,

thank you for your fast response and sorry for my slow response ;)
I am using the app now with the screen on at night, works perfectly.
Just that I get it right - are permissions the problem that an alarm can't be triggered when the app is running in the background? Or can the polling process not run in the background?
I used Android with Nightscout before, there it's possible to do set alarms also when the app is not open.

Thanks a lot!

**Comment by dhermanns** [comment]
Hi Rijak,

no problem. Yes - it's very hard to force alarms on an iOS device. We already have background updates implemented. But apple decides how many updates an hour your app is allowed to do.

On android this is easier to achieve. But during the different android version updates, this has got more restrictive, too. It's all about battery life.

But good to hear, that you have it up and running now.

**Comment by Rijak0** [comment]
Hey dhermanns,

alright, thanks a lot!
Unfortunately I am very busy at the moment and don't have much experience in native iOS development but hopefully I get to contribute to this project (or other open source projects of this type) in some way soon.
Appreciate what you're doing here a lot!

Thank you once again and have a nice day!
