### ISSUE TITLE
Apple Watch alert

### ISSUE THREAD

**Issue by timwa124** [nightscout/nightguard#9]
Hi,

i now this isn't a "issue" but i'm not aware how to send a feature request :)

Would it be possible to get an alert if a high / low value is passed? today i use pushover for this, but it would be great to have it in your app (on apple watch) directly :)

have a nice week 

best Markus

**Comment by dhermanns** [comment]
Hi Markus,

yes - I really would like to have such a feature, too. But as far as I now - the only way Apple lets you do something on the watch without user interaction, is by sending push notifications.

So I don't know a reliable way to get alerts working directly on the watch :-/ . Apple seems to be protecting their battery runtime by all means...

But maybe someone else has an idea of how to get reliable alerts just by running the watch app!?

**Comment by dhermanns** [comment]
Please reopen if someone has an idea how to achieve the reliable alerts on the watch...
