### ISSUE TITLE
Feature Request: Display Insulin Treatments

### ISSUE THREAD

**Issue by evovinetu** [nightscout/nightguard#93]
Thank you for this amazing app, it's the best of all!!! 

I miss one feature though: icons on the chart's line indicating insulin treatments (blue bubbles in Nightscout website) with a possibility to tap on it and see more info.
Is it in the plans anytime soon?..

Cheers!
Evo

![nightscout_x](https://user-images.githubusercontent.com/4004367/81203709-ec617180-8fd0-11ea-82e8-64375032e0e7.PNG)

**Comment by dhermanns** [comment]
Hi! No - not planned now. Did you notice that ja can long press the target
button and get all this information from the embedded nightscout Web-App?

**Comment by evaldasjab** [comment]
Nice! No, i didn't know it, thanks :)

**Comment by dhermanns** [comment]
I will keep this ticket here as a possible enhancement request.

**Comment by jonfawcett** [comment]
@dhermanns  Parent following a DD on dex, pod, Loop... I've found with all the extra data displays from automatic-bolus that Nightscout (via Safari or web-wrapper apps) gets very very slow on mobile. So I've been working on a new app to try and solve this for a concise view of BG, Basal, Bolus, and Carbs. When I saw this request I tried to see how hard it would be to get https://github.com/danielgindi/Charts integrated into Nightguard. The benefit with this is you can add multiple charts overlaid. So once it's setup, it shouldn't be hard to add additional NS calls for treatments to add to the graph. It also has a lot of options that can easily be dropped into user settings like spike has (lines, dots, colors, etc) Is this something you think is worth pursuing?

![IMG_0799](https://user-images.githubusercontent.com/38429455/83772648-9aece680-a651-11ea-8187-dd1762c9ba58.png)

**Comment by dhermanns** [comment]
I already had a look at different graph libraries before starting an own
one. This was because every library I looked for was too limited.

Your one looks great. On a long perspective I would like to have a chart
like in Android APS. But I think you will have to do your own painting to
achieve this.

**Comment by jonfawcett** [comment]
Yes...Charts is missing a few things I would like to do just like all the libraries I’ve seen. But I think I have a workaround for them. I’ll let you know once I have this running in my app and you can look to see how I did everything if you want to incorporate it.

**Comment by dhermanns** [comment]
Curious to see it!

**Comment by tromanisagit** [comment]
I too wanted to see the treatment data on the graph.  Just read your comment about the long press on the target. Works well.  Would be good to get this on the apple watch interface (if its not?)

**Comment by dhermanns** [comment]
The watch isn‘t able to display the website. But I think displaying carbs
and boluses directly on the graph would be amazing.

If I find some time that could be next.

>
>

**Comment by tromanisagit** [comment]
Fab update - thanks

**Comment by dhermanns** [comment]
This is available now.

**Comment by evovinetu** [comment]
Unfortunately I still don't see it :( 
Version 3.3.0.712.

Should I change something in settings?

![nightscout](https://user-images.githubusercontent.com/4004367/116690780-909eae00-a9c2-11eb-81ba-feab48282a03.jpg)
![nightguard](https://user-images.githubusercontent.com/4004367/116690803-985e5280-a9c2-11eb-8401-0d9d68d7c782.png)

**Comment by dhermanns** [comment]
Hi Evo!

You could try the latest TestFlight and let me know if that helps:

https://testflight.apple.com/join/Ub8WcpcE


Evo Vinetu ***@***.***> schrieb am Fr. 30. Apr. 2021 um 13:46:
