### ISSUE TITLE
Not able to enter herokuapp link

### ISSUE THREAD

**Issue by severiti** [nightscout/nightguard#95]
Hi,  when entering my Nightscout link the app doesn’t react. I tried on several ways but no result

**Comment by dhermanns** [comment]
Hi Severiti,

you can send me your URI and I will have a look. If you like you can use my
twitter handle h3rmanns.

Dirk

**Comment by severiti** [comment]
Hi,

its https://kimdia.herokuapp.com/



Op ma 18 mei 2020 om 20:58 schreef dhermanns <notifications@github.com>:

**Comment by dhermanns** [comment]
I could open it just fine. App stays stable. But maybe just because I have
my old values in cache. When I have a direct look using the webapp, I see
that you have no values in your backend so far, right?

Maybe you should upload some data and see if nightguard is able to display
them.

**Comment by severiti** [comment]
Hi thanks, seems to be resolved now

Op ma 18 mei 2020 om 23:12 schreef dhermanns <notifications@github.com>:

**Comment by dhermanns** [comment]
Happy to hear that!
