### ISSUE TITLE
New localized strings

### ISSUE THREAD

**Issue by dhermanns** [nightscout/nightguard#97]
Hi Markus (@makotila)!

Could you have a look here:
https://github.com/nightscout/nightguard/blob/master/nightguard/Base.lproj/Localizable.strings

I've got a few new labels for the "disable all alerts" feature.

**Comment by makotila** [comment]
@dhermanns Hi, Finnish translations in PR #98

**Comment by dhermanns** [comment]
Great - thanks Markus!
