### ISSUE TITLE
watch complication not updating every 5 minutes

### ISSUE THREAD

**Issue by YoeriR** [nightscout/nightguard#99]
not sure if this has been a FAQ but, on my iWatch 5 icm iPhone XR both on latest OS. I use xdrip4ios for the readings of my MiaoMiao, this sends it to my nightscout. which is read by night guard on my phone and watch. 
my nightguard watch complication isn't updating every time it gets a new reading, why is this and can this be resolved?

thanks in advance.

Yoeri Rol

**Comment by dhermanns** [comment]
Hi YoeriR!

Yes - this is right and is a limitation from Apple to protect the battery
life. My experience is that updates about 1 to 2 times an hour are allowed.
We already had the clearance from apple as a medical app which could leed
to more possibilities, but I hadn‘t had the time to go into this in more
detail.

So right now you will have to keep the app in foreground to force updates.

Cu,
Dirk

**Comment by YoeriR** [comment]
aaah allright! thanks for the super quick answer!

**Comment by dhermanns** [comment]
Welcome ;-)
